var resData = [
    {
        "name":"ad_png",
        "type":"image",
        "url":"ad.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    },
    {
        "name":"logo_jpg",
        "type":"image",
        "url":"logo.jpg"
    },
    {
        "name":"love_png",
        "type":"image",
        "url":"love.png"
    },
    {
        "name":"music_gif",
        "type":"image",
        "url":"music.gif"
    },
    {
        "name":"naiyou_png",
        "type":"image",
        "url":"naiyou.png"
    },
    {
        "name":"pic-1_png",
        "type":"image",
        "url":"pic-1.png"
    },
    {
        "name":"pro_png",
        "type":"image",
        "url":"pro.png"
    },
    {
        "name":"pro-n_png",
        "type":"image",
        "url":"pro-n.png"
    },
    {
        "name":"top-l_png",
        "type":"image",
        "url":"top-l.png"
    },
    {
        "name":"w-1_png",
        "type":"image",
        "url":"w-1.png"
    },
    {
        "name":"w-2_png",
        "type":"image",
        "url":"w-2.png"
    },
    {
        "name":"w-3_png",
        "type":"image",
        "url":"w-3.png"
    },
    {
        "name":"word-1_png",
        "type":"image",
        "url":"word-1.png"
    },
    {
        "name":"word-2_png",
        "type":"image",
        "url":"word-2.png"
    },
    {
        "name":"ad_jpg",
        "type":"image",
        "url":"ad.jpg"
    }
];