var resData = [
    {
      "name":"t1_png",
      "type":"image",
      "url":"t1.png"
    },
    {
      "name":"t2_png",
      "type":"image",
      "url":"t2.png"
    },
    {
      "name":"title_png",
      "type":"image",
      "url":"title.png"
    },
    {
      "name":"top-bg_png",
      "type":"image",
      "url":"top-bg.png"
    },
    {
      "name":"btn-decorator_png",
      "type":"image",
      "url":"btn-decorator.png"
    },
    {
      "name":"footer-bg_jpg",
      "type":"image",
      "url":"footer-bg.jpg"
    },
    {
      "name":"footer-text_png",
      "type":"image",
      "url":"footer-text.png"
    },
    {
      "name":"main-text_png",
      "type":"image",
      "url":"main-text.png"
    },
    {
      "name":"p1-1_png",
      "type":"image",
      "url":"p1-1.png"
    },
    {
      "name":"p1-2_png",
      "type":"image",
      "url":"p1-2.png"
    },
    {
      "name":"p2-1_png",
      "type":"image",
      "url":"p2-1.png"
    },
    {
      "name":"p2-2_png",
      "type":"image",
      "url":"p2-2.png"
    },
    {
      "name":"p3-3_png",
      "type":"image",
      "url":"p3-3.png"
    },
    {
      "name":"price1_png",
      "type":"image",
      "url":"price1.png"
    },
    {
      "name":"price2_png",
      "type":"image",
      "url":"price2.png"
    }];