var resData = [
    {
        "name":"title-2-ms_png",
        "type":"image",
        "url":"title-2-ms.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"word-1_png",
        "type":"image",
        "url":"word-1.png"
    },
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-title_png",
        "type":"image",
        "url":"cake-title.png"
    },
    {
        "name":"go-ms_png",
        "type":"image",
        "url":"go-ms.png"
    },
    {
        "name":"haoli_png",
        "type":"image",
        "url":"haoli.png"
    },
    {
        "name":"jingxi_png",
        "type":"image",
        "url":"jingxi.png"
    },
    {
        "name":"ms-time_png",
        "type":"image",
        "url":"ms-time.png"
    },
    {
        "name":"quan-1_png",
        "type":"image",
        "url":"quan-1.png"
    },
    {
        "name":"quan-2_png",
        "type":"image",
        "url":"quan-2.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    }
];