var resData = [
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"wnl_png",
        "type":"image",
        "url":"wnl.png"
    },
    {
        "name":"b-1_png",
        "type":"image",
        "url":"b-1.png"
    },
    {
        "name":"b-2_png",
        "type":"image",
        "url":"b-2.png"
    },
    {
        "name":"b-3_png",
        "type":"image",
        "url":"b-3.png"
    },
    {
        "name":"b-bg_png",
        "type":"image",
        "url":"b-bg.png"
    },
    {
        "name":"card-1_png",
        "type":"image",
        "url":"card-1.png"
    },
    {
        "name":"card-2_png",
        "type":"image",
        "url":"card-2.png"
    },
    {
        "name":"card-3_png",
        "type":"image",
        "url":"card-3.png"
    },
    {
        "name":"cartery-1_png",
        "type":"image",
        "url":"cartery-1.png"
    },
    {
        "name":"cartery-2_png",
        "type":"image",
        "url":"cartery-2.png"
    },
    {
        "name":"coffee_png",
        "type":"image",
        "url":"coffee.png"
    },
    {
        "name":"fd_png",
        "type":"image",
        "url":"fd.png"
    },
    {
        "name":"fd-1_png",
        "type":"image",
        "url":"fd-1.png"
    },
    {
        "name":"fd-2_png",
        "type":"image",
        "url":"fd-2.png"
    },
    {
        "name":"fd-pic_png",
        "type":"image",
        "url":"fd-pic.png"
    },
    {
        "name":"gz_png",
        "type":"image",
        "url":"gz.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"img-4_png",
        "type":"image",
        "url":"img-4.png"
    },
    {
        "name":"li-style_png",
        "type":"image",
        "url":"li-style.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    }
];