var resData = [
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-bg_png",
        "type":"image",
        "url":"img-bg.png"
    },
    {
        "name":"kj-bg_png",
        "type":"image",
        "url":"kj-bg.png"
    },
    {
        "name":"nobody_png",
        "type":"image",
        "url":"nobody.png"
    },
    {
        "name":"pay-ok_png",
        "type":"image",
        "url":"pay-ok.png"
    },
    {
        "name":"percent-1_png",
        "type":"image",
        "url":"percent-1.png"
    },
    {
        "name":"percent-2_png",
        "type":"image",
        "url":"percent-2.png"
    },
    {
        "name":"pt-banner_png",
        "type":"image",
        "url":"pt-banner.png"
    },
    {
        "name":"share_png",
        "type":"image",
        "url":"share.png"
    },
    {
        "name":"share-btn_png",
        "type":"image",
        "url":"share-btn.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"btn-home_png",
        "type":"image",
        "url":"btn-home.png"
    },
    {
        "name":"btn-my_png",
        "type":"image",
        "url":"btn-my.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"get-pp_png",
        "type":"image",
        "url":"get-pp.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    }
];