var resData = [
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake2_png",
        "type":"image",
        "url":"cake2.png"
    },
    {
        "name":"code1_png",
        "type":"image",
        "url":"code1.png"
    },
    {
        "name":"code2_png",
        "type":"image",
        "url":"code2.png"
    },
    {
        "name":"step1_png",
        "type":"image",
        "url":"step1.png"
    },
    {
        "name":"step2_png",
        "type":"image",
        "url":"step2.png"
    },
    {
        "name":"gh_png",
        "type":"image",
        "url":"gh.png"
    }
];