var resData = [
    {
        "name":"quan-2_png",
        "type":"image",
        "url":"quan-2.png"
    },
    {
        "name":"s-title_png",
        "type":"image",
        "url":"s-title.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"acrow_png",
        "type":"image",
        "url":"acrow.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"bj_cp1_png",
        "type":"image",
        "url":"bj_cp1.png"
    },
    {
        "name":"bj_cp2_png",
        "type":"image",
        "url":"bj_cp2.png"
    },
    {
        "name":"bj_cp3_png",
        "type":"image",
        "url":"bj_cp3.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cp1_png",
        "type":"image",
        "url":"cp1.png"
    },
    {
        "name":"cp2_png",
        "type":"image",
        "url":"cp2.png"
    },
    {
        "name":"cp3_png",
        "type":"image",
        "url":"cp3.png"
    },
    {
        "name":"cp-title_png",
        "type":"image",
        "url":"cp-title.png"
    },
    {
        "name":"go-btn_png",
        "type":"image",
        "url":"go-btn.png"
    },
    {
        "name":"in-l_png",
        "type":"image",
        "url":"in-l.png"
    },
    {
        "name":"in-l-h_png",
        "type":"image",
        "url":"in-l-h.png"
    },
    {
        "name":"in-r_png",
        "type":"image",
        "url":"in-r.png"
    },
    {
        "name":"in-r-h_png",
        "type":"image",
        "url":"in-r-h.png"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    },
    {
        "name":"minus_png",
        "type":"image",
        "url":"minus.png"
    },
    {
        "name":"plus_png",
        "type":"image",
        "url":"plus.png"
    },
    {
        "name":"quan-1_png",
        "type":"image",
        "url":"quan-1.png"
    }
];