var resData = [
    {
        "name":"logo_png",
        "type":"image",
        "url":"logo.png"
    },
    {
        "name":"lv_png",
        "type":"image",
        "url":"lv.png"
    },
    {
        "name":"mx_png",
        "type":"image",
        "url":"mx.png"
    },
    {
        "name":"pr-1_png",
        "type":"image",
        "url":"pr-1.png"
    },
    {
        "name":"pr-2_png",
        "type":"image",
        "url":"pr-2.png"
    },
    {
        "name":"sb_png",
        "type":"image",
        "url":"sb.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"yh_png",
        "type":"image",
        "url":"yh.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"btn-bg_png",
        "type":"image",
        "url":"btn-bg.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"ds-1_png",
        "type":"image",
        "url":"ds-1.png"
    },
    {
        "name":"ds-2_png",
        "type":"image",
        "url":"ds-2.png"
    },
    {
        "name":"ds-3_png",
        "type":"image",
        "url":"ds-3.png"
    },
    {
        "name":"ds-4_png",
        "type":"image",
        "url":"ds-4.png"
    }
];