var resData = [
<<<<<<< HEAD
    {
        "name":"logo_png",
        "type":"image",
        "url":"logo.png"
    },
    {
        "name":"lv_png",
        "type":"image",
        "url":"lv.png"
    },
    {
        "name":"mx_png",
        "type":"image",
        "url":"mx.png"
    },
    {
        "name":"pr-1_png",
        "type":"image",
        "url":"pr-1.png"
    },
    {
        "name":"pr-2_png",
        "type":"image",
        "url":"pr-2.png"
    },
    {
        "name":"sb_png",
        "type":"image",
        "url":"sb.png"
    },
    {
        "name":"m-title_png",
        "type":"image",
        "url":"m-title.png"
    },
    {
        "name":"m-yh_png",
        "type":"image",
        "url":"m-yh.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"btn-bg_png",
        "type":"image",
        "url":"btn-bg.png"
    },
    {
        "name":"m-cake-1_png",
        "type":"image",
        "url":"m-cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"ds-1_png",
        "type":"image",
        "url":"ds-1.png"
    },
    {
        "name":"ds-2_png",
        "type":"image",
        "url":"ds-2.png"
    },
    {
        "name":"ds-3_png",
        "type":"image",
        "url":"ds-3.png"
    },
    {
        "name":"m-ds-4_png",
        "type":"image",
        "url":"m-ds-4.png"
    }
    ,
    {
        "name":"ds-5_png",
        "type":"image",
        "url":"ds-5.png"
    }
];
=======
  {
    "name":"0_png",
    "type":"image",
    "url":"0.png"
  },
  {
    "name":"1_png",
    "type":"image",
    "url":"1.png"
  },
  {
    "name":"2_png",
    "type":"image",
    "url":"2.png"
  },
  {
    "name":"3_png",
    "type":"image",
    "url":"3.png"
  },
  {
    "name":"4_png",
    "type":"image",
    "url":"4.png"
  },
  {
    "name":"5_png",
    "type":"image",
    "url":"5.png"
  },
  {
    "name":"6_png",
    "type":"image",
    "url":"6.png"
  },
  {
    "name":"7_png",
    "type":"image",
    "url":"7.png"
  },
  {
    "name":"8_png",
    "type":"image",
    "url":"8.png"
  },
  {
    "name":"9_png",
    "type":"image",
    "url":"9.png"
  },
  {
    "name":"banner-bg_jpg",
    "type":"image",
    "url":"banner-bg.jpg"
  },
  {
    "name":"banner-text_png",
    "type":"image",
    "url":"banner-text.png"
  },
  {
    "name":"cake_png",
    "type":"image",
    "url":"cake.png"
  },
  {
    "name":"cake-sm_png",
    "type":"image",
    "url":"cake-sm.png"
  },
  {
    "name":"cake-tips_png",
    "type":"image",
    "url":"cake-tips.png"
  },
  {
    "name":"checkbox_png",
    "type":"image",
    "url":"checkbox.png"
  },
  {
    "name":"counter-bg_png",
    "type":"image",
    "url":"counter-bg.png"
  },
  {
    "name":"deco1_png",
    "type":"image",
    "url":"deco1.png"
  },
  {
    "name":"deco2_png",
    "type":"image",
    "url":"deco2.png"
  },
  {
    "name":"deco3_png",
    "type":"image",
    "url":"deco3.png"
  },
  {
    "name":"deco4_png",
    "type":"image",
    "url":"deco4.png"
  },
  {
    "name":"footer-action_png",
    "type":"image",
    "url":"footer-action.png"
  },
  {
    "name":"logo_png",
    "type":"image",
    "url":"logo.png"
  },
  {
    "name":"main-bg_jpg",
    "type":"image",
    "url":"main-bg.jpg"
  },
  {
    "name":"main-cake_png",
    "type":"image",
    "url":"main-cake.png"
  },
  {
    "name":"main-text_png",
    "type":"image",
    "url":"main-text.png"
  },
  {
    "name":"nut_png",
    "type":"image",
    "url":"nut.png"
  },
  {
    "name":"spoon_png",
    "type":"image",
    "url":"spoon.png"
  }];
>>>>>>> c1968ce4116819a09b05eaa02268519ebafc1600
