var resData = [
    {
        "name":"ms-small-img-13_jpg",
        "type":"image",
        "url":"ms-small-img-13.jpg"
    },
    {
        "name":"ms-sq_png",
        "type":"image",
        "url":"ms-sq.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"nut_png",
        "type":"image",
        "url":"nut.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"spoon_png",
        "type":"image",
        "url":"spoon.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"top_png",
        "type":"image",
        "url":"top.png"
    },
    {
        "name":"top-1_png",
        "type":"image",
        "url":"top-1.png"
    },
    {
        "name":"top-2_png",
        "type":"image",
        "url":"top-2.png"
    },
    {
        "name":"ad_jpg",
        "type":"image",
        "url":"ad.jpg"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"car-icon_png",
        "type":"image",
        "url":"car-icon.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"dot_png",
        "type":"image",
        "url":"dot.png"
    },
    {
        "name":"footer-action_png",
        "type":"image",
        "url":"footer-action.png"
    },
    {
        "name":"haoli-pic-1_jpg",
        "type":"image",
        "url":"haoli-pic-1.jpg"
    },
    {
        "name":"haoli-pic-2_jpg",
        "type":"image",
        "url":"haoli-pic-2.jpg"
    },
    {
        "name":"haoli-pic-3_jpg",
        "type":"image",
        "url":"haoli-pic-3.jpg"
    },
    {
        "name":"haoli-pic-4_jpg",
        "type":"image",
        "url":"haoli-pic-4.jpg"
    },
    {
        "name":"haoli-pic-5_jpg",
        "type":"image",
        "url":"haoli-pic-5.jpg"
    },
    {
        "name":"haoli-pic-6_jpg",
        "type":"image",
        "url":"haoli-pic-6.jpg"
    },
    {
        "name":"haoli-pic-7_jpg",
        "type":"image",
        "url":"haoli-pic-7.jpg"
    },
    {
        "name":"icon-1_png",
        "type":"image",
        "url":"icon-1.png"
    },
    {
        "name":"icon-2_png",
        "type":"image",
        "url":"icon-2.png"
    },
    {
        "name":"icon-3_png",
        "type":"image",
        "url":"icon-3.png"
    },
    {
        "name":"icon-4_png",
        "type":"image",
        "url":"icon-4.png"
    },
    {
        "name":"icon-5_png",
        "type":"image",
        "url":"icon-5.png"
    },
    {
        "name":"icon-6_png",
        "type":"image",
        "url":"icon-6.png"
    },
    {
        "name":"img-1_jpg",
        "type":"image",
        "url":"img-1.jpg"
    },
    {
        "name":"img-2_jpg",
        "type":"image",
        "url":"img-2.jpg"
    },
    {
        "name":"img-3_jpg",
        "type":"image",
        "url":"img-3.jpg"
    },
    {
        "name":"img-4_jpg",
        "type":"image",
        "url":"img-4.jpg"
    },
    {
        "name":"img-5_jpg",
        "type":"image",
        "url":"img-5.jpg"
    },
    {
        "name":"img-6_jpg",
        "type":"image",
        "url":"img-6.jpg"
    },
    {
        "name":"img-7_jpg",
        "type":"image",
        "url":"img-7.jpg"
    },
    {
        "name":"img-8_jpg",
        "type":"image",
        "url":"img-8.jpg"
    },
    {
        "name":"logo_png",
        "type":"image",
        "url":"logo.png"
    },
    {
        "name":"main-bg_jpg",
        "type":"image",
        "url":"main-bg.jpg"
    },
    {
        "name":"main-cake_png",
        "type":"image",
        "url":"main-cake.png"
    },
    {
        "name":"main-text_png",
        "type":"image",
        "url":"main-text.png"
    },
    {
        "name":"ms-biao_png",
        "type":"image",
        "url":"ms-biao.png"
    },
    {
        "name":"ms-big-img-1_jpg",
        "type":"image",
        "url":"ms-big-img-1.jpg"
    },
    {
        "name":"ms-big-img-2_jpg",
        "type":"image",
        "url":"ms-big-img-2.jpg"
    },
    {
        "name":"ms-big-img-3_jpg",
        "type":"image",
        "url":"ms-big-img-3.jpg"
    },
    {
        "name":"ms-big-img-4_jpg",
        "type":"image",
        "url":"ms-big-img-4.jpg"
    },
    {
        "name":"ms-big-img-5_jpg",
        "type":"image",
        "url":"ms-big-img-5.jpg"
    },
    {
        "name":"ms-big-img-6_jpg",
        "type":"image",
        "url":"ms-big-img-6.jpg"
    },
    {
        "name":"ms-big-img-7_jpg",
        "type":"image",
        "url":"ms-big-img-7.jpg"
    },
    {
        "name":"ms-big-img-8_jpg",
        "type":"image",
        "url":"ms-big-img-8.jpg"
    },
    {
        "name":"ms-big-img-9_jpg",
        "type":"image",
        "url":"ms-big-img-9.jpg"
    },
    {
        "name":"ms-big-img-10_jpg",
        "type":"image",
        "url":"ms-big-img-10.jpg"
    },
    {
        "name":"ms-big-img-11_jpg",
        "type":"image",
        "url":"ms-big-img-11.jpg"
    },
    {
        "name":"ms-big-img-12_jpg",
        "type":"image",
        "url":"ms-big-img-12.jpg"
    },
    {
        "name":"ms-big-img-13_jpg",
        "type":"image",
        "url":"ms-big-img-13.jpg"
    },
    {
        "name":"ms-logo_png",
        "type":"image",
        "url":"ms-logo.png"
    },
    {
        "name":"ms-small-img-0_png",
        "type":"image",
        "url":"ms-small-img-0.png"
    },
    {
        "name":"ms-small-img-1_jpg",
        "type":"image",
        "url":"ms-small-img-1.jpg"
    },
    {
        "name":"ms-small-img-2_jpg",
        "type":"image",
        "url":"ms-small-img-2.jpg"
    },
    {
        "name":"ms-small-img-3_jpg",
        "type":"image",
        "url":"ms-small-img-3.jpg"
    },
    {
        "name":"ms-small-img-4_jpg",
        "type":"image",
        "url":"ms-small-img-4.jpg"
    },
    {
        "name":"ms-small-img-5_jpg",
        "type":"image",
        "url":"ms-small-img-5.jpg"
    },
    {
        "name":"ms-small-img-6_jpg",
        "type":"image",
        "url":"ms-small-img-6.jpg"
    },
    {
        "name":"ms-small-img-7_jpg",
        "type":"image",
        "url":"ms-small-img-7.jpg"
    },
    {
        "name":"ms-small-img-8_jpg",
        "type":"image",
        "url":"ms-small-img-8.jpg"
    },
    {
        "name":"ms-small-img-9_jpg",
        "type":"image",
        "url":"ms-small-img-9.jpg"
    },
    {
        "name":"ms-small-img-10_jpg",
        "type":"image",
        "url":"ms-small-img-10.jpg"
    },
    {
        "name":"ms-small-img-11_jpg",
        "type":"image",
        "url":"ms-small-img-11.jpg"
    },
    {
        "name":"ms-small-img-12_jpg",
        "type":"image",
        "url":"ms-small-img-12.jpg"
    }
];