var resData = [
    {
        "name":"s-title_png",
        "type":"image",
        "url":"s-title.png"
    },
    {
        "name":"yuebing_png",
        "type":"image",
        "url":"yuebing.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"code_png",
        "type":"image",
        "url":"code.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"price-1_png",
        "type":"image",
        "url":"price-1.png"
    },
    {
        "name":"price-2_png",
        "type":"image",
        "url":"price-2.png"
    }
];