var resData = [
    {
        "name":"small-pic-1_png",
        "type":"image",
        "url":"small-pic-1.png"
    },
    {
        "name":"small-pic-2_png",
        "type":"image",
        "url":"small-pic-2.png"
    },
    {
        "name":"small-pic-3_png",
        "type":"image",
        "url":"small-pic-3.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"tree_png",
        "type":"image",
        "url":"tree.png"
    },
    {
        "name":"tuzi_png",
        "type":"image",
        "url":"tuzi.png"
    },
    {
        "name":"word-1_png",
        "type":"image",
        "url":"word-1.png"
    },
    {
        "name":"xiaocao_png",
        "type":"image",
        "url":"xiaocao.png"
    },
    {
        "name":"across_png",
        "type":"image",
        "url":"across.png"
    },
    {
        "name":"baozi_png",
        "type":"image",
        "url":"baozi.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"che_png",
        "type":"image",
        "url":"che.png"
    },
    {
        "name":"chezi_png",
        "type":"image",
        "url":"chezi.png"
    },
    {
        "name":"dadi_png",
        "type":"image",
        "url":"dadi.png"
    },
    {
        "name":"jieshao_png",
        "type":"image",
        "url":"jieshao.png"
    },
    {
        "name":"kuai_png",
        "type":"image",
        "url":"kuai.png"
    },
    {
        "name":"longmogu_png",
        "type":"image",
        "url":"longmogu.png"
    },
    {
        "name":"long-mogu_png",
        "type":"image",
        "url":"long-mogu.png"
    },
    {
        "name":"pic_png",
        "type":"image",
        "url":"pic.png"
    }
];