var resData = [
    {
        "name":"bg-1_png",
        "type":"image",
        "url":"bg-1.png"
    },
    {
        "name":"bg-2_png",
        "type":"image",
        "url":"bg-2.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"img-1_jpg",
        "type":"image",
        "url":"img-1.jpg"
    },
    {
        "name":"img-2_jpg",
        "type":"image",
        "url":"img-2.jpg"
    },
    {
        "name":"img-3_jpg",
        "type":"image",
        "url":"img-3.jpg"
    },
    {
        "name":"img-4_jpg",
        "type":"image",
        "url":"img-4.jpg"
    },
    {
        "name":"img-5_jpg",
        "type":"image",
        "url":"img-5.jpg"
    },
    {
        "name":"img-6_jpg",
        "type":"image",
        "url":"img-6.jpg"
    },
    {
        "name":"img-7_jpg",
        "type":"image",
        "url":"img-7.jpg"
    },
    {
        "name":"img-8_jpg",
        "type":"image",
        "url":"img-8.jpg"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"quan-1_png",
        "type":"image",
        "url":"quan-1.png"
    },
    {
        "name":"quan-2_png",
        "type":"image",
        "url":"quan-2.png"
    },
    {
        "name":"quan-3_png",
        "type":"image",
        "url":"quan-3.png"
    },
    {
        "name":"quan-4_png",
        "type":"image",
        "url":"quan-4.png"
    },
    {
        "name":"ad-1_png",
        "type":"image",
        "url":"ad-1.png"
    },
    {
        "name":"ad-2_png",
        "type":"image",
        "url":"ad-2.png"
    },
    {
        "name":"baoyou_png",
        "type":"image",
        "url":"baoyou.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    }
];