var resData = [
    {
        "name":"lihe-title-2_png",
        "type":"image",
        "url":"lihe-title-2.png"
    },
    {
        "name":"words-1_png",
        "type":"image",
        "url":"words-1.png"
    },
    {
        "name":"words-2_png",
        "type":"image",
        "url":"words-2.png"
    },
    {
        "name":"words-3_png",
        "type":"image",
        "url":"words-3.png"
    },
    {
        "name":"words-4_png",
        "type":"image",
        "url":"words-4.png"
    },
    {
        "name":"words-5_png",
        "type":"image",
        "url":"words-5.png"
    },
    {
        "name":"words-6_png",
        "type":"image",
        "url":"words-6.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-pic-1_png",
        "type":"image",
        "url":"cake-pic-1.png"
    },
    {
        "name":"cake-pic-2_png",
        "type":"image",
        "url":"cake-pic-2.png"
    },
    {
        "name":"cake-pic-3_png",
        "type":"image",
        "url":"cake-pic-3.png"
    },
    {
        "name":"cake-pic-4_png",
        "type":"image",
        "url":"cake-pic-4.png"
    },
    {
        "name":"cake-pic-5_png",
        "type":"image",
        "url":"cake-pic-5.png"
    },
    {
        "name":"cake-pic-6_png",
        "type":"image",
        "url":"cake-pic-6.png"
    },
    {
        "name":"lihe-1_png",
        "type":"image",
        "url":"lihe-1.png"
    },
    {
        "name":"lihe-2_png",
        "type":"image",
        "url":"lihe-2.png"
    },
    {
        "name":"lihe-title-1_png",
        "type":"image",
        "url":"lihe-title-1.png"
    }
];