var resData = [
    {
        "name":"pri-2_png",
        "type":"image",
        "url":"pri-2.png"
    },
    {
        "name":"s1-cake_png",
        "type":"image",
        "url":"s1-cake.png"
    },
    {
        "name":"s1-cloud1_png",
        "type":"image",
        "url":"s1-cloud1.png"
    },
    {
        "name":"s1-cloud2_png",
        "type":"image",
        "url":"s1-cloud2.png"
    },
    {
        "name":"s1-w_png",
        "type":"image",
        "url":"s1-w.png"
    },
    {
        "name":"s1-w2_png",
        "type":"image",
        "url":"s1-w2.png"
    },
    {
        "name":"s1-xiong_png",
        "type":"image",
        "url":"s1-xiong.png"
    },
    {
        "name":"s2-cake_png",
        "type":"image",
        "url":"s2-cake.png"
    },
    {
        "name":"s2-line_png",
        "type":"image",
        "url":"s2-line.png"
    },
    {
        "name":"s2-ny_png",
        "type":"image",
        "url":"s2-ny.png"
    },
    {
        "name":"s2-w_png",
        "type":"image",
        "url":"s2-w.png"
    },
    {
        "name":"s2-w2_png",
        "type":"image",
        "url":"s2-w2.png"
    },
    {
        "name":"s2-xiong_png",
        "type":"image",
        "url":"s2-xiong.png"
    },
    {
        "name":"s3-cake_png",
        "type":"image",
        "url":"s3-cake.png"
    },
    {
        "name":"s3-title_png",
        "type":"image",
        "url":"s3-title.png"
    },
    {
        "name":"s3-xiong_png",
        "type":"image",
        "url":"s3-xiong.png"
    },
    {
        "name":"banner-cake_png",
        "type":"image",
        "url":"banner-cake.png"
    },
    {
        "name":"banner-shu_png",
        "type":"image",
        "url":"banner-shu.png"
    },
    {
        "name":"banner-title_png",
        "type":"image",
        "url":"banner-title.png"
    },
    {
        "name":"banner-xiong_png",
        "type":"image",
        "url":"banner-xiong.png"
    },
    {
        "name":"btn-bg_png",
        "type":"image",
        "url":"btn-bg.png"
    },
    {
        "name":"gou-1_png",
        "type":"image",
        "url":"gou-1.png"
    },
    {
        "name":"gou-2_png",
        "type":"image",
        "url":"gou-2.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"pri-1_png",
        "type":"image",
        "url":"pri-1.png"
    }
];