var resData = [
    {
        "name":"img-1_03_jpg",
        "type":"image",
        "url":"img-1_03.jpg"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"shengyu_png",
        "type":"image",
        "url":"shengyu.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"women_png",
        "type":"image",
        "url":"women.png"
    },
    {
        "name":"zengpin_png",
        "type":"image",
        "url":"zengpin.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-bg_png",
        "type":"image",
        "url":"cake-bg.png"
    }
];