var resData = [
    {
        "name":"main-3-bg_png",
        "type":"image",
        "url":"main-3-bg.png"
    },
    {
        "name":"text_png",
        "type":"image",
        "url":"text.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"card-1_png",
        "type":"image",
        "url":"card-1.png"
    },
    {
        "name":"card-2_png",
        "type":"image",
        "url":"card-2.png"
    },
    {
        "name":"card-3_png",
        "type":"image",
        "url":"card-3.png"
    },
    {
        "name":"card-4_png",
        "type":"image",
        "url":"card-4.png"
    },
    {
        "name":"foot-bg_png",
        "type":"image",
        "url":"foot-bg.png"
    },
    {
        "name":"main-1-bg_png",
        "type":"image",
        "url":"main-1-bg.png"
    },
    {
        "name":"main-2-bg_png",
        "type":"image",
        "url":"main-2-bg.png"
    }
];