var resData = [
    {
        "name":"time-1_png",
        "type":"image",
        "url":"time-1.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"btn-buy_png",
        "type":"image",
        "url":"btn-buy.png"
    },
    {
        "name":"btn-cart_png",
        "type":"image",
        "url":"btn-cart.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"cake-7_png",
        "type":"image",
        "url":"cake-7.png"
    },
    {
        "name":"cake-8_png",
        "type":"image",
        "url":"cake-8.png"
    },
    {
        "name":"car_png",
        "type":"image",
        "url":"car.png"
    },
    {
        "name":"car-on_png",
        "type":"image",
        "url":"car-on.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"dot_png",
        "type":"image",
        "url":"dot.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"lipin-1_png",
        "type":"image",
        "url":"lipin-1.png"
    }
];