var loadingData = [
        {
            "name":"loading-bg_jpg",
            "type":"image",
            "url":"loading-bg.jpg"
        },
        {
            "name":"loading-slide_png",
            "type":"image",
            "url":"loading-slide.png"
        },
        {
            "name":"loading-title_png",
            "type":"image",
            "url":"loading-title.png"
        },
        {
            "name":"floater_png",
            "type":"image",
            "url":"floater.png"
        }
    ],
    preloadData = [
        {
            "name":"btn-glitch_png",
            "type":"image",
            "url":"btn-glitch.png"
        },
        {
            "name":"btn-text_png",
            "type":"image",
            "url":"btn-text.png"
        },
        {
            "name":"cake-bg2_jpg",
            "type":"image",
            "url":"cake-bg2.jpg"
        },
        {
            "name":"cake-btn-disable_png",
            "type":"image",
            "url":"cake-btn-disable.png"
        },
        {
            "name":"cake-btn_png",
            "type":"image",
            "url":"cake-btn.png"
        },
        {
            "name":"cake-text_png",
            "type":"image",
            "url":"cake-text.png"
        },
        {
            "name":"care-bg_jpg",
            "type":"image",
            "url":"care-bg.jpg"
        },
        {
            "name":"care-btn-glitch_png",
            "type":"image",
            "url":"care-btn-glitch.png"
        },
        {
            "name":"care-btn_png",
            "type":"image",
            "url":"care-btn.png"
        },
        {
            "name":"care-lighting-left_png",
            "type":"image",
            "url":"care-lighting-left.png"
        },
        {
            "name":"care-lighting-right_png",
            "type":"image",
            "url":"care-lighting-right.png"
        },
        {
            "name":"care-pump_png",
            "type":"image",
            "url":"care-pump.png"
        },
        {
            "name":"ccd_png",
            "type":"image",
            "url":"ccd.png"
        },
        {
            "name":"glitch-care_png",
            "type":"image",
            "url":"glitch-care.png"
        },
        {
            "name":"glitch_png",
            "type":"image",
            "url":"glitch.png"
        }
    ];