var resData = [
    {
        "name":"lipin-2_png",
        "type":"image",
        "url":"lipin-2.png"
    },
    {
        "name":"txt-1_png",
        "type":"image",
        "url":"txt-1.png"
    },
    {
        "name":"txt-2_png",
        "type":"image",
        "url":"txt-2.png"
    },
    {
        "name":"xiaoshi_png",
        "type":"image",
        "url":"xiaoshi.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"buy_btn1_png",
        "type":"image",
        "url":"buy_btn1.png"
    },
    {
        "name":"buy_btn2_png",
        "type":"image",
        "url":"buy_btn2.png"
    },
    {
        "name":"buy_btn3_png",
        "type":"image",
        "url":"buy_btn3.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"float_png",
        "type":"image",
        "url":"float.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"lipin-1_png",
        "type":"image",
        "url":"lipin-1.png"
    }
];