var resData = [
    {
        "name":"message-btn_png",
        "type":"image",
        "url":"message-btn.png"
    },
    {
        "name":"sec-1_jpg",
        "type":"image",
        "url":"sec-1.jpg"
    },
    {
        "name":"sec-2_jpg",
        "type":"image",
        "url":"sec-2.jpg"
    },
    {
        "name":"sec-3_jpg",
        "type":"image",
        "url":"sec-3.jpg"
    },
    {
        "name":"sec-4_jpg",
        "type":"image",
        "url":"sec-4.jpg"
    },
    {
        "name":"sec-foot_jpg",
        "type":"image",
        "url":"sec-foot.jpg"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"buy-btn_png",
        "type":"image",
        "url":"buy-btn.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-new_png",
        "type":"image",
        "url":"cake-new.png"
    },
    {
        "name":"group-1_png",
        "type":"image",
        "url":"group-1.png"
    },
    {
        "name":"group-2_png",
        "type":"image",
        "url":"group-2.png"
    },
    {
        "name":"message-bg_png",
        "type":"image",
        "url":"message-bg.png"
    }
];