var resData = [
    {
        "name":"ricotta_png",
        "type":"image",
        "url":"ricotta.png"
    },
    {
        "name":"shengbang_png",
        "type":"image",
        "url":"shengbang.png"
    },
    {
        "name":"shuidi_png",
        "type":"image",
        "url":"shuidi.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"topbar_png",
        "type":"image",
        "url":"topbar.png"
    },
    {
        "name":"words-1_png",
        "type":"image",
        "url":"words-1.png"
    },
    {
        "name":"words-2_png",
        "type":"image",
        "url":"words-2.png"
    },
    {
        "name":"buybtn_png",
        "type":"image",
        "url":"buybtn.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-ricotta_png",
        "type":"image",
        "url":"cake-ricotta.png"
    },
    {
        "name":"cloud-1_png",
        "type":"image",
        "url":"cloud-1.png"
    },
    {
        "name":"game_png",
        "type":"image",
        "url":"game.png"
    },
    {
        "name":"hetao_png",
        "type":"image",
        "url":"hetao.png"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    },
    {
        "name":"line-cloud_png",
        "type":"image",
        "url":"line-cloud.png"
    }
];