var resData = [
    {
        "name":"reduce-4_png",
        "type":"image",
        "url":"reduce-4.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"weixin_png",
        "type":"image",
        "url":"weixin.png"
    },
    {
        "name":"add-1_png",
        "type":"image",
        "url":"add-1.png"
    },
    {
        "name":"add-2_png",
        "type":"image",
        "url":"add-2.png"
    },
    {
        "name":"add-3_png",
        "type":"image",
        "url":"add-3.png"
    },
    {
        "name":"add-4_png",
        "type":"image",
        "url":"add-4.png"
    },
    {
        "name":"banner-wap_png",
        "type":"image",
        "url":"banner-wap.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"btn-3_png",
        "type":"image",
        "url":"btn-3.png"
    },
    {
        "name":"btn-4_png",
        "type":"image",
        "url":"btn-4.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"dis-1_png",
        "type":"image",
        "url":"dis-1.png"
    },
    {
        "name":"dis-2_png",
        "type":"image",
        "url":"dis-2.png"
    },
    {
        "name":"dis-3_png",
        "type":"image",
        "url":"dis-3.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"icon-1_png",
        "type":"image",
        "url":"icon-1.png"
    },
    {
        "name":"icon-1-h_png",
        "type":"image",
        "url":"icon-1-h.png"
    },
    {
        "name":"icon-2_png",
        "type":"image",
        "url":"icon-2.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"reduce-1_png",
        "type":"image",
        "url":"reduce-1.png"
    },
    {
        "name":"reduce-2_png",
        "type":"image",
        "url":"reduce-2.png"
    },
    {
        "name":"reduce-3_png",
        "type":"image",
        "url":"reduce-3.png"
    }
];