var loadingData = [
        {
            "name":"loading-bg_jpg",
            "type":"image",
            "url":"loading-bg.jpg"
        },
        {
            "name":"loading-title_png",
            "type":"image",
            "url":"loading-title.png"
        },
        {
            "name":"loading-slide_png",
            "type":"image",
            "url":"loading-slide.png"
        }],
    preloadData = [
        {
            "name":"darkCake_png",
            "type":"image",
            "url":"darkCake.png"
        },
        {
            "name":"lighting-right_png",
            "type":"image",
            "url":"lighting-right.png"
        },
        {
            "name":"box_png",
            "type":"image",
            "url":"box.png"
        },
        {
            "name":"boxbg_jpg",
            "type":"image",
            "url":"boxbg.jpg"
        },
        {
            "name":"boxBuyBtn-disable_png",
            "type":"image",
            "url":"boxBuyBtn-disable.png"
        },
        {
            "name":"boxBuyBtn_png",
            "type":"image",
            "url":"boxBuyBtn.png"
        },
        {
            "name":"boxbuytext_png",
            "type":"image",
            "url":"boxbuytext.png"
        },
        {
            "name":"boxText_png",
            "type":"image",
            "url":"boxText.png"
        },
        {
            "name":"buyBtn-disable_png",
            "type":"image",
            "url":"buyBtn-disable.png"
        },
        {
            "name":"buyBtn_png",
            "type":"image",
            "url":"buyBtn.png"
        },
        {
            "name":"buyText_png",
            "type":"image",
            "url":"buyText.png"
        },
        {
            "name":"carebtn_png",
            "type":"image",
            "url":"carebtn.png"
        },
        {
            "name":"carebtntext_png",
            "type":"image",
            "url":"carebtntext.png"
        },
        {
            "name":"darkPumpkin_png",
            "type":"image",
            "url":"darkPumpkin.png"
        },
        {
            "name":"glitch_png",
            "type":"image",
            "url":"glitch.png"
        },
        {
            "name":"glitchCake_png",
            "type":"image",
            "url":"glitchCake.png"
        },
        {
            "name":"lightCakebg_jpg",
            "type":"image",
            "url":"lightCakebg.jpg"
        },
        {
            "name":"lighting-left_png",
            "type":"image",
            "url":"lighting-left.png"
        },
        {
            "name":"lightPumpkin_png",
            "type":"image",
            "url":"lightPumpkin.png"
        },
        {
            "name":"heart1_png",
            "type":"image",
            "url":"heart1.png"
        },
        {
            "name":"heart2_png",
            "type":"image",
            "url":"heart2.png"
        },
        {
            "name":"heart3_png",
            "type":"image",
            "url":"heart3.png"
        },
        {
            "name":"heart4_png",
            "type":"image",
            "url":"heart4.png"
        },
        {
            "name":"heart5_png",
            "type":"image",
            "url":"heart5.png"
        },
        {
            "name":"heart6_png",
            "type":"image",
            "url":"heart6.png"
        },
        {
            "name":"heart7_png",
            "type":"image",
            "url":"heart7.png"
        },
        {
            "name":"heart8_png",
            "type":"image",
            "url":"heart8.png"
        },
        {
            "name":"eye1_png",
            "type":"image",
            "url":"eye1.png"
        },
        {
            "name":"eye2_png",
            "type":"image",
            "url":"eye2.png"
        },
        {
            "name":"eye3_png",
            "type":"image",
            "url":"eye3.png"
        },
        {
            "name":"eye4_png",
            "type":"image",
            "url":"eye4.png"
        },
        {
            "name":"eye5_png",
            "type":"image",
            "url":"eye5.png"
        },
        {
            "name":"eye6_png",
            "type":"image",
            "url":"eye6.png"
        },
        {
            "name":"eye8_png",
            "type":"image",
            "url":"eye8.png"
        },
        {
            "name":"ghost1_png",
            "type":"image",
            "url":"ghost1.png"
        },
        {
            "name":"ghost2_png",
            "type":"image",
            "url":"ghost2.png"
        },
        {
            "name":"ghost3_png",
            "type":"image",
            "url":"ghost3.png"
        },
        {
            "name":"ghost4_png",
            "type":"image",
            "url":"ghost4.png"
        },
        {
            "name":"ghost5_png",
            "type":"image",
            "url":"ghost5.png"
        },
        {
            "name":"ghost6_png",
            "type":"image",
            "url":"ghost6.png"
        },
        {
            "name":"ghost7_png",
            "type":"image",
            "url":"ghost7.png"
        },
        {
            "name":"ghost8_png",
            "type":"image",
            "url":"ghost8.png"
        },
        {
            "name":"pumpkin1_png",
            "type":"image",
            "url":"pumpkin1.png"
        },
        {
            "name":"pumpkin2_png",
            "type":"image",
            "url":"pumpkin2.png"
        },
        {
            "name":"pumpkin3_png",
            "type":"image",
            "url":"pumpkin3.png"
        },
        {
            "name":"pumpkin4_png",
            "type":"image",
            "url":"pumpkin4.png"
        },
        {
            "name":"pumpkin5_png",
            "type":"image",
            "url":"pumpkin5.png"
        },
        {
            "name":"pumpkin6_png",
            "type":"image",
            "url":"pumpkin6.png"
        },
        {
            "name":"pumpkin7_png",
            "type":"image",
            "url":"pumpkin7.png"
        },
        {
            "name":"pumpkin8_png",
            "type":"image",
            "url":"pumpkin8.png"
        },
        {
            "name":"eye7_png",
            "type":"image",
            "url":"eye7.png"
        },
        {
            "name":"btn-glitch_png",
            "type":"image",
            "url":"btn-glitch.png"
        },
        {
            "name":"glitchedbtn_png",
            "type":"image",
            "url":"glitchedbtn.png"
        }];