var resData = [
    {
        "name":"game-bg3_png",
        "type":"image",
        "url":"game-bg3.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"banner-cake_png",
        "type":"image",
        "url":"banner-cake.png"
    },
    {
        "name":"banner-zp_png",
        "type":"image",
        "url":"banner-zp.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"game-bg1_png",
        "type":"image",
        "url":"game-bg1.png"
    },
    {
        "name":"game-bg2_png",
        "type":"image",
        "url":"game-bg2.png"
    }
];