var resData = [
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"zeng-book_png",
        "type":"image",
        "url":"zeng-book.png"
    },
    {
        "name":"zengpin_png",
        "type":"image",
        "url":"zengpin.png"
    },
    {
        "name":"add-2_png",
        "type":"image",
        "url":"add-2.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-0-word_png",
        "type":"image",
        "url":"cake-0-word.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-img-0_png",
        "type":"image",
        "url":"cake-img-0.png"
    },
    {
        "name":"cake-img-1_png",
        "type":"image",
        "url":"cake-img-1.png"
    },
    {
        "name":"cake-img-2_png",
        "type":"image",
        "url":"cake-img-2.png"
    },
    {
        "name":"chuizi_png",
        "type":"image",
        "url":"chuizi.png"
    },
    {
        "name":"dadan_png",
        "type":"image",
        "url":"dadan.png"
    },
    {
        "name":"dis-2_png",
        "type":"image",
        "url":"dis-2.png"
    },
    {
        "name":"dis-3_png",
        "type":"image",
        "url":"dis-3.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"reduce-2_png",
        "type":"image",
        "url":"reduce-2.png"
    },
    {
        "name":"s-title-1_png",
        "type":"image",
        "url":"s-title-1.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    }
];