var resData = [
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"buybtn_png",
        "type":"image",
        "url":"buybtn.png"
    },
    {
        "name":"cake1_png",
        "type":"image",
        "url":"cake1.png"
    },
    {
        "name":"cake2_png",
        "type":"image",
        "url":"cake2.png"
    },
    {
        "name":"cake3_png",
        "type":"image",
        "url":"cake3.png"
    },
    {
        "name":"coffee_png",
        "type":"image",
        "url":"coffee.png"
    },
    {
        "name":"fen_png",
        "type":"image",
        "url":"fen.png"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"minus_png",
        "type":"image",
        "url":"minus.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"plus_png",
        "type":"image",
        "url":"plus.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"top_png",
        "type":"image",
        "url":"top.png"
    },
    {
        "name":"topsnow_png",
        "type":"image",
        "url":"topsnow.png"
    }
];