var resData = [
    {
        "name":"zuhe-3_png",
        "type":"image",
        "url":"zuhe-3.png"
    },
    {
        "name":"zuhe-3-bg_png",
        "type":"image",
        "url":"zuhe-3-bg.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"foot-bg_png",
        "type":"image",
        "url":"foot-bg.png"
    },
    {
        "name":"row1-bg_png",
        "type":"image",
        "url":"row1-bg.png"
    },
    {
        "name":"row1-cake_png",
        "type":"image",
        "url":"row1-cake.png"
    },
    {
        "name":"row2-bg_png",
        "type":"image",
        "url":"row2-bg.png"
    },
    {
        "name":"row2-cake_png",
        "type":"image",
        "url":"row2-cake.png"
    },
    {
        "name":"row3-bg_png",
        "type":"image",
        "url":"row3-bg.png"
    },
    {
        "name":"row3-cake_png",
        "type":"image",
        "url":"row3-cake.png"
    },
    {
        "name":"wap-zp-award-1_png",
        "type":"image",
        "url":"wap-zp-award-1.png"
    },
    {
        "name":"wap-zp-award-2_png",
        "type":"image",
        "url":"wap-zp-award-2.png"
    },
    {
        "name":"wap-zp-award-3_png",
        "type":"image",
        "url":"wap-zp-award-3.png"
    },
    {
        "name":"wap-zpbg_png",
        "type":"image",
        "url":"wap-zpbg.png"
    },
    {
        "name":"zhuanpan-bg_png",
        "type":"image",
        "url":"zhuanpan-bg.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"zp-bg_png",
        "type":"image",
        "url":"zp-bg.png"
    },
    {
        "name":"zp-btn_png",
        "type":"image",
        "url":"zp-btn.png"
    },
    {
        "name":"zp-pan_png",
        "type":"image",
        "url":"zp-pan.png"
    },
    {
        "name":"zuhe-1_png",
        "type":"image",
        "url":"zuhe-1.png"
    },
    {
        "name":"zuhe-1-bg_png",
        "type":"image",
        "url":"zuhe-1-bg.png"
    },
    {
        "name":"zuhe-2_png",
        "type":"image",
        "url":"zuhe-2.png"
    },
    {
        "name":"zuhe-2-bg_png",
        "type":"image",
        "url":"zuhe-2-bg.png"
    }
];