var resData = [
    {
        "name":"quanyi_png",
        "type":"image",
        "url":"quanyi.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    }
];