var resData = [
    {
        "name":"t-6_png",
        "type":"image",
        "url":"t-6.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"xst-1_png",
        "type":"image",
        "url":"xst-1.png"
    },
    {
        "name":"xst-2_png",
        "type":"image",
        "url":"xst-2.png"
    },
    {
        "name":"xst-3_png",
        "type":"image",
        "url":"xst-3.png"
    },
    {
        "name":"xst-4_png",
        "type":"image",
        "url":"xst-4.png"
    },
    {
        "name":"xst-5_png",
        "type":"image",
        "url":"xst-5.png"
    },
    {
        "name":"xst-6_png",
        "type":"image",
        "url":"xst-6.png"
    },
    {
        "name":"xst-7_png",
        "type":"image",
        "url":"xst-7.png"
    },
    {
        "name":"xst-8_png",
        "type":"image",
        "url":"xst-8.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"banner-title_png",
        "type":"image",
        "url":"banner-title.png"
    },
    {
        "name":"bj-banner_jpg",
        "type":"image",
        "url":"bj-banner.jpg"
    },
    {
        "name":"bj-cake-6_png",
        "type":"image",
        "url":"bj-cake-6.png"
    },
    {
        "name":"bj-quanyi_png",
        "type":"image",
        "url":"bj-quanyi.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"disc-1_png",
        "type":"image",
        "url":"disc-1.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"main-bg_png",
        "type":"image",
        "url":"main-bg.png"
    },
    {
        "name":"quanyi_png",
        "type":"image",
        "url":"quanyi.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"t-5_png",
        "type":"image",
        "url":"t-5.png"
    }
];