var resData = [
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"btn-buy_png",
        "type":"image",
        "url":"btn-buy.png"
    },
    {
        "name":"btn-cart_png",
        "type":"image",
        "url":"btn-cart.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-s-1_png",
        "type":"image",
        "url":"cake-s-1.png"
    },
    {
        "name":"cake-s-2_png",
        "type":"image",
        "url":"cake-s-2.png"
    },
    {
        "name":"cake-s-3_png",
        "type":"image",
        "url":"cake-s-3.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"hd-title-1_png",
        "type":"image",
        "url":"hd-title-1.png"
    },
    {
        "name":"hd-title-2_png",
        "type":"image",
        "url":"hd-title-2.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"in-1_png",
        "type":"image",
        "url":"in-1.png"
    },
    {
        "name":"in-2_png",
        "type":"image",
        "url":"in-2.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"ok_png",
        "type":"image",
        "url":"ok.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    }
];