var resData = [
    {
        "name":"share_jpg",
        "type":"image",
        "url":"share.jpg"
    },
    {
        "name":"share-txt_png",
        "type":"image",
        "url":"share-txt.png"
    },
    {
        "name":"txt-shengdan_png",
        "type":"image",
        "url":"txt-shengdan.png"
    },
    {
        "name":"txt-yy_png",
        "type":"image",
        "url":"txt-yy.png"
    },
    {
        "name":"xue-wu_png",
        "type":"image",
        "url":"xue-wu.png"
    },
    {
        "name":"btn-go_png",
        "type":"image",
        "url":"btn-go.png"
    },
    {
        "name":"btn-go-hl_png",
        "type":"image",
        "url":"btn-go-hl.png"
    },
    {
        "name":"btn-share_png",
        "type":"image",
        "url":"btn-share.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"card-bottom_png",
        "type":"image",
        "url":"card-bottom.png"
    },
    {
        "name":"card-middle_png",
        "type":"image",
        "url":"card-middle.png"
    },
    {
        "name":"card-top_png",
        "type":"image",
        "url":"card-top.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"cover_png",
        "type":"image",
        "url":"cover.png"
    },
    {
        "name":"iphone_png",
        "type":"image",
        "url":"iphone.png"
    },
    {
        "name":"land_tip_png",
        "type":"image",
        "url":"land_tip.png"
    },
    {
        "name":"page-1_jpg",
        "type":"image",
        "url":"page-1.jpg"
    },
    {
        "name":"page-2_jpg",
        "type":"image",
        "url":"page-2.jpg"
    },
    {
        "name":"point_png",
        "type":"image",
        "url":"point.png"
    }
];