var resData = [
    {
        "name":"price-4_png",
        "type":"image",
        "url":"price-4.png"
    },
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-2_png",
        "type":"image",
        "url":"sec-2.png"
    },
    {
        "name":"sec-3_png",
        "type":"image",
        "url":"sec-3.png"
    },
    {
        "name":"sec-4_png",
        "type":"image",
        "url":"sec-4.png"
    },
    {
        "name":"sec-5_png",
        "type":"image",
        "url":"sec-5.png"
    },
    {
        "name":"sec-foot_png",
        "type":"image",
        "url":"sec-foot.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"txt_png",
        "type":"image",
        "url":"txt.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"card_png",
        "type":"image",
        "url":"card.png"
    },
    {
        "name":"price-1_png",
        "type":"image",
        "url":"price-1.png"
    },
    {
        "name":"price-2_png",
        "type":"image",
        "url":"price-2.png"
    },
    {
        "name":"price-3_png",
        "type":"image",
        "url":"price-3.png"
    }
];