var resData = [
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-t-1_png",
        "type":"image",
        "url":"cake-t-1.png"
    },
    {
        "name":"cake-t-2_png",
        "type":"image",
        "url":"cake-t-2.png"
    },
    {
        "name":"cake-t-3_png",
        "type":"image",
        "url":"cake-t-3.png"
    },
    {
        "name":"icon_10_png",
        "type":"image",
        "url":"icon_10.png"
    },
    {
        "name":"icon_20_png",
        "type":"image",
        "url":"icon_20.png"
    },
    {
        "name":"machine-award_png",
        "type":"image",
        "url":"machine-award.png"
    },
    {
        "name":"machine-bg_png",
        "type":"image",
        "url":"machine-bg.png"
    },
    {
        "name":"machine-btn-left_png",
        "type":"image",
        "url":"machine-btn-left.png"
    },
    {
        "name":"machine-btn-right_png",
        "type":"image",
        "url":"machine-btn-right.png"
    },
    {
        "name":"machine-btn-start_png",
        "type":"image",
        "url":"machine-btn-start.png"
    },
    {
        "name":"machine-claw_png",
        "type":"image",
        "url":"machine-claw.png"
    },
    {
        "name":"machine-head_png",
        "type":"image",
        "url":"machine-head.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    }
];