var resData = [
    {
        "name":"code_png",
        "type":"image",
        "url":"code.png"
    },
    {
        "name":"code1_png",
        "type":"image",
        "url":"code1.png"
    },
    {
        "name":"code2_png",
        "type":"image",
        "url":"code2.png"
    },
    {
        "name":"ewm_png",
        "type":"image",
        "url":"ewm.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"plus_png",
        "type":"image",
        "url":"plus.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"shengyu_png",
        "type":"image",
        "url":"shengyu.png"
    },
    {
        "name":"shouqing_png",
        "type":"image",
        "url":"shouqing.png"
    },
    {
        "name":"step1_png",
        "type":"image",
        "url":"step1.png"
    },
    {
        "name":"step2_png",
        "type":"image",
        "url":"step2.png"
    },
    {
        "name":"time_png",
        "type":"image",
        "url":"time.png"
    },
    {
        "name":"t-style_png",
        "type":"image",
        "url":"t-style.png"
    },
    {
        "name":"act_text_png",
        "type":"image",
        "url":"act_text.png"
    },
    {
        "name":"banner-1_jpg",
        "type":"image",
        "url":"banner-1.jpg"
    },
    {
        "name":"banner-2_jpg",
        "type":"image",
        "url":"banner-2.jpg"
    },
    {
        "name":"btn-add_png",
        "type":"image",
        "url":"btn-add.png"
    },
    {
        "name":"btn-minus_png",
        "type":"image",
        "url":"btn-minus.png"
    },
    {
        "name":"buybtn_png",
        "type":"image",
        "url":"buybtn.png"
    }
];