var resData = [
    {
        "name":"bot_png",
        "type":"image",
        "url":"bot.png"
    },
    {
        "name":"test_png",
        "type":"image",
        "url":"test.png"
    },
    {
        "name":"top01_png",
        "type":"image",
        "url":"top01.png"
    },
    {
        "name":"top02_png",
        "type":"image",
        "url":"top02.png"
    },
    {
        "name":"top03_png",
        "type":"image",
        "url":"top03.png"
    },
    {
        "name":"top04_png",
        "type":"image",
        "url":"top04.png"
    },
    {
        "name":"top05_png",
        "type":"image",
        "url":"top05.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"bg1_jpg",
        "type":"image",
        "url":"bg1.jpg"
    },
    {
        "name":"bg2_jpg",
        "type":"image",
        "url":"bg2.jpg"
    }
];