var resData = [
    {
        "name":"word4_png",
        "type":"image",
        "url":"word4.png"
    },
    {
        "name":"word5_png",
        "type":"image",
        "url":"word5.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"bg1_png",
        "type":"image",
        "url":"bg1.png"
    },
    {
        "name":"bg2_png",
        "type":"image",
        "url":"bg2.png"
    },
    {
        "name":"bg3_png",
        "type":"image",
        "url":"bg3.png"
    },
    {
        "name":"bg4_png",
        "type":"image",
        "url":"bg4.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake1_png",
        "type":"image",
        "url":"cake1.png"
    },
    {
        "name":"cake2_png",
        "type":"image",
        "url":"cake2.png"
    },
    {
        "name":"cake3_png",
        "type":"image",
        "url":"cake3.png"
    },
    {
        "name":"cake4_png",
        "type":"image",
        "url":"cake4.png"
    },
    {
        "name":"cake5_png",
        "type":"image",
        "url":"cake5.png"
    },
    {
        "name":"caomei_a_png",
        "type":"image",
        "url":"caomei_a.png"
    },
    {
        "name":"caomei_b_png",
        "type":"image",
        "url":"caomei_b.png"
    },
    {
        "name":"caomei_c_png",
        "type":"image",
        "url":"caomei_c.png"
    },
    {
        "name":"freak1_png",
        "type":"image",
        "url":"freak1.png"
    },
    {
        "name":"freak2_png",
        "type":"image",
        "url":"freak2.png"
    },
    {
        "name":"heart_png",
        "type":"image",
        "url":"heart.png"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    },
    {
        "name":"monster_b_png",
        "type":"image",
        "url":"monster_b.png"
    },
    {
        "name":"monster_c_png",
        "type":"image",
        "url":"monster_c.png"
    },
    {
        "name":"monster_d_png",
        "type":"image",
        "url":"monster_d.png"
    },
    {
        "name":"monster_e_png",
        "type":"image",
        "url":"monster_e.png"
    },
    {
        "name":"monster2_png",
        "type":"image",
        "url":"monster2.png"
    },
    {
        "name":"monster3_png",
        "type":"image",
        "url":"monster3.png"
    },
    {
        "name":"monster4_png",
        "type":"image",
        "url":"monster4.png"
    },
    {
        "name":"monster5_png",
        "type":"image",
        "url":"monster5.png"
    },
    {
        "name":"monster6_png",
        "type":"image",
        "url":"monster6.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"word1_png",
        "type":"image",
        "url":"word1.png"
    },
    {
        "name":"word2_png",
        "type":"image",
        "url":"word2.png"
    },
    {
        "name":"word3_png",
        "type":"image",
        "url":"word3.png"
    }
];