var resData = [
    {
        "name":"price-2_png",
        "type":"image",
        "url":"price-2.png"
    },
    {
        "name":"s-title-1_png",
        "type":"image",
        "url":"s-title-1.png"
    },
    {
        "name":"word-1_02_png",
        "type":"image",
        "url":"word-1_02.png"
    },
    {
        "name":"wx_png",
        "type":"image",
        "url":"wx.png"
    },
    {
        "name":"xs-zuhe_png",
        "type":"image",
        "url":"xs-zuhe.png"
    },
    {
        "name":"banner-wap_png",
        "type":"image",
        "url":"banner-wap.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"dis-1_png",
        "type":"image",
        "url":"dis-1.png"
    },
    {
        "name":"dis-2_png",
        "type":"image",
        "url":"dis-2.png"
    },
    {
        "name":"dis-3_png",
        "type":"image",
        "url":"dis-3.png"
    },
    {
        "name":"liwu_png",
        "type":"image",
        "url":"liwu.png"
    },
    {
        "name":"price-1_png",
        "type":"image",
        "url":"price-1.png"
    }
];