var resData = [
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"tusi_png",
        "type":"image",
        "url":"tusi.png"
    },
    {
        "name":"tusi_bj_png",
        "type":"image",
        "url":"tusi_bj.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"hongbao_png",
        "type":"image",
        "url":"hongbao.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"icon_20_png",
        "type":"image",
        "url":"icon_20.png"
    },
    {
        "name":"icon_40_png",
        "type":"image",
        "url":"icon_40.png"
    },
    {
        "name":"icon_60_png",
        "type":"image",
        "url":"icon_60.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"main_bg_png",
        "type":"image",
        "url":"main_bg.png"
    }
];