var resData = [
    {
        "name":"mcake-3_png",
        "type":"image",
        "url":"mcake-3.png"
    },
    {
        "name":"mcake-4_png",
        "type":"image",
        "url":"mcake-4.png"
    },
    {
        "name":"mun-btn_png",
        "type":"image",
        "url":"mun-btn.png"
    },
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-2_png",
        "type":"image",
        "url":"sec-2.png"
    },
    {
        "name":"sec-3_png",
        "type":"image",
        "url":"sec-3.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"buy-btn_png",
        "type":"image",
        "url":"buy-btn.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"gobuy-btn_png",
        "type":"image",
        "url":"gobuy-btn.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"icon_20_png",
        "type":"image",
        "url":"icon_20.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"in-b-1_png",
        "type":"image",
        "url":"in-b-1.png"
    },
    {
        "name":"in-b-2_png",
        "type":"image",
        "url":"in-b-2.png"
    },
    {
        "name":"in-c-1_png",
        "type":"image",
        "url":"in-c-1.png"
    },
    {
        "name":"in-c-2_png",
        "type":"image",
        "url":"in-c-2.png"
    },
    {
        "name":"in-d-1_png",
        "type":"image",
        "url":"in-d-1.png"
    },
    {
        "name":"in-d-2_png",
        "type":"image",
        "url":"in-d-2.png"
    },
    {
        "name":"in-e-1_png",
        "type":"image",
        "url":"in-e-1.png"
    },
    {
        "name":"in-e-2_png",
        "type":"image",
        "url":"in-e-2.png"
    },
    {
        "name":"mcake-1_png",
        "type":"image",
        "url":"mcake-1.png"
    },
    {
        "name":"mcake-2_png",
        "type":"image",
        "url":"mcake-2.png"
    }
];