var resData = [
    {
        "name":"star_png",
        "type":"image",
        "url":"star.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"xz-1_png",
        "type":"image",
        "url":"xz-1.png"
    },
    {
        "name":"xz-1-back_png",
        "type":"image",
        "url":"xz-1-back.png"
    },
    {
        "name":"xz-2_png",
        "type":"image",
        "url":"xz-2.png"
    },
    {
        "name":"xz-2-04_png",
        "type":"image",
        "url":"xz-2-04.png"
    },
    {
        "name":"xz-2-back_png",
        "type":"image",
        "url":"xz-2-back.png"
    },
    {
        "name":"xz-2-back-04_png",
        "type":"image",
        "url":"xz-2-back-04.png"
    },
    {
        "name":"xz-3_png",
        "type":"image",
        "url":"xz-3.png"
    },
    {
        "name":"xz-3-back_png",
        "type":"image",
        "url":"xz-3-back.png"
    },
    {
        "name":"xz-4_png",
        "type":"image",
        "url":"xz-4.png"
    },
    {
        "name":"xz-4-back_png",
        "type":"image",
        "url":"xz-4-back.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"banner-t_png",
        "type":"image",
        "url":"banner-t.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"banner-wap_png",
        "type":"image",
        "url":"banner-wap.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"card-1_png",
        "type":"image",
        "url":"card-1.png"
    },
    {
        "name":"card-2_png",
        "type":"image",
        "url":"card-2.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"foot-bg_jpg",
        "type":"image",
        "url":"foot-bg.jpg"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"in-1_png",
        "type":"image",
        "url":"in-1.png"
    },
    {
        "name":"in-2_png",
        "type":"image",
        "url":"in-2.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"in-b-1_png",
        "type":"image",
        "url":"in-b-1.png"
    },
    {
        "name":"in-b-2_png",
        "type":"image",
        "url":"in-b-2.png"
    },
    {
        "name":"in-c-1_png",
        "type":"image",
        "url":"in-c-1.png"
    },
    {
        "name":"in-c-2_png",
        "type":"image",
        "url":"in-c-2.png"
    },
    {
        "name":"in-d-1_png",
        "type":"image",
        "url":"in-d-1.png"
    },
    {
        "name":"in-d-2_png",
        "type":"image",
        "url":"in-d-2.png"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"price_png",
        "type":"image",
        "url":"price.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    }
];