var resData = [
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"in-1_png",
        "type":"image",
        "url":"in-1.png"
    },
    {
        "name":"in-2_png",
        "type":"image",
        "url":"in-2.png"
    },
    {
        "name":"jiang-bg_png",
        "type":"image",
        "url":"jiang-bg.png"
    },
    {
        "name":"WAP_06_png",
        "type":"image",
        "url":"WAP_06.png"
    },
    {
        "name":"xiaoshibao_png",
        "type":"image",
        "url":"xiaoshibao.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"btn-jf-1_png",
        "type":"image",
        "url":"btn-jf-1.png"
    },
    {
        "name":"btn-jf-2_png",
        "type":"image",
        "url":"btn-jf-2.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"hua-1_png",
        "type":"image",
        "url":"hua-1.png"
    },
    {
        "name":"hua-2_png",
        "type":"image",
        "url":"hua-2.png"
    }
];