var resData = [
    {
        "name":"xiaoshi-1_png",
        "type":"image",
        "url":"xiaoshi-1.png"
    },
    {
        "name":"xiaoshi-2_png",
        "type":"image",
        "url":"xiaoshi-2.png"
    },
    {
        "name":"xiaoshi-3_png",
        "type":"image",
        "url":"xiaoshi-3.png"
    },
    {
        "name":"xiaoshi-4_png",
        "type":"image",
        "url":"xiaoshi-4.png"
    },
    {
        "name":"x-t-1_png",
        "type":"image",
        "url":"x-t-1.png"
    },
    {
        "name":"x-t-2_png",
        "type":"image",
        "url":"x-t-2.png"
    },
    {
        "name":"x-t-3_png",
        "type":"image",
        "url":"x-t-3.png"
    },
    {
        "name":"x-t-4_png",
        "type":"image",
        "url":"x-t-4.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"calendar-1_png",
        "type":"image",
        "url":"calendar-1.png"
    },
    {
        "name":"calendar-2_png",
        "type":"image",
        "url":"calendar-2.png"
    },
    {
        "name":"calendar-3_png",
        "type":"image",
        "url":"calendar-3.png"
    },
    {
        "name":"calendar-4_png",
        "type":"image",
        "url":"calendar-4.png"
    },
    {
        "name":"foot-bg_jpg",
        "type":"image",
        "url":"foot-bg.jpg"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"hy-title-3_png",
        "type":"image",
        "url":"hy-title-3.png"
    },
    {
        "name":"hy-title-4_png",
        "type":"image",
        "url":"hy-title-4.png"
    },
    {
        "name":"m-1_png",
        "type":"image",
        "url":"m-1.png"
    },
    {
        "name":"m-2_png",
        "type":"image",
        "url":"m-2.png"
    },
    {
        "name":"m-3_png",
        "type":"image",
        "url":"m-3.png"
    },
    {
        "name":"m-4_png",
        "type":"image",
        "url":"m-4.png"
    },
    {
        "name":"m-cake-1_png",
        "type":"image",
        "url":"m-cake-1.png"
    },
    {
        "name":"m-cake-2_png",
        "type":"image",
        "url":"m-cake-2.png"
    },
    {
        "name":"m-cake-3_png",
        "type":"image",
        "url":"m-cake-3.png"
    },
    {
        "name":"m-cake-4_png",
        "type":"image",
        "url":"m-cake-4.png"
    },
    {
        "name":"numb-1_png",
        "type":"image",
        "url":"numb-1.png"
    },
    {
        "name":"numb-2_png",
        "type":"image",
        "url":"numb-2.png"
    },
    {
        "name":"numb-3_png",
        "type":"image",
        "url":"numb-3.png"
    },
    {
        "name":"numb-4_png",
        "type":"image",
        "url":"numb-4.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    }
];