var resData = [
    {
        "name":"tag-2_png",
        "type":"image",
        "url":"tag-2.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"dot_png",
        "type":"image",
        "url":"dot.png"
    },
    {
        "name":"gobtn-1_png",
        "type":"image",
        "url":"gobtn-1.png"
    },
    {
        "name":"gobtn-2_png",
        "type":"image",
        "url":"gobtn-2.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"quan-2_png",
        "type":"image",
        "url":"quan-2.png"
    },
    {
        "name":"quan-3_png",
        "type":"image",
        "url":"quan-3.png"
    },
    {
        "name":"s-bg_png",
        "type":"image",
        "url":"s-bg.png"
    },
    {
        "name":"tag-1_png",
        "type":"image",
        "url":"tag-1.png"
    }
];