var resData = [
    {
        "name":"cover_png",
        "type":"image",
        "url":"cover.png"
    },
    {
        "name":"i1_png",
        "type":"image",
        "url":"i1.png"
    },
    {
        "name":"i2_png",
        "type":"image",
        "url":"i2.png"
    },
    {
        "name":"i4_png",
        "type":"image",
        "url":"i4.png"
    },
    {
        "name":"i5_png",
        "type":"image",
        "url":"i5.png"
    },
    {
        "name":"icon_buy_png",
        "type":"image",
        "url":"icon_buy.png"
    },
    {
        "name":"icon_recommend_png",
        "type":"image",
        "url":"icon_recommend.png"
    },
    {
        "name":"p1_arrow_png",
        "type":"image",
        "url":"p1_arrow.png"
    },
    {
        "name":"p1_fork_png",
        "type":"image",
        "url":"p1_fork.png"
    },
    {
        "name":"p1_img_png",
        "type":"image",
        "url":"p1_img.png"
    },
    {
        "name":"p1_name_png",
        "type":"image",
        "url":"p1_name.png"
    },
    {
        "name":"p2_arrow_png",
        "type":"image",
        "url":"p2_arrow.png"
    },
    {
        "name":"p2_fork_png",
        "type":"image",
        "url":"p2_fork.png"
    },
    {
        "name":"p2_img_png",
        "type":"image",
        "url":"p2_img.png"
    },
    {
        "name":"p2_name_png",
        "type":"image",
        "url":"p2_name.png"
    },
    {
        "name":"p2_photo_png",
        "type":"image",
        "url":"p2_photo.png"
    },
    {
        "name":"p3_arrow_png",
        "type":"image",
        "url":"p3_arrow.png"
    },
    {
        "name":"p3_fork_png",
        "type":"image",
        "url":"p3_fork.png"
    },
    {
        "name":"p3_img_png",
        "type":"image",
        "url":"p3_img.png"
    },
    {
        "name":"p3_name_png",
        "type":"image",
        "url":"p3_name.png"
    },
    {
        "name":"p4_arrow_png",
        "type":"image",
        "url":"p4_arrow.png"
    },
    {
        "name":"p4_fork_png",
        "type":"image",
        "url":"p4_fork.png"
    },
    {
        "name":"p4_img_png",
        "type":"image",
        "url":"p4_img.png"
    },
    {
        "name":"p4_name_png",
        "type":"image",
        "url":"p4_name.png"
    },
    {
        "name":"p5_arrow_png",
        "type":"image",
        "url":"p5_arrow.png"
    },
    {
        "name":"p5_fork_png",
        "type":"image",
        "url":"p5_fork.png"
    },
    {
        "name":"p5_img_png",
        "type":"image",
        "url":"p5_img.png"
    },
    {
        "name":"p5_name_png",
        "type":"image",
        "url":"p5_name.png"
    },
    {
        "name":"p5_photo_png",
        "type":"image",
        "url":"p5_photo.png"
    },
    {
        "name":"slide_mask_jpg",
        "type":"image",
        "url":"slide_mask.jpg"
    },
    {
        "name":"slide_text_png",
        "type":"image",
        "url":"slide_text.png"
    },
    {
        "name":"top_2017_png",
        "type":"image",
        "url":"top_2017.png"
    },
    {
        "name":"top_bg_png",
        "type":"image",
        "url":"top_bg.png"
    },
    {
        "name":"top_text_png",
        "type":"image",
        "url":"top_text.png"
    },
    {
        "name":"top_title_png",
        "type":"image",
        "url":"top_title.png"
    },
    {
        "name":"floater_png",
        "type":"image",
        "url":"floater.png"
    }
];