var resData = [
    {
        "name":"pic-4_png",
        "type":"image",
        "url":"pic-4.png"
    },
    {
        "name":"scal_png",
        "type":"image",
        "url":"scal.png"
    },
    {
        "name":"sicon_png",
        "type":"image",
        "url":"sicon.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"top-bg_png",
        "type":"image",
        "url":"top-bg.png"
    },
    {
        "name":"w-1_png",
        "type":"image",
        "url":"w-1.png"
    },
    {
        "name":"w-2_png",
        "type":"image",
        "url":"w-2.png"
    },
    {
        "name":"w-3_png",
        "type":"image",
        "url":"w-3.png"
    },
    {
        "name":"w-4_png",
        "type":"image",
        "url":"w-4.png"
    },
    {
        "name":"word_png",
        "type":"image",
        "url":"word.png"
    },
    {
        "name":"ws-1_png",
        "type":"image",
        "url":"ws-1.png"
    },
    {
        "name":"ws-1-q_png",
        "type":"image",
        "url":"ws-1-q.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cloud-1-1_png",
        "type":"image",
        "url":"cloud-1-1.png"
    },
    {
        "name":"cloud-1-2_png",
        "type":"image",
        "url":"cloud-1-2.png"
    },
    {
        "name":"cloud-2-1_png",
        "type":"image",
        "url":"cloud-2-1.png"
    },
    {
        "name":"cloud-2-2_png",
        "type":"image",
        "url":"cloud-2-2.png"
    },
    {
        "name":"cloud-3-1_png",
        "type":"image",
        "url":"cloud-3-1.png"
    },
    {
        "name":"cloud-3-2_png",
        "type":"image",
        "url":"cloud-3-2.png"
    },
    {
        "name":"f-bg_jpg",
        "type":"image",
        "url":"f-bg.jpg"
    },
    {
        "name":"f-bg_png",
        "type":"image",
        "url":"f-bg.png"
    },
    {
        "name":"ka-1_png",
        "type":"image",
        "url":"ka-1.png"
    },
    {
        "name":"light-r_png",
        "type":"image",
        "url":"light-r.png"
    },
    {
        "name":"mon_png",
        "type":"image",
        "url":"mon.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"pic-1_png",
        "type":"image",
        "url":"pic-1.png"
    },
    {
        "name":"pic-2_png",
        "type":"image",
        "url":"pic-2.png"
    },
    {
        "name":"pic-3_png",
        "type":"image",
        "url":"pic-3.png"
    }
];