var resData = [
    {
        "name":"cake-a_png",
        "type":"image",
        "url":"cake-a.png"
    },
    {
        "name":"lang-1_png",
        "type":"image",
        "url":"lang-1.png"
    },
    {
        "name":"lang-2_png",
        "type":"image",
        "url":"lang-2.png"
    },
    {
        "name":"lang-3_png",
        "type":"image",
        "url":"lang-3.png"
    },
    {
        "name":"langlang_jpg",
        "type":"image",
        "url":"langlang.jpg"
    },
    {
        "name":"line-1_png",
        "type":"image",
        "url":"line-1.png"
    },
    {
        "name":"line-2_png",
        "type":"image",
        "url":"line-2.png"
    },
    {
        "name":"s-2_png",
        "type":"image",
        "url":"s-2.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"words-1_png",
        "type":"image",
        "url":"words-1.png"
    },
    {
        "name":"words-2_png",
        "type":"image",
        "url":"words-2.png"
    },
    {
        "name":"words-3_png",
        "type":"image",
        "url":"words-3.png"
    },
    {
        "name":"words-4_png",
        "type":"image",
        "url":"words-4.png"
    },
    {
        "name":"words-5_png",
        "type":"image",
        "url":"words-5.png"
    },
    {
        "name":"words-6-1_png",
        "type":"image",
        "url":"words-6-1.png"
    },
    {
        "name":"words-6-2_png",
        "type":"image",
        "url":"words-6-2.png"
    },
    {
        "name":"xuline-1_png",
        "type":"image",
        "url":"xuline-1.png"
    },
    {
        "name":"xuline-2_png",
        "type":"image",
        "url":"xuline-2.png"
    },
    {
        "name":"xuline-3_png",
        "type":"image",
        "url":"xuline-3.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    }
];