var resData = [
    {
        "name":"guagua-cover3_png",
        "type":"image",
        "url":"guagua-cover3.png"
    },
    {
        "name":"hy-title_png",
        "type":"image",
        "url":"hy-title.png"
    },
    {
        "name":"shaozi_png",
        "type":"image",
        "url":"shaozi.png"
    },
    {
        "name":"shou_png",
        "type":"image",
        "url":"shou.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"guagua-cover_png",
        "type":"image",
        "url":"guagua-cover.png"
    },
    {
        "name":"guagua-cover2_png",
        "type":"image",
        "url":"guagua-cover2.png"
    }
];