var resData = [
    {
        "name":"quan-15_png",
        "type":"image",
        "url":"quan-15.png"
    },
    {
        "name":"sec-quan_png",
        "type":"image",
        "url":"sec-quan.png"
    },
    {
        "name":"shou_png",
        "type":"image",
        "url":"shou.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cover_png",
        "type":"image",
        "url":"cover.png"
    },
    {
        "name":"dot_png",
        "type":"image",
        "url":"dot.png"
    },
    {
        "name":"foot-bg_png",
        "type":"image",
        "url":"foot-bg.png"
    },
    {
        "name":"get-agin_png",
        "type":"image",
        "url":"get-agin.png"
    },
    {
        "name":"get-btn_png",
        "type":"image",
        "url":"get-btn.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"icon_20_png",
        "type":"image",
        "url":"icon_20.png"
    },
    {
        "name":"icon_40_png",
        "type":"image",
        "url":"icon_40.png"
    },
    {
        "name":"icon_60_png",
        "type":"image",
        "url":"icon_60.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"quan-5_png",
        "type":"image",
        "url":"quan-5.png"
    },
    {
        "name":"quan-10_png",
        "type":"image",
        "url":"quan-10.png"
    }
];