var resData = [
    {
        "name":"miaosha_png",
        "type":"image",
        "url":"miaosha.png"
    },
    {
        "name":"quanyi_png",
        "type":"image",
        "url":"quanyi.png"
    },
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-17_png",
        "type":"image",
        "url":"cake-17.png"
    },
    {
        "name":"cake-20_png",
        "type":"image",
        "url":"cake-20.png"
    },
    {
        "name":"cake-27_png",
        "type":"image",
        "url":"cake-27.png"
    },
    {
        "name":"cake-28_png",
        "type":"image",
        "url":"cake-28.png"
    },
    {
        "name":"foot-bg_jpg",
        "type":"image",
        "url":"foot-bg.jpg"
    },
    {
        "name":"hongbao_png",
        "type":"image",
        "url":"hongbao.png"
    },
    {
        "name":"t-27_png",
        "type":"image",
        "url":"t-27.png"
    },
    {
        "name":"t-28_png",
        "type":"image",
        "url":"t-28.png"
    },
    {
        "name":"t-5_png",
        "type":"image",
        "url":"t-5.png"
    },
    {
        "name":"t-17_png",
        "type":"image",
        "url":"t-17.png"
    },
    {
        "name":"t-20_png",
        "type":"image",
        "url":"t-20.png"
    }
];