var resData = [
    {
        "name":"quqi-img-4_png",
        "type":"image",
        "url":"quqi-img-4.png"
    },
    {
        "name":"tab-top1_png",
        "type":"image",
        "url":"tab-top1.png"
    },
    {
        "name":"tab-top2_png",
        "type":"image",
        "url":"tab-top2.png"
    },
    {
        "name":"title-tj_png",
        "type":"image",
        "url":"title-tj.png"
    },
    {
        "name":"cake-img-1_png",
        "type":"image",
        "url":"cake-img-1.png"
    },
    {
        "name":"cake-img-2_png",
        "type":"image",
        "url":"cake-img-2.png"
    },
    {
        "name":"cake-img-3_png",
        "type":"image",
        "url":"cake-img-3.png"
    },
    {
        "name":"chir-l_png",
        "type":"image",
        "url":"chir-l.png"
    },
    {
        "name":"chir-man_png",
        "type":"image",
        "url":"chir-man.png"
    },
    {
        "name":"chir-r_png",
        "type":"image",
        "url":"chir-r.png"
    },
    {
        "name":"chir-w_png",
        "type":"image",
        "url":"chir-w.png"
    },
    {
        "name":"foot-img_png",
        "type":"image",
        "url":"foot-img.png"
    },
    {
        "name":"img-1_jpg",
        "type":"image",
        "url":"img-1.jpg"
    },
    {
        "name":"img-2_jpg",
        "type":"image",
        "url":"img-2.jpg"
    },
    {
        "name":"img-3_jpg",
        "type":"image",
        "url":"img-3.jpg"
    },
    {
        "name":"img-4_jpg",
        "type":"image",
        "url":"img-4.jpg"
    },
    {
        "name":"img-5_jpg",
        "type":"image",
        "url":"img-5.jpg"
    },
    {
        "name":"img-6_jpg",
        "type":"image",
        "url":"img-6.jpg"
    },
    {
        "name":"img-t-1_jpg",
        "type":"image",
        "url":"img-t-1.jpg"
    },
    {
        "name":"img-t-2_jpg",
        "type":"image",
        "url":"img-t-2.jpg"
    },
    {
        "name":"img-t-3_jpg",
        "type":"image",
        "url":"img-t-3.jpg"
    },
    {
        "name":"img-t-4_jpg",
        "type":"image",
        "url":"img-t-4.jpg"
    },
    {
        "name":"img-t-5_jpg",
        "type":"image",
        "url":"img-t-5.jpg"
    },
    {
        "name":"img-t-6_jpg",
        "type":"image",
        "url":"img-t-6.jpg"
    },
    {
        "name":"quqi-img-1_png",
        "type":"image",
        "url":"quqi-img-1.png"
    },
    {
        "name":"quqi-img-2_png",
        "type":"image",
        "url":"quqi-img-2.png"
    },
    {
        "name":"quqi-img-3_png",
        "type":"image",
        "url":"quqi-img-3.png"
    }
];