var resData = [
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"img-4_png",
        "type":"image",
        "url":"img-4.png"
    },
    {
        "name":"img-5_png",
        "type":"image",
        "url":"img-5.png"
    },
    {
        "name":"img-6_png",
        "type":"image",
        "url":"img-6.png"
    },
    {
        "name":"img-7_png",
        "type":"image",
        "url":"img-7.png"
    },
    {
        "name":"img-8_png",
        "type":"image",
        "url":"img-8.png"
    },
    {
        "name":"lihe-1_png",
        "type":"image",
        "url":"lihe-1.png"
    },
    {
        "name":"lihe-2_png",
        "type":"image",
        "url":"lihe-2.png"
    },
    {
        "name":"lipin-card_png",
        "type":"image",
        "url":"lipin-card.png"
    }
];