var resData = [
    {
        "name":"price-3_png",
        "type":"image",
        "url":"price-3.png"
    },
    {
        "name":"s-title-1_png",
        "type":"image",
        "url":"s-title-1.png"
    },
    {
        "name":"s-title-2_png",
        "type":"image",
        "url":"s-title-2.png"
    },
    {
        "name":"s-title-3_png",
        "type":"image",
        "url":"s-title-3.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"code_png",
        "type":"image",
        "url":"code.png"
    },
    {
        "name":"go-buy-1_png",
        "type":"image",
        "url":"go-buy-1.png"
    },
    {
        "name":"go-buy-2_png",
        "type":"image",
        "url":"go-buy-2.png"
    },
    {
        "name":"go-buy-3_png",
        "type":"image",
        "url":"go-buy-3.png"
    },
    {
        "name":"gou-1-1_png",
        "type":"image",
        "url":"gou-1-1.png"
    },
    {
        "name":"gou-1-2_png",
        "type":"image",
        "url":"gou-1-2.png"
    },
    {
        "name":"gou-2-1_png",
        "type":"image",
        "url":"gou-2-1.png"
    },
    {
        "name":"gou-2-2_png",
        "type":"image",
        "url":"gou-2-2.png"
    },
    {
        "name":"gou-3-1_png",
        "type":"image",
        "url":"gou-3-1.png"
    },
    {
        "name":"gou-3-2_png",
        "type":"image",
        "url":"gou-3-2.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"price-1_png",
        "type":"image",
        "url":"price-1.png"
    },
    {
        "name":"price-2_png",
        "type":"image",
        "url":"price-2.png"
    }
];