var resData = [
    {
        "name":"hongbao_png",
        "type":"image",
        "url":"hongbao.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"reduce-1_png",
        "type":"image",
        "url":"reduce-1.png"
    },
    {
        "name":"sec-bg-1_png",
        "type":"image",
        "url":"sec-bg-1.png"
    },
    {
        "name":"sec-bg-2_png",
        "type":"image",
        "url":"sec-bg-2.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"t-5_png",
        "type":"image",
        "url":"t-5.png"
    },
    {
        "name":"t-6_png",
        "type":"image",
        "url":"t-6.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"xiaoduo_png",
        "type":"image",
        "url":"xiaoduo.png"
    },
    {
        "name":"add-1_png",
        "type":"image",
        "url":"add-1.png"
    },
    {
        "name":"banner-cake_png",
        "type":"image",
        "url":"banner-cake.png"
    },
    {
        "name":"banner-logo_png",
        "type":"image",
        "url":"banner-logo.png"
    },
    {
        "name":"banner-txt_png",
        "type":"image",
        "url":"banner-txt.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    }
];