var resData = [
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"bonbon_png",
        "type":"image",
        "url":"bonbon.png"
    },
    {
        "name":"crepes_png",
        "type":"image",
        "url":"crepes.png"
    },
    {
        "name":"logo_png",
        "type":"image",
        "url":"logo.png"
    },
    {
        "name":"milk_png",
        "type":"image",
        "url":"milk.png"
    },
    {
        "name":"mousse_png",
        "type":"image",
        "url":"mousse.png"
    },
    {
        "name":"pink_png",
        "type":"image",
        "url":"pink.png"
    },
    {
        "name":"rulebg_png",
        "type":"image",
        "url":"rulebg.png"
    },
    {
        "name":"shumei_png",
        "type":"image",
        "url":"shumei.png"
    }
];