var resData = [
  {
    "name":"0_png",
    "type":"image",
    "url":"0.png"
  },
  {
    "name":"1_png",
    "type":"image",
    "url":"1.png"
  },
  {
    "name":"2_png",
    "type":"image",
    "url":"2.png"
  },
  {
    "name":"3_png",
    "type":"image",
    "url":"3.png"
  },
  {
    "name":"4_png",
    "type":"image",
    "url":"4.png"
  },
  {
    "name":"5_png",
    "type":"image",
    "url":"5.png"
  },
  {
    "name":"6_png",
    "type":"image",
    "url":"6.png"
  },
  {
    "name":"7_png",
    "type":"image",
    "url":"7.png"
  },
  {
    "name":"8_png",
    "type":"image",
    "url":"8.png"
  },
  {
    "name":"9_png",
    "type":"image",
    "url":"9.png"
  },
  {
    "name":"banner-bg_jpg",
    "type":"image",
    "url":"banner-bg.jpg"
  },
  {
    "name":"banner-text_png",
    "type":"image",
    "url":"banner-text.png"
  },
  {
    "name":"cake_png",
    "type":"image",
    "url":"cake.png"
  },
  {
    "name":"cake-sm_png",
    "type":"image",
    "url":"cake-sm.png"
  },
  {
    "name":"cake-tips_png",
    "type":"image",
    "url":"cake-tips.png"
  },
  {
    "name":"checkbox_png",
    "type":"image",
    "url":"checkbox.png"
  },
  {
    "name":"counter-bg_png",
    "type":"image",
    "url":"counter-bg.png"
  },
  {
    "name":"deco1_png",
    "type":"image",
    "url":"deco1.png"
  },
  {
    "name":"deco2_png",
    "type":"image",
    "url":"deco2.png"
  },
  {
    "name":"deco3_png",
    "type":"image",
    "url":"deco3.png"
  },
  {
    "name":"deco4_png",
    "type":"image",
    "url":"deco4.png"
  },
  {
    "name":"footer-action_png",
    "type":"image",
    "url":"footer-action.png"
  },
  {
    "name":"logo_png",
    "type":"image",
    "url":"logo.png"
  },
  {
    "name":"main-bg_jpg",
    "type":"image",
    "url":"main-bg.jpg"
  },
  {
    "name":"main-cake_png",
    "type":"image",
    "url":"main-cake.png"
  },
  {
    "name":"main-text_png",
    "type":"image",
    "url":"main-text.png"
  },
  {
    "name":"nut_png",
    "type":"image",
    "url":"nut.png"
  },
  {
    "name":"spoon_png",
    "type":"image",
    "url":"spoon.png"
  }];