var resData = [
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"add-1_png",
        "type":"image",
        "url":"add-1.png"
    },
    {
        "name":"add-2_png",
        "type":"image",
        "url":"add-2.png"
    },
    {
        "name":"add-3_png",
        "type":"image",
        "url":"add-3.png"
    },
    {
        "name":"add-4_png",
        "type":"image",
        "url":"add-4.png"
    },
    {
        "name":"add-5_png",
        "type":"image",
        "url":"add-5.png"
    },
    {
        "name":"banner-1_png",
        "type":"image",
        "url":"banner-1.png"
    },
    {
        "name":"banner-2_png",
        "type":"image",
        "url":"banner-2.png"
    },
    {
        "name":"banner-3_png",
        "type":"image",
        "url":"banner-3.png"
    },
    {
        "name":"banner-4_png",
        "type":"image",
        "url":"banner-4.png"
    },
    {
        "name":"banner-t_png",
        "type":"image",
        "url":"banner-t.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"hongbao_png",
        "type":"image",
        "url":"hongbao.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"quanyi_png",
        "type":"image",
        "url":"quanyi.png"
    },
    {
        "name":"reduce-1_png",
        "type":"image",
        "url":"reduce-1.png"
    },
    {
        "name":"reduce-2_png",
        "type":"image",
        "url":"reduce-2.png"
    },
    {
        "name":"reduce-3_png",
        "type":"image",
        "url":"reduce-3.png"
    },
    {
        "name":"reduce-4_png",
        "type":"image",
        "url":"reduce-4.png"
    },
    {
        "name":"reduce-5_png",
        "type":"image",
        "url":"reduce-5.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"t-5_png",
        "type":"image",
        "url":"t-5.png"
    }
];