var resData = [
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"title-line_png",
        "type":"image",
        "url":"title-line.png"
    },
    {
        "name":"title-line-1_png",
        "type":"image",
        "url":"title-line-1.png"
    },
    {
        "name":"title-line-2_png",
        "type":"image",
        "url":"title-line-2.png"
    },
    {
        "name":"top-bar_02_png",
        "type":"image",
        "url":"top-bar_02.png"
    },
    {
        "name":"bangshu_png",
        "type":"image",
        "url":"bangshu.png"
    },
    {
        "name":"bangshuli_png",
        "type":"image",
        "url":"bangshuli.png"
    },
    {
        "name":"bg_03_jpg",
        "type":"image",
        "url":"bg_03.jpg"
    },
    {
        "name":"bg-ds-1_png",
        "type":"image",
        "url":"bg-ds-1.png"
    },
    {
        "name":"bg-ds-2_png",
        "type":"image",
        "url":"bg-ds-2.png"
    },
    {
        "name":"bg-ds-3_png",
        "type":"image",
        "url":"bg-ds-3.png"
    },
    {
        "name":"bg-ds-4_png",
        "type":"image",
        "url":"bg-ds-4.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"btn-bg_png",
        "type":"image",
        "url":"btn-bg.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cakebg_png",
        "type":"image",
        "url":"cakebg.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"minus_png",
        "type":"image",
        "url":"minus.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"plus_png",
        "type":"image",
        "url":"plus.png"
    },
    {
        "name":"pr-bd_png",
        "type":"image",
        "url":"pr-bd.png"
    }
];