var resData = [
    {
        "name":"text-1_png",
        "type":"image",
        "url":"text-1.png"
    },
    {
        "name":"text-2_png",
        "type":"image",
        "url":"text-2.png"
    },
    {
        "name":"text-3_png",
        "type":"image",
        "url":"text-3.png"
    },
    {
        "name":"text-4_png",
        "type":"image",
        "url":"text-4.png"
    },
    {
        "name":"text-5_png",
        "type":"image",
        "url":"text-5.png"
    },
    {
        "name":"word_png",
        "type":"image",
        "url":"word.png"
    },
    {
        "name":"ad-1_jpg",
        "type":"image",
        "url":"ad-1.jpg"
    },
    {
        "name":"ad-2_jpg",
        "type":"image",
        "url":"ad-2.jpg"
    },
    {
        "name":"ad-3_jpg",
        "type":"image",
        "url":"ad-3.jpg"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"ds-1_png",
        "type":"image",
        "url":"ds-1.png"
    },
    {
        "name":"ds-2_png",
        "type":"image",
        "url":"ds-2.png"
    },
    {
        "name":"ds-3_png",
        "type":"image",
        "url":"ds-3.png"
    },
    {
        "name":"ds-4_png",
        "type":"image",
        "url":"ds-4.png"
    },
    {
        "name":"ds-5_png",
        "type":"image",
        "url":"ds-5.png"
    },
    {
        "name":"hd_png",
        "type":"image",
        "url":"hd.png"
    },
    {
        "name":"icon_png",
        "type":"image",
        "url":"icon.png"
    },
    {
        "name":"pan-2_png",
        "type":"image",
        "url":"pan-2.png"
    },
    {
        "name":"pro-1_png",
        "type":"image",
        "url":"pro-1.png"
    },
    {
        "name":"pro-2_png",
        "type":"image",
        "url":"pro-2.png"
    },
    {
        "name":"pro-3_png",
        "type":"image",
        "url":"pro-3.png"
    },
    {
        "name":"pro-4_png",
        "type":"image",
        "url":"pro-4.png"
    },
    {
        "name":"pro-5_png",
        "type":"image",
        "url":"pro-5.png"
    }
];