var resData = [
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"icon_15_png",
        "type":"image",
        "url":"icon_15.png"
    },
    {
        "name":"icon_30_png",
        "type":"image",
        "url":"icon_30.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-2_png",
        "type":"image",
        "url":"sec-2.png"
    },
    {
        "name":"sec-3_png",
        "type":"image",
        "url":"sec-3.png"
    },
    {
        "name":"sec-4_png",
        "type":"image",
        "url":"sec-4.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"shanghai/cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"shanghai/cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"shanghai/cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"shanghai/cake-4.png"
    },
    {
        "name":"cake-t-1_png",
        "type":"image",
        "url":"shanghai/cake-t-1.png"
    },
    {
        "name":"cake-t-2_png",
        "type":"image",
        "url":"shanghai/cake-t-2.png"
    },
    {
        "name":"cake-t-3_png",
        "type":"image",
        "url":"shanghai/cake-t-3.png"
    },
    {
        "name":"cake-t-4_png",
        "type":"image",
        "url":"shanghai/cake-t-4.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"shanghai/hy-title-1.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"shanghai/zp.png"
    }
];