var resData = [
    {
        "name":"tower2_png",
        "type":"image",
        "url":"tower2.png"
    },
    {
        "name":"word_qing_png",
        "type":"image",
        "url":"word_qing.png"
    },
    {
        "name":"word_shou_png",
        "type":"image",
        "url":"word_shou.png"
    },
    {
        "name":"word_yi_png",
        "type":"image",
        "url":"word_yi.png"
    },
    {
        "name":"act_ge_png",
        "type":"image",
        "url":"act_ge.png"
    },
    {
        "name":"act_sheng_png",
        "type":"image",
        "url":"act_sheng.png"
    },
    {
        "name":"act_text_png",
        "type":"image",
        "url":"act_text.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"pic01_jpg",
        "type":"image",
        "url":"pic01.jpg"
    },
    {
        "name":"plate_png",
        "type":"image",
        "url":"plate.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"text1893_png",
        "type":"image",
        "url":"text1893.png"
    },
    {
        "name":"top_pic_jpg",
        "type":"image",
        "url":"top_pic.jpg"
    },
    {
        "name":"top_pingan_png",
        "type":"image",
        "url":"top_pingan.png"
    },
    {
        "name":"top_quality_png",
        "type":"image",
        "url":"top_quality.png"
    },
    {
        "name":"top_sq_png",
        "type":"image",
        "url":"top_sq.png"
    },
    {
        "name":"tower1_png",
        "type":"image",
        "url":"tower1.png"
    }
];