var resData = [
    {
        "name":"weidao_png",
        "type":"image",
        "url":"weidao.png"
    },
    {
        "name":"word-1_png",
        "type":"image",
        "url":"word-1.png"
    },
    {
        "name":"word-2_png",
        "type":"image",
        "url":"word-2.png"
    },
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"go-btn_png",
        "type":"image",
        "url":"go-btn.png"
    },
    {
        "name":"guize-1_png",
        "type":"image",
        "url":"guize-1.png"
    },
    {
        "name":"guize-more_png",
        "type":"image",
        "url":"guize-more.png"
    },
    {
        "name":"huajian-box-1_png",
        "type":"image",
        "url":"huajian-box-1.png"
    },
    {
        "name":"huajian-box-2_png",
        "type":"image",
        "url":"huajian-box-2.png"
    },
    {
        "name":"huajian-box-3_png",
        "type":"image",
        "url":"huajian-box-3.png"
    },
    {
        "name":"huajian-box-4_png",
        "type":"image",
        "url":"huajian-box-4.png"
    },
    {
        "name":"kanshi-1_png",
        "type":"image",
        "url":"kanshi-1.png"
    },
    {
        "name":"kanshi-2_png",
        "type":"image",
        "url":"kanshi-2.png"
    },
    {
        "name":"moon-1_png",
        "type":"image",
        "url":"moon-1.png"
    },
    {
        "name":"moon-2_png",
        "type":"image",
        "url":"moon-2.png"
    },
    {
        "name":"moon-3_png",
        "type":"image",
        "url":"moon-3.png"
    },
    {
        "name":"moon-4_png",
        "type":"image",
        "url":"moon-4.png"
    },
    {
        "name":"qiushui-box-1_png",
        "type":"image",
        "url":"qiushui-box-1.png"
    },
    {
        "name":"qiushui-box-2_png",
        "type":"image",
        "url":"qiushui-box-2.png"
    },
    {
        "name":"qiushui-box-3_png",
        "type":"image",
        "url":"qiushui-box-3.png"
    },
    {
        "name":"qiushui-box-4_png",
        "type":"image",
        "url":"qiushui-box-4.png"
    },
    {
        "name":"qiushui-box-5_png",
        "type":"image",
        "url":"qiushui-box-5.png"
    },
    {
        "name":"shouna-1_png",
        "type":"image",
        "url":"shouna-1.png"
    },
    {
        "name":"shouna-2_png",
        "type":"image",
        "url":"shouna-2.png"
    },
    {
        "name":"tab-title-1_png",
        "type":"image",
        "url":"tab-title-1.png"
    },
    {
        "name":"tab-title-2_png",
        "type":"image",
        "url":"tab-title-2.png"
    }
];