var resData = [
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"xiaoshi-1_png",
        "type":"image",
        "url":"xiaoshi-1.png"
    },
    {
        "name":"xiaoshi-2_png",
        "type":"image",
        "url":"xiaoshi-2.png"
    },
    {
        "name":"xiaoshi-3_png",
        "type":"image",
        "url":"xiaoshi-3.png"
    },
    {
        "name":"xiaoshi-4_png",
        "type":"image",
        "url":"xiaoshi-4.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"car_png",
        "type":"image",
        "url":"car.png"
    },
    {
        "name":"car-on_png",
        "type":"image",
        "url":"car-on.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"code_png",
        "type":"image",
        "url":"code.png"
    },
    {
        "name":"dot_png",
        "type":"image",
        "url":"dot.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"img-4_png",
        "type":"image",
        "url":"img-4.png"
    },
    {
        "name":"img-5_png",
        "type":"image",
        "url":"img-5.png"
    },
    {
        "name":"img-6_png",
        "type":"image",
        "url":"img-6.png"
    },
    {
        "name":"jf-pz_png",
        "type":"image",
        "url":"jf-pz.png"
    },
    {
        "name":"jian-20_png",
        "type":"image",
        "url":"jian-20.png"
    },
    {
        "name":"jian-30_png",
        "type":"image",
        "url":"jian-30.png"
    },
    {
        "name":"jian-50_png",
        "type":"image",
        "url":"jian-50.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"num-2_png",
        "type":"image",
        "url":"num-2.png"
    },
    {
        "name":"num-3_png",
        "type":"image",
        "url":"num-3.png"
    },
    {
        "name":"num-4_png",
        "type":"image",
        "url":"num-4.png"
    },
    {
        "name":"num-5_png",
        "type":"image",
        "url":"num-5.png"
    },
    {
        "name":"price_png",
        "type":"image",
        "url":"price.png"
    }
];