var resData = [
    {
        "name":"price-6_png",
        "type":"image",
        "url":"price-6.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"price-1_png",
        "type":"image",
        "url":"price-1.png"
    },
    {
        "name":"price-2_png",
        "type":"image",
        "url":"price-2.png"
    },
    {
        "name":"price-3_png",
        "type":"image",
        "url":"price-3.png"
    },
    {
        "name":"price-4_png",
        "type":"image",
        "url":"price-4.png"
    },
    {
        "name":"price-5_png",
        "type":"image",
        "url":"price-5.png"
    }
];