var resData = [
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"floater_png",
        "type":"image",
        "url":"floater.png"
    },
    {
        "name":"hd-title-1_png",
        "type":"image",
        "url":"hd-title-1.png"
    },
    {
        "name":"hd-title-2_png",
        "type":"image",
        "url":"hd-title-2.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"text_png",
        "type":"image",
        "url":"text.png"
    },
    {
        "name":"xs-1_png",
        "type":"image",
        "url":"xs-1.png"
    },
    {
        "name":"xs-2_png",
        "type":"image",
        "url":"xs-2.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"btn-buy_png",
        "type":"image",
        "url":"btn-buy.png"
    },
    {
        "name":"btn-cart_png",
        "type":"image",
        "url":"btn-cart.png"
    }
];