var resData = [
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"wx-code_png",
        "type":"image",
        "url":"wx-code.png"
    },
    {
        "name":"about_png",
        "type":"image",
        "url":"about.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"buy-btn_png",
        "type":"image",
        "url":"buy-btn.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"car-btn-1_png",
        "type":"image",
        "url":"car-btn-1.png"
    },
    {
        "name":"cart_png",
        "type":"image",
        "url":"cart.png"
    },
    {
        "name":"foot-bg_png",
        "type":"image",
        "url":"foot-bg.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"icon-wx_png",
        "type":"image",
        "url":"icon-wx.png"
    },
    {
        "name":"img-1_jpg",
        "type":"image",
        "url":"img-1.jpg"
    },
    {
        "name":"img-2_jpg",
        "type":"image",
        "url":"img-2.jpg"
    },
    {
        "name":"img-3_jpg",
        "type":"image",
        "url":"img-3.jpg"
    },
    {
        "name":"img-4_jpg",
        "type":"image",
        "url":"img-4.jpg"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"input-bg_png",
        "type":"image",
        "url":"input-bg.png"
    },
    {
        "name":"lipin_png",
        "type":"image",
        "url":"lipin.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"pic01_jpg",
        "type":"image",
        "url":"pic01.jpg"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"s-title-1_png",
        "type":"image",
        "url":"s-title-1.png"
    },
    {
        "name":"s-title-2_png",
        "type":"image",
        "url":"s-title-2.png"
    },
    {
        "name":"s-title-3_png",
        "type":"image",
        "url":"s-title-3.png"
    },
    {
        "name":"s-title-4_png",
        "type":"image",
        "url":"s-title-4.png"
    },
    {
        "name":"submit-btn_png",
        "type":"image",
        "url":"submit-btn.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    }
];