var resData = [
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"banner-bg_png",
        "type":"image",
        "url":"banner-bg.png"
    },
    {
        "name":"banner-cake-1_png",
        "type":"image",
        "url":"banner-cake-1.png"
    },
    {
        "name":"banner-cake-2_png",
        "type":"image",
        "url":"banner-cake-2.png"
    },
    {
        "name":"banner-title_png",
        "type":"image",
        "url":"banner-title.png"
    },
    {
        "name":"img-1_03_jpg",
        "type":"image",
        "url":"img-1_03.jpg"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"qidai_png",
        "type":"image",
        "url":"qidai.png"
    },
    {
        "name":"shaozi_png",
        "type":"image",
        "url":"shaozi.png"
    },
    {
        "name":"text-1893_png",
        "type":"image",
        "url":"text-1893.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    }
];