var resData = [
    {
        "name":"fen_png",
        "type":"image",
        "url":"fen.png"
    },

    {
        "name":"minus_png",
        "type":"image",
        "url":"minus.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"plus_png",
        "type":"image",
        "url":"plus.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"step1_png",
        "type":"image",
        "url":"step1.png"
    },
    {
        "name":"step2_png",
        "type":"image",
        "url":"step2.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"topsnow_png",
        "type":"image",
        "url":"topsnow.png"
    },
    {
        "name":"buybtn_png",
        "type":"image",
        "url":"buybtn.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake1_png",
        "type":"image",
        "url":"cake1.png"
    },
    {
        "name":"cake2_png",
        "type":"image",
        "url":"cake2.png"
    },
    {
        "name":"cake3_png",
        "type":"image",
        "url":"cake3.png"
    },
    {
        "name":"cakebg_png",
        "type":"image",
        "url":"cakebg.png"
    },
    {
        "name":"ewm_png",
        "type":"image",
        "url":"ewm.png"
    }
    ,
    {
        "name":"code1_png",
        "type":"image",
        "url":"code1.png"
    }
    ,
    {
        "name":"code2_png",
        "type":"image",
        "url":"code2.png"
    }
];