var resData = [
    {
        "name":"foot_bg_png",
        "type":"image",
        "url":"foot_bg.png"
    },
    {
        "name":"sec_bg_1_png",
        "type":"image",
        "url":"sec_bg_1.png"
    },
    {
        "name":"sec_bg_2_png",
        "type":"image",
        "url":"sec_bg_2.png"
    },
    {
        "name":"sec_bg_3_png",
        "type":"image",
        "url":"sec_bg_3.png"
    },
    {
        "name":"sec_title_1_png",
        "type":"image",
        "url":"sec_title_1.png"
    },
    {
        "name":"sec_title_2_png",
        "type":"image",
        "url":"sec_title_2.png"
    },
    {
        "name":"sec_title_3_png",
        "type":"image",
        "url":"sec_title_3.png"
    },
    {
        "name":"star_png",
        "type":"image",
        "url":"star.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bj_bread_1_1_png",
        "type":"image",
        "url":"bj_bread_1_1.png"
    },
    {
        "name":"bj_bread_1_2_png",
        "type":"image",
        "url":"bj_bread_1_2.png"
    },
    {
        "name":"bj_bread_1_t_png",
        "type":"image",
        "url":"bj_bread_1_t.png"
    },
    {
        "name":"bj_bread_2_1_png",
        "type":"image",
        "url":"bj_bread_2_1.png"
    },
    {
        "name":"bj_bread_2_2_png",
        "type":"image",
        "url":"bj_bread_2_2.png"
    },
    {
        "name":"bj_bread_2_t_png",
        "type":"image",
        "url":"bj_bread_2_t.png"
    },
    {
        "name":"bj_bread_group_1_png",
        "type":"image",
        "url":"bj_bread_group_1.png"
    },
    {
        "name":"bj_bread_group_2_png",
        "type":"image",
        "url":"bj_bread_group_2.png"
    },
    {
        "name":"bj_bread_offer_png",
        "type":"image",
        "url":"bj_bread_offer.png"
    },
    {
        "name":"bread_1_1_png",
        "type":"image",
        "url":"bread_1_1.png"
    },
    {
        "name":"bread_1_2_png",
        "type":"image",
        "url":"bread_1_2.png"
    },
    {
        "name":"bread_1_t_png",
        "type":"image",
        "url":"bread_1_t.png"
    },
    {
        "name":"bread_2_1_png",
        "type":"image",
        "url":"bread_2_1.png"
    },
    {
        "name":"bread_2_2_png",
        "type":"image",
        "url":"bread_2_2.png"
    },
    {
        "name":"bread_2_t_png",
        "type":"image",
        "url":"bread_2_t.png"
    },
    {
        "name":"bread_3_1_png",
        "type":"image",
        "url":"bread_3_1.png"
    },
    {
        "name":"bread_3_2_png",
        "type":"image",
        "url":"bread_3_2.png"
    },
    {
        "name":"bread_3_t_png",
        "type":"image",
        "url":"bread_3_t.png"
    },
    {
        "name":"bread_group_1_png",
        "type":"image",
        "url":"bread_group_1.png"
    },
    {
        "name":"bread_group_2_png",
        "type":"image",
        "url":"bread_group_2.png"
    },
    {
        "name":"bread_offer_png",
        "type":"image",
        "url":"bread_offer.png"
    }

];