var resData = [
  {
    "name":"sec2-bg_png",
    "type":"image",
    "url":"sec2-bg.png"
  },
  {
    "name":"banner2_png",
    "type":"image",
    "url":"sec2/banner2.png"
  },
  {
    "name":"sec2-p12-text_png",
    "type":"image",
    "url":"sec2/sec2-p12-text.png"
  },
  {
    "name":"sec2-p12_png",
    "type":"image",
    "url":"sec2/sec2-p12.png"
  },
  {
    "name":"sec2-p22_png",
    "type":"image",
    "url":"sec2/sec2-p22.png"
  },
  {
    "name":"border-img_png",
    "type":"image",
    "url":"border-img.png"
  },
  {
    "name":"border-img2_png",
    "type":"image",
    "url":"border-img2.png"
  },
  {
    "name":"buy-btn_png",
    "type":"image",
    "url":"buy-btn.png"
  },
  {
    "name":"sec1-bg_jpg",
    "type":"image",
    "url":"sec1-bg.jpg"
  }];