var resData = [
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"xiaoshi-1_png",
        "type":"image",
        "url":"xiaoshi-1.png"
    },
    {
        "name":"xiaoshi-2_png",
        "type":"image",
        "url":"xiaoshi-2.png"
    },
    {
        "name":"xiaoshi-3_png",
        "type":"image",
        "url":"xiaoshi-3.png"
    },
    {
        "name":"banner-wap_png",
        "type":"image",
        "url":"banner-wap.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cart_png",
        "type":"image",
        "url":"cart.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"footer-bg_png",
        "type":"image",
        "url":"footer-bg.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"hy-title-3_png",
        "type":"image",
        "url":"hy-title-3.png"
    },
    {
        "name":"in-l_png",
        "type":"image",
        "url":"in-l.png"
    },
    {
        "name":"in-r_png",
        "type":"image",
        "url":"in-r.png"
    },
    {
        "name":"sele-li_png",
        "type":"image",
        "url":"sele-li.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    }
];