var resData = [
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"shengyu_png",
        "type":"image",
        "url":"shengyu.png"
    },
    {
        "name":"step_png",
        "type":"image",
        "url":"step.png"
    },
    {
        "name":"t-gz_png",
        "type":"image",
        "url":"t-gz.png"
    },
    {
        "name":"time_png",
        "type":"image",
        "url":"time.png"
    },
    {
        "name":"t-lc_png",
        "type":"image",
        "url":"t-lc.png"
    },
    {
        "name":"t-style_png",
        "type":"image",
        "url":"t-style.png"
    },
    {
        "name":"act_text_png",
        "type":"image",
        "url":"act_text.png"
    },
    {
        "name":"banner-1_png",
        "type":"image",
        "url":"banner-1.png"
    },
    {
        "name":"banner-2_png",
        "type":"image",
        "url":"banner-2.png"
    },
    {
        "name":"btn-add_png",
        "type":"image",
        "url":"btn-add.png"
    },
    {
        "name":"btn-minus_png",
        "type":"image",
        "url":"btn-minus.png"
    },
    {
        "name":"gh-code_png",
        "type":"image",
        "url":"gh-code.png"
    },
    {
        "name":"mcake-code_png",
        "type":"image",
        "url":"mcake-code.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    }
];