var resData = [
  {
    "name":"q-text_png",
    "type":"image",
    "url":"q-text.png"
  },
  {
    "name":"q1_png",
    "type":"image",
    "url":"q1.png"
  },
  {
    "name":"q2_png",
    "type":"image",
    "url":"q2.png"
  },
  {
    "name":"q3-bg_jpg",
    "type":"image",
    "url":"q3-bg.jpg"
  },
  {
    "name":"q3-header_png",
    "type":"image",
    "url":"q3-header.png"
  },
  {
    "name":"q3-text_png",
    "type":"image",
    "url":"q3-text.png"
  },
  {
    "name":"q4_jpg",
    "type":"image",
    "url":"q4.jpg"
  },
  {
    "name":"q4-text_png",
    "type":"image",
    "url":"q4-text.png"
  },
  {
    "name":"q5_png",
    "type":"image",
    "url":"q5.png"
  },
  {
    "name":"q5-header_jpg",
    "type":"image",
    "url":"q5-header.jpg"
  },
  {
    "name":"q5-text_png",
    "type":"image",
    "url":"q5-text.png"
  }];