var resData = [
    {
        "name":"word-2_png",
        "type":"image",
        "url":"word-2.png"
    },
    {
        "name":"acrow_png",
        "type":"image",
        "url":"acrow.png"
    },
    {
        "name":"acrow1_png",
        "type":"image",
        "url":"acrow1.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"details_png",
        "type":"image",
        "url":"details.png"
    },
    {
        "name":"girl-a_png",
        "type":"image",
        "url":"girl-a.png"
    },
    {
        "name":"girl-b_png",
        "type":"image",
        "url":"girl-b.png"
    },
    {
        "name":"girl-c_png",
        "type":"image",
        "url":"girl-c.png"
    },
    {
        "name":"girl-d_png",
        "type":"image",
        "url":"girl-d.png"
    },
    {
        "name":"girl-e_png",
        "type":"image",
        "url":"girl-e.png"
    },
    {
        "name":"line1_jpg",
        "type":"image",
        "url":"line1.jpg"
    },
    {
        "name":"line2_jpg",
        "type":"image",
        "url":"line2.jpg"
    },
    {
        "name":"product1_png",
        "type":"image",
        "url":"product1.png"
    },
    {
        "name":"product2_png",
        "type":"image",
        "url":"product2.png"
    },
    {
        "name":"r-clod1_png",
        "type":"image",
        "url":"r-clod1.png"
    },
    {
        "name":"r-clod2_png",
        "type":"image",
        "url":"r-clod2.png"
    },
    {
        "name":"s-cake1_png",
        "type":"image",
        "url":"s-cake1.png"
    },
    {
        "name":"s-cake2_png",
        "type":"image",
        "url":"s-cake2.png"
    },
    {
        "name":"s-cake3_png",
        "type":"image",
        "url":"s-cake3.png"
    },
    {
        "name":"s-cake4_png",
        "type":"image",
        "url":"s-cake4.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"word-1_png",
        "type":"image",
        "url":"word-1.png"
    }
];