var resData = [
    {
        "name":"txt-bg_png",
        "type":"image",
        "url":"txt-bg.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"code_png",
        "type":"image",
        "url":"code.png"
    },
    {
        "name":"code1_png",
        "type":"image",
        "url":"code1.png"
    },
    {
        "name":"code2_png",
        "type":"image",
        "url":"code2.png"
    },
    {
        "name":"ewm_png",
        "type":"image",
        "url":"ewm.png"
    },
    {
        "name":"fen_png",
        "type":"image",
        "url":"fen.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"go-buy-bg_png",
        "type":"image",
        "url":"go-buy-bg.png"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"plate_png",
        "type":"image",
        "url":"plate.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"step1_png",
        "type":"image",
        "url":"step1.png"
    },
    {
        "name":"step2_png",
        "type":"image",
        "url":"step2.png"
    },
    {
        "name":"text1893_png",
        "type":"image",
        "url":"text1893.png"
    },
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    }
];