var resData = [
    {
        "name":"mym-c_png",
        "type":"image",
        "url":"mym-c.png"
    },
    {
        "name":"mym-top_png",
        "type":"image",
        "url":"mym-top.png"
    },
    {
        "name":"ren_png",
        "type":"image",
        "url":"ren.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"top-bg_jpg",
        "type":"image",
        "url":"top-bg.jpg"
    },
    {
        "name":"words-1_png",
        "type":"image",
        "url":"words-1.png"
    },
    {
        "name":"words-2_png",
        "type":"image",
        "url":"words-2.png"
    },
    {
        "name":"words-3_png",
        "type":"image",
        "url":"words-3.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-samll_png",
        "type":"image",
        "url":"cake-samll.png"
    },
    {
        "name":"cl-1_png",
        "type":"image",
        "url":"cl-1.png"
    },
    {
        "name":"cl-2_png",
        "type":"image",
        "url":"cl-2.png"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    },
    {
        "name":"line-lang_png",
        "type":"image",
        "url":"line-lang.png"
    },
    {
        "name":"main-bg_jpg",
        "type":"image",
        "url":"main-bg.jpg"
    },
    {
        "name":"mym_png",
        "type":"image",
        "url":"mym.png"
    },
    {
        "name":"mym-a_png",
        "type":"image",
        "url":"mym-a.png"
    },
    {
        "name":"mym-b_png",
        "type":"image",
        "url":"mym-b.png"
    }
];