var resData = [
    {
        "name":"pumpkin-title_png",
        "type":"image",
        "url":"pumpkin-title.png"
    },
    {
        "name":"tcc_png",
        "type":"image",
        "url":"tcc.png"
    },
    {
        "name":"time-bg_png",
        "type":"image",
        "url":"time-bg.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"txt_png",
        "type":"image",
        "url":"txt.png"
    },
    {
        "name":"txt-1_png",
        "type":"image",
        "url":"txt-1.png"
    },
    {
        "name":"txt-2_png",
        "type":"image",
        "url":"txt-2.png"
    },
    {
        "name":"txt-3_png",
        "type":"image",
        "url":"txt-3.png"
    },
    {
        "name":"banner-t_png",
        "type":"image",
        "url":"banner-t.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-block_png",
        "type":"image",
        "url":"cake-block.png"
    },
    {
        "name":"cake-price_png",
        "type":"image",
        "url":"cake-price.png"
    },
    {
        "name":"card_02_png",
        "type":"image",
        "url":"card_02.png"
    },
    {
        "name":"card-1_png",
        "type":"image",
        "url":"card-1.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"flower-t_png",
        "type":"image",
        "url":"flower-t.png"
    },
    {
        "name":"go-btn_png",
        "type":"image",
        "url":"go-btn.png"
    },
    {
        "name":"go-btn2_png",
        "type":"image",
        "url":"go-btn2.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"go-sj_png",
        "type":"image",
        "url":"go-sj.png"
    },
    {
        "name":"go-use_png",
        "type":"image",
        "url":"go-use.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"main-bg_png",
        "type":"image",
        "url":"main-bg.png"
    },
    {
        "name":"pumpkin-1_png",
        "type":"image",
        "url":"pumpkin-1.png"
    },
    {
        "name":"pumpkin-2_png",
        "type":"image",
        "url":"pumpkin-2.png"
    },
    {
        "name":"pumpkin-3_png",
        "type":"image",
        "url":"pumpkin-3.png"
    },
    {
        "name":"pumpkin-4_png",
        "type":"image",
        "url":"pumpkin-4.png"
    }
];