var resData = [
    {
        "name":"word-1_png",
        "type":"image",
        "url":"word-1.png"
    },
    {
        "name":"word-2_png",
        "type":"image",
        "url":"word-2.png"
    },
    {
        "name":"word-3_png",
        "type":"image",
        "url":"word-3.png"
    },
    {
        "name":"word-4_png",
        "type":"image",
        "url":"word-4.png"
    },
    {
        "name":"word-5_png",
        "type":"image",
        "url":"word-5.png"
    },
    {
        "name":"word-6_png",
        "type":"image",
        "url":"word-6.png"
    },
    {
        "name":"zhifu_png",
        "type":"image",
        "url":"zhifu.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"in-l_png",
        "type":"image",
        "url":"in-l.png"
    },
    {
        "name":"in-r_png",
        "type":"image",
        "url":"in-r.png"
    },
    {
        "name":"pic-2_png",
        "type":"image",
        "url":"pic-2.png"
    },
    {
        "name":"pic-3_png",
        "type":"image",
        "url":"pic-3.png"
    },
    {
        "name":"pic-4_png",
        "type":"image",
        "url":"pic-4.png"
    }
];