var resData = [
    {
        "name":"row-bg_png",
        "type":"image",
        "url":"row-bg.png"
    },
    {
        "name":"ss-bg-1_png",
        "type":"image",
        "url":"ss-bg-1.png"
    },
    {
        "name":"ss-bg-2_png",
        "type":"image",
        "url":"ss-bg-2.png"
    },
    {
        "name":"ss-bg-3_png",
        "type":"image",
        "url":"ss-bg-3.png"
    },
    {
        "name":"t-0-1_png",
        "type":"image",
        "url":"t-0-1.png"
    },
    {
        "name":"t-0-2_png",
        "type":"image",
        "url":"t-0-2.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"t-5_png",
        "type":"image",
        "url":"t-5.png"
    },
    {
        "name":"t-6_png",
        "type":"image",
        "url":"t-6.png"
    },
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"add-1_png",
        "type":"image",
        "url":"add-1.png"
    },
    {
        "name":"add-2_png",
        "type":"image",
        "url":"add-2.png"
    },
    {
        "name":"banner-t_png",
        "type":"image",
        "url":"banner-t.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"buy-btn_png",
        "type":"image",
        "url":"buy-btn.png"
    },
    {
        "name":"buy-btn-2_png",
        "type":"image",
        "url":"buy-btn-2.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"dis-1_png",
        "type":"image",
        "url":"dis-1.png"
    },
    {
        "name":"dis-2_png",
        "type":"image",
        "url":"dis-2.png"
    },
    {
        "name":"dis-3_png",
        "type":"image",
        "url":"dis-3.png"
    },
    {
        "name":"dis-4_png",
        "type":"image",
        "url":"dis-4.png"
    },
    {
        "name":"dis-5_png",
        "type":"image",
        "url":"dis-5.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"hy-title-3_png",
        "type":"image",
        "url":"hy-title-3.png"
    },
    {
        "name":"icon-1_png",
        "type":"image",
        "url":"icon-1.png"
    },
    {
        "name":"icon-1-h_png",
        "type":"image",
        "url":"icon-1-h.png"
    },
    {
        "name":"icon-2_png",
        "type":"image",
        "url":"icon-2.png"
    },
    {
        "name":"libao_png",
        "type":"image",
        "url":"libao.png"
    },
    {
        "name":"libao-1_jpg",
        "type":"image",
        "url":"libao-1.jpg"
    },
    {
        "name":"libao-2_jpg",
        "type":"image",
        "url":"libao-2.jpg"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"reduce-1_png",
        "type":"image",
        "url":"reduce-1.png"
    },
    {
        "name":"reduce-2_png",
        "type":"image",
        "url":"reduce-2.png"
    },
    {
        "name":"beijing-libao-1_jpg",
        "type":"image",
        "url":"beijing-libao-1.jpg"
    },
    {
        "name":"beijing-libao-2_jpg",
        "type":"image",
        "url":"beijing-libao-2.jpg"
    }

];