var resData = [
    {
        "name":"more1_png",
        "type":"image",
        "url":"more1.png"
    },
    {
        "name":"more-1_png",
        "type":"image",
        "url":"more-1.png"
    },
    {
        "name":"more2_png",
        "type":"image",
        "url":"more2.png"
    },
    {
        "name":"more-2_png",
        "type":"image",
        "url":"more-2.png"
    },
    {
        "name":"s1-bg_jpg",
        "type":"image",
        "url":"s1-bg.jpg"
    },
    {
        "name":"s3-bg_jpg",
        "type":"image",
        "url":"s3-bg.jpg"
    },
    {
        "name":"s6-bg_jpg",
        "type":"image",
        "url":"s6-bg.jpg"
    },
    {
        "name":"w-1_png",
        "type":"image",
        "url":"w-1.png"
    },
    {
        "name":"w-2_png",
        "type":"image",
        "url":"w-2.png"
    },
    {
        "name":"w-3_png",
        "type":"image",
        "url":"w-3.png"
    },
    {
        "name":"banner-cake_png",
        "type":"image",
        "url":"banner-cake.png"
    },
    {
        "name":"banner-cf_png",
        "type":"image",
        "url":"banner-cf.png"
    },
    {
        "name":"banner-girl_png",
        "type":"image",
        "url":"banner-girl.png"
    },
    {
        "name":"banner-title_png",
        "type":"image",
        "url":"banner-title.png"
    },
    {
        "name":"banner-w_png",
        "type":"image",
        "url":"banner-w.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"girl_png",
        "type":"image",
        "url":"girl.png"
    },
    {
        "name":"hongmei_png",
        "type":"image",
        "url":"hongmei.png"
    },
    {
        "name":"in-l_png",
        "type":"image",
        "url":"in-l.png"
    },
    {
        "name":"in-r_png",
        "type":"image",
        "url":"in-r.png"
    },
    {
        "name":"lanmei_png",
        "type":"image",
        "url":"lanmei.png"
    }
];