var resData = [
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"foot-bg_jpg",
        "type":"image",
        "url":"foot-bg.jpg"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"reduce-2_png",
        "type":"image",
        "url":"reduce-2.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"add-2_png",
        "type":"image",
        "url":"add-2.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    }
];