var resData = [
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bread-2_png",
        "type":"image",
        "url":"bread-2.png"
    },
    {
        "name":"bread-slide-1_png",
        "type":"image",
        "url":"bread-slide-1.png"
    },
    {
        "name":"bread-slide-2_png",
        "type":"image",
        "url":"bread-slide-2.png"
    },
    {
        "name":"bread-slide-3_png",
        "type":"image",
        "url":"bread-slide-3.png"
    },
    {
        "name":"bread-slide-4_png",
        "type":"image",
        "url":"bread-slide-4.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"cart_png",
        "type":"image",
        "url":"cart.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"in-bg_png",
        "type":"image",
        "url":"in-bg.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    }
];