var resData = [
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"txt_png",
        "type":"image",
        "url":"txt.png"
    },
    {
        "name":"choujiang_png",
        "type":"image",
        "url":"choujiang.png"
    },
    {
        "name":"choujiang-btn_png",
        "type":"image",
        "url":"choujiang-btn.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"jiang-1_png",
        "type":"image",
        "url":"jiang-1.png"
    },
    {
        "name":"jiang-1-on_png",
        "type":"image",
        "url":"jiang-1-on.png"
    },
    {
        "name":"jiang-2_png",
        "type":"image",
        "url":"jiang-2.png"
    },
    {
        "name":"jiang-2-on_png",
        "type":"image",
        "url":"jiang-2-on.png"
    },
    {
        "name":"jiang-3_png",
        "type":"image",
        "url":"jiang-3.png"
    },
    {
        "name":"jiang-3-on_png",
        "type":"image",
        "url":"jiang-3-on.png"
    },
    {
        "name":"jiang-4_png",
        "type":"image",
        "url":"jiang-4.png"
    },
    {
        "name":"jiang-4-on_png",
        "type":"image",
        "url":"jiang-4-on.png"
    },
    {
        "name":"jiang-5_png",
        "type":"image",
        "url":"jiang-5.png"
    },
    {
        "name":"jiang-5-on_png",
        "type":"image",
        "url":"jiang-5-on.png"
    },
    {
        "name":"jiang-6_png",
        "type":"image",
        "url":"jiang-6.png"
    },
    {
        "name":"jiang-6-on_png",
        "type":"image",
        "url":"jiang-6-on.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    }
];