var resData = [
    {
        "name":"shuangxiong_png",
        "type":"image",
        "url":"shuangxiong.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"carows_png",
        "type":"image",
        "url":"carows.png"
    },
    {
        "name":"line-1_png",
        "type":"image",
        "url":"line-1.png"
    },
    {
        "name":"price_png",
        "type":"image",
        "url":"price.png"
    },
    {
        "name":"price-1_png",
        "type":"image",
        "url":"price-1.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    }
];