var resData = [
	{
		"name":"bg_png",
		"type":"image",
		"url":"bg.png"
	},
	{
		"name":"btn-minus_png",
		"type":"image",
		"url":"btn-minus.png"
	},
	{
		"name":"btn-plus_png",
		"type":"image",
		"url":"btn-plus.png"
	},
	{
		"name":"icon-add_png",
		"type":"image",
		"url":"icon-add.png"
	},
	{
		"name":"p1-bg_png",
		"type":"image",
		"url":"p1-bg.png"
	},
	{
		"name":"p1-cheese_png",
		"type":"image",
		"url":"p1-cheese.png"
	},
	{
		"name":"p1-hand_png",
		"type":"image",
		"url":"p1-hand.png"
	},
	{
		"name":"p1-small_png",
		"type":"image",
		"url":"p1-small.png"
	},
	{
		"name":"p1-title_png",
		"type":"image",
		"url":"p1-title.png"
	},
	{
		"name":"p2-bg_png",
		"type":"image",
		"url":"p2-bg.png"
	},
	{
		"name":"p2-code_png",
		"type":"image",
		"url":"p2-code.png"
	},
	{
		"name":"p2-puren_png",
		"type":"image",
		"url":"p2-puren.png"
	},
	{
		"name":"p2-text_png",
		"type":"image",
		"url":"p2-text.png"
	},
	{
		"name":"p3-bg_png",
		"type":"image",
		"url":"p3-bg.png"
	},
	{
		"name":"p3-buy_png",
		"type":"image",
		"url":"p3-buy.png"
	},
	{
		"name":"p3-cat_png",
		"type":"image",
		"url":"p3-cat.png"
	},
	{
		"name":"p3-cheese_png",
		"type":"image",
		"url":"p3-cheese.png"
	},
	{
		"name":"p3-cream_png",
		"type":"image",
		"url":"p3-cream.png"
	},
	{
		"name":"p3-mony_png",
		"type":"image",
		"url":"p3-mony.png"
	},
	{
		"name":"p3-num_png",
		"type":"image",
		"url":"p3-num.png"
	},
	{
		"name":"p3-text_png",
		"type":"image",
		"url":"p3-text.png"
	},
	{
		"name":"p5-buy_png",
		"type":"image",
		"url":"p5-buy.png"
	},
	{
		"name":"p5-cheese_png",
		"type":"image",
		"url":"p5-cheese.png"
	},
	{
		"name":"p5-frame_png",
		"type":"image",
		"url":"p5-frame.png"
	},
	{
		"name":"p5-moneybg_png",
		"type":"image",
		"url":"p5-moneybg.png"
	},
	{
		"name":"p5-ricotta1_png",
		"type":"image",
		"url":"p5-ricotta1.png"
	},
	{
		"name":"p5-ricotta2_png",
		"type":"image",
		"url":"p5-ricotta2.png"
	},
	{
		"name":"p5-ricotta3_png",
		"type":"image",
		"url":"p5-ricotta3.png"
	},
	{
		"name":"p5-title_png",
		"type":"image",
		"url":"p5-title.png"
	},
	{
		"name":"rules_png",
		"type":"image",
		"url":"rules.png"
	},
	{
		"name":"cata_png",
		"type":"image",
		"url":"cata.png"
	},
	{
		"name":"catb_png",
		"type":"image",
		"url":"catb.png"
	},
	{
		"name":"catc_png",
		"type":"image",
		"url":"catc.png"
	},
	{
		"name":"catd_png",
		"type":"image",
		"url":"catd.png"
	},
	{
		"name":"cate_png",
		"type":"image",
		"url":"cate.png"
	}
];