var resData = [
    {
        "name":"pic-newyear_jpg",
        "type":"image",
        "url":"pic-newyear.jpg"
    },
    {
        "name":"pic-ps_jpg",
        "type":"image",
        "url":"pic-ps.jpg"
    },
    {
        "name":"plate_png",
        "type":"image",
        "url":"plate.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"text1893_png",
        "type":"image",
        "url":"text1893.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"top_pic_jpg",
        "type":"image",
        "url":"top_pic.jpg"
    },
    {
        "name":"top_pic_38_jpg",
        "type":"image",
        "url":"top_pic_38.jpg"
    },
    {
        "name":"top_pingan_png",
        "type":"image",
        "url":"top_pingan.png"
    },
    {
        "name":"top_quality_png",
        "type":"image",
        "url":"top_quality.png"
    },
    {
        "name":"tower1_png",
        "type":"image",
        "url":"tower1.png"
    },
    {
        "name":"tower2_png",
        "type":"image",
        "url":"tower2.png"
    },
    {
        "name":"word_qing_png",
        "type":"image",
        "url":"word_qing.png"
    },
    {
        "name":"word_shou_png",
        "type":"image",
        "url":"word_shou.png"
    },
    {
        "name":"word_yi_png",
        "type":"image",
        "url":"word_yi.png"
    },
    {
        "name":"act_ge_png",
        "type":"image",
        "url":"act_ge.png"
    },
    {
        "name":"act_sheng_png",
        "type":"image",
        "url":"act_sheng.png"
    },
    {
        "name":"act_text_png",
        "type":"image",
        "url":"act_text.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"logo_png",
        "type":"image",
        "url":"logo.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"note-38_png",
        "type":"image",
        "url":"note-38.png"
    },
    {
        "name":"note-520_png",
        "type":"image",
        "url":"note-520.png"
    },
    {
        "name":"note-christmasDay_png",
        "type":"image",
        "url":"note-christmasDay.png"
    },
    {
        "name":"note-lover_png",
        "type":"image",
        "url":"note-lover.png"
    },
    {
        "name":"note-mother_png",
        "type":"image",
        "url":"note-mother.png"
    },
    {
        "name":"note-newyear_png",
        "type":"image",
        "url":"note-newyear.png"
    },
    {
        "name":"note-ps_png",
        "type":"image",
        "url":"note-ps.png"
    },
    {
        "name":"pic01_jpg",
        "type":"image",
        "url":"pic01.jpg"
    },
    {
        "name":"pic-520_jpg",
        "type":"image",
        "url":"pic-520.jpg"
    },
    {
        "name":"pic-christmasDay_jpg",
        "type":"image",
        "url":"pic-christmasDay.jpg"
    },
    {
        "name":"pic-lover_jpg",
        "type":"image",
        "url":"pic-lover.jpg"
    },
    {
        "name":"pic-mother_jpg",
        "type":"image",
        "url":"pic-mother.jpg"
    }
];