var resData = [
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"star_png",
        "type":"image",
        "url":"star.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"wenda_png",
        "type":"image",
        "url":"wenda.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-img-1_png",
        "type":"image",
        "url":"cake-img-1.png"
    },
    {
        "name":"cake-img-2_png",
        "type":"image",
        "url":"cake-img-2.png"
    },
    {
        "name":"cake-img-3_png",
        "type":"image",
        "url":"cake-img-3.png"
    },
    {
        "name":"cake-title_png",
        "type":"image",
        "url":"cake-title.png"
    },
    {
        "name":"cake-tuijian_png",
        "type":"image",
        "url":"cake-tuijian.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"dis-1_png",
        "type":"image",
        "url":"dis-1.png"
    },
    {
        "name":"foot-bg_png",
        "type":"image",
        "url":"foot-bg.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    }
];