var resData = [
    {
        "name":"sec-foot_png",
        "type":"image",
        "url":"sec-foot.png"
    },
    {
        "name":"shengbang-txt-1_png",
        "type":"image",
        "url":"shengbang-txt-1.png"
    },
    {
        "name":"shengbang-txt-2_png",
        "type":"image",
        "url":"shengbang-txt-2.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"go-btn_png",
        "type":"image",
        "url":"go-btn.png"
    },
    {
        "name":"go-btn2_png",
        "type":"image",
        "url":"go-btn2.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"icon_20_png",
        "type":"image",
        "url":"icon_20.png"
    },
    {
        "name":"icon_40_png",
        "type":"image",
        "url":"icon_40.png"
    },
    {
        "name":"icon_60_png",
        "type":"image",
        "url":"icon_60.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"quan-1_png",
        "type":"image",
        "url":"quan-1.png"
    },
    {
        "name":"quan-2_png",
        "type":"image",
        "url":"quan-2.png"
    },
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-2_png",
        "type":"image",
        "url":"sec-2.png"
    }
];