var resData = [
    {
        "name":"more-hl_png",
        "type":"image",
        "url":"more-hl.png"
    },
    {
        "name":"sele-li_png",
        "type":"image",
        "url":"sele-li.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"zhekou_png",
        "type":"image",
        "url":"zhekou.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"ai-fathter_png",
        "type":"image",
        "url":"ai-fathter.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-bg-1_png",
        "type":"image",
        "url":"cake-bg-1.png"
    },
    {
        "name":"cake-bg-2_png",
        "type":"image",
        "url":"cake-bg-2.png"
    },
    {
        "name":"cake-bg-3_png",
        "type":"image",
        "url":"cake-bg-3.png"
    },
    {
        "name":"channel_289_9_jpg",
        "type":"image",
        "url":"channel_289_9.jpg"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"ewm_png",
        "type":"image",
        "url":"ewm.png"
    },
    {
        "name":"guize-bg_png",
        "type":"image",
        "url":"guize-bg.png"
    },
    {
        "name":"huangou_png",
        "type":"image",
        "url":"huangou.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"icon-1_png",
        "type":"image",
        "url":"icon-1.png"
    },
    {
        "name":"icon-1-h_png",
        "type":"image",
        "url":"icon-1-h.png"
    },
    {
        "name":"in-l_png",
        "type":"image",
        "url":"in-l.png"
    },
    {
        "name":"in-r_png",
        "type":"image",
        "url":"in-r.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    }
];