var resData = [
    {
        "name":"main-bg_png",
        "type":"image",
        "url":"main-bg.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"chl-brand_png",
        "type":"image",
        "url":"chl-brand.png"
    },
    {
        "name":"foot-bg_png",
        "type":"image",
        "url":"foot-bg.png"
    },
    {
        "name":"foot-top_png",
        "type":"image",
        "url":"foot-top.png"
    }

];