var resData = [
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"words-1_png",
        "type":"image",
        "url":"words-1.png"
    },
    {
        "name":"words-2_png",
        "type":"image",
        "url":"words-2.png"
    },
    {
        "name":"words-3_png",
        "type":"image",
        "url":"words-3.png"
    },
    {
        "name":"words-4_png",
        "type":"image",
        "url":"words-4.png"
    },
    {
        "name":"zhipai_png",
        "type":"image",
        "url":"zhipai.png"
    },
    {
        "name":"zs-1_png",
        "type":"image",
        "url":"zs-1.png"
    },
    {
        "name":"zs-2_png",
        "type":"image",
        "url":"zs-2.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cofei_png",
        "type":"image",
        "url":"cofei.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    }
];