var resData = [
    {
        "name":"code_png",
        "type":"image",
        "url":"code.png"
    },
    {
        "name":"family_png",
        "type":"image",
        "url":"family.png"
    },
    {
        "name":"gobuy_png",
        "type":"image",
        "url":"gobuy.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"gou-1-1_png",
        "type":"image",
        "url":"gou-1-1.png"
    },
    {
        "name":"gou-1-2_png",
        "type":"image",
        "url":"gou-1-2.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"icon-1_png",
        "type":"image",
        "url":"icon-1.png"
    },
    {
        "name":"icon-1-h_png",
        "type":"image",
        "url":"icon-1-h.png"
    },
    {
        "name":"line_jpg",
        "type":"image",
        "url":"line.jpg"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    },
    {
        "name":"s-bg_png",
        "type":"image",
        "url":"s-bg.png"
    },
    {
        "name":"shengbang_png",
        "type":"image",
        "url":"shengbang.png"
    },
    {
        "name":"shengbang-price_png",
        "type":"image",
        "url":"shengbang-price.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"xs_png",
        "type":"image",
        "url":"xs.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    }
];