var resData = [
    {
        "name":"cake-i-3_png",
        "type":"image",
        "url":"cake-i-3.png"
    },
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-foot_png",
        "type":"image",
        "url":"sec-foot.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-i-1_png",
        "type":"image",
        "url":"cake-i-1.png"
    },
    {
        "name":"cake-i-2_png",
        "type":"image",
        "url":"cake-i-2.png"
    }
];