var resData = [
    {
        "name":"buybtn-disable_png",
        "type":"image",
        "url":"lv2/buybtn-disable.png"
    },
    {
        "name":"buybtn_png",
        "type":"image",
        "url":"lv2/buybtn.png"
    },
    {
        "name":"ico_png",
        "type":"image",
        "url":"lv2/ico.png"
    },
    {
        "name":"icon_png",
        "type":"image",
        "url":"lv2/icon.png"
    },
    {
        "name":"img1_png",
        "type":"image",
        "url":"lv2/img1.png"
    },
    {
        "name":"img2_png",
        "type":"image",
        "url":"lv2/img2.png"
    },
    {
        "name":"price_png",
        "type":"image",
        "url":"lv2/price.png"
    },
    {
        "name":"product_png",
        "type":"image",
        "url":"lv2/product.png"
    },
    {
        "name":"scbg_jpg",
        "type":"image",
        "url":"lv2/scbg.jpg"
    },
    {
        "name":"text1_png",
        "type":"image",
        "url":"lv2/text1.png"
    },
    {
        "name":"text2_png",
        "type":"image",
        "url":"lv2/text2.png"
    },
    {
        "name":"f1_png",
        "type":"image",
        "url":"lv2/f1.png"
    },
    {
        "name":"f2_png",
        "type":"image",
        "url":"lv2/f2.png"
    },
    {
        "name":"f3_png",
        "type":"image",
        "url":"lv2/f3.png"
    },
    {
        "name":"f4_png",
        "type":"image",
        "url":"lv2/f4.png"
    },
    {
        "name":"f5_png",
        "type":"image",
        "url":"lv2/f5.png"
    },
    {
        "name":"f6_png",
        "type":"image",
        "url":"lv2/f6.png"
    },
    {
        "name":"f7_png",
        "type":"image",
        "url":"lv2/f7.png"
    },
    {
        "name":"f8_png",
        "type":"image",
        "url":"lv2/f8.png"
    },
    {
        "name":"f9_png",
        "type":"image",
        "url":"lv2/f9.png"
    },
    {
        "name":"f10_png",
        "type":"image",
        "url":"lv2/f10.png"
    },
    {
        "name":"f11_png",
        "type":"image",
        "url":"lv2/f11.png"
    },
    {
        "name":"f12_png",
        "type":"image",
        "url":"lv2/f12.png"
    }
];
var preData = [
    {
        "name":"loading-bg-left_jpg",
        "type":"image",
        "url":"lv2/loading-bg-left.jpg"
    },
    {
        "name":"loading-bg-right_jpg",
        "type":"image",
        "url":"lv2/loading-bg-right.jpg"
    },
    {
        "name":"sidai_png",
        "type":"image",
        "url":"lv2/sidai.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"lv2/title.png"
    },
    {
        "name":"mask_png",
        "type":"image",
        "url":"lv2/mask.png"
    }
];