var resData = [
    {
        "name":"arrow_png",
        "type":"image",
        "url":"arrow.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"btn_png",
        "type":"image",
        "url":"btn.png"
    },
    {
        "name":"flower_png",
        "type":"image",
        "url":"flower.png"
    },
    {
        "name":"img1_png",
        "type":"image",
        "url":"img1.png"
    },
    {
        "name":"img2_png",
        "type":"image",
        "url":"img2.png"
    },
    {
        "name":"img3_png",
        "type":"image",
        "url":"img3.png"
    },
    {
        "name":"model_png",
        "type":"image",
        "url":"model.png"
    },
    {
        "name":"price_png",
        "type":"image",
        "url":"price.png"
    },
    {
        "name":"text1_png",
        "type":"image",
        "url":"text1.png"
    },
    {
        "name":"text2_png",
        "type":"image",
        "url":"text2.png"
    },
    {
        "name":"text3_png",
        "type":"image",
        "url":"text3.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    }];