var resData = [
    {
        "name":"zhi_png",
        "type":"image",
        "url":"zhi.png"
    },
    {
        "name":"act_ge_png",
        "type":"image",
        "url":"act_ge.png"
    },
    {
        "name":"act_sheng_png",
        "type":"image",
        "url":"act_sheng.png"
    },
    {
        "name":"act-lihe_png",
        "type":"image",
        "url":"act-lihe.png"
    },
    {
        "name":"act-rules_png",
        "type":"image",
        "url":"act-rules.png"
    },
    {
        "name":"act-style_png",
        "type":"image",
        "url":"act-style.png"
    },
    {
        "name":"act-time_png",
        "type":"image",
        "url":"act-time.png"
    },
    {
        "name":"baner-box_png",
        "type":"image",
        "url":"baner-box.png"
    },
    {
        "name":"baner-cake_png",
        "type":"image",
        "url":"baner-cake.png"
    },
    {
        "name":"baner-ren_png",
        "type":"image",
        "url":"baner-ren.png"
    },
    {
        "name":"baner-title_png",
        "type":"image",
        "url":"baner-title.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"box-title_png",
        "type":"image",
        "url":"box-title.png"
    },
    {
        "name":"btn-add_png",
        "type":"image",
        "url":"btn-add.png"
    },
    {
        "name":"btn-minus_png",
        "type":"image",
        "url":"btn-minus.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"libox_png",
        "type":"image",
        "url":"libox.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"plate_png",
        "type":"image",
        "url":"plate.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    }
];