var resData = [
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"supi_png",
        "type":"image",
        "url":"supi.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"tuzi_png",
        "type":"image",
        "url":"tuzi.png"
    },
    {
        "name":"youhui_png",
        "type":"image",
        "url":"youhui.png"
    },
    {
        "name":"0_png",
        "type":"image",
        "url":"0.png"
    },
    {
        "name":"1_png",
        "type":"image",
        "url":"1.png"
    },
    {
        "name":"2_png",
        "type":"image",
        "url":"2.png"
    },
    {
        "name":"3_png",
        "type":"image",
        "url":"3.png"
    },
    {
        "name":"4_png",
        "type":"image",
        "url":"4.png"
    },
    {
        "name":"5_png",
        "type":"image",
        "url":"5.png"
    },
    {
        "name":"6_png",
        "type":"image",
        "url":"6.png"
    },
    {
        "name":"7_png",
        "type":"image",
        "url":"7.png"
    },
    {
        "name":"8_png",
        "type":"image",
        "url":"8.png"
    },
    {
        "name":"9_png",
        "type":"image",
        "url":"9.png"
    },
    {
        "name":"baner-bg_jpg",
        "type":"image",
        "url":"baner-bg.jpg"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"checkbox_png",
        "type":"image",
        "url":"checkbox.png"
    },
    {
        "name":"cloul-1_png",
        "type":"image",
        "url":"cloul-1.png"
    },
    {
        "name":"cloul-2_png",
        "type":"image",
        "url":"cloul-2.png"
    },
    {
        "name":"cloul-3_png",
        "type":"image",
        "url":"cloul-3.png"
    },
    {
        "name":"cloul-4_png",
        "type":"image",
        "url":"cloul-4.png"
    },
    {
        "name":"counter-bg_png",
        "type":"image",
        "url":"counter-bg.png"
    },
    {
        "name":"counter-bg2_png",
        "type":"image",
        "url":"counter-bg2.png"
    },
    {
        "name":"line_jpg",
        "type":"image",
        "url":"line.jpg"
    },
    {
        "name":"lobo_png",
        "type":"image",
        "url":"lobo.png"
    },
    {
        "name":"logo_png",
        "type":"image",
        "url":"logo.png"
    },
    {
        "name":"main-bg_jpg",
        "type":"image",
        "url":"main-bg.jpg"
    }
];