var resData = [
    {
        "name":"quan-2_png",
        "type":"image",
        "url":"quan-2.png"
    },
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-2_png",
        "type":"image",
        "url":"sec-2.png"
    },
    {
        "name":"sec-3_png",
        "type":"image",
        "url":"sec-3.png"
    },
    {
        "name":"sec-foot_png",
        "type":"image",
        "url":"sec-foot.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"get-packet_png",
        "type":"image",
        "url":"get-packet.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"hy-title-3_png",
        "type":"image",
        "url":"hy-title-3.png"
    },
    {
        "name":"hy-title-4_png",
        "type":"image",
        "url":"hy-title-4.png"
    },
    {
        "name":"icon_49.5_png",
        "type":"image",
        "url":"icon_49.5.png"
    },
    {
        "name":"icon_74.5_png",
        "type":"image",
        "url":"icon_74.5.png"
    },
    {
        "name":"icon_99.5_png",
        "type":"image",
        "url":"icon_99.5.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    }
];