var resData = [
    {
        "name":"icon-4_png",
        "type":"image",
        "url":"icon-4.png"
    },
    {
        "name":"icon-5_png",
        "type":"image",
        "url":"icon-5.png"
    },
    {
        "name":"icon-5-h_png",
        "type":"image",
        "url":"icon-5-h.png"
    },
    {
        "name":"result-main_png",
        "type":"image",
        "url":"result-main.png"
    },
    {
        "name":"result-top_png",
        "type":"image",
        "url":"result-top.png"
    },
    {
        "name":"icon-0_png",
        "type":"image",
        "url":"icon-0.png"
    },
    {
        "name":"icon-0-h_png",
        "type":"image",
        "url":"icon-0-h.png"
    },
    {
        "name":"icon-1_png",
        "type":"image",
        "url":"icon-1.png"
    },
    {
        "name":"icon-1-h_png",
        "type":"image",
        "url":"icon-1-h.png"
    },
    {
        "name":"icon-2_png",
        "type":"image",
        "url":"icon-2.png"
    },
    {
        "name":"icon-2-h_png",
        "type":"image",
        "url":"icon-2-h.png"
    },
    {
        "name":"icon-3_png",
        "type":"image",
        "url":"icon-3.png"
    },
    {
        "name":"icon-3-h_png",
        "type":"image",
        "url":"icon-3-h.png"
    }
];