var resData = [
  {
    "name":"sub-title_png",
    "type":"image",
    "url":"sub-title.png"
  },
  {
    "name":"s1-1_jpg",
    "type":"image",
    "url":"s1-1.jpg"
  },
  {
    "name":"s1-2_jpg",
    "type":"image",
    "url":"s1-2.jpg"
  },
  {
    "name":"s1-3_jpg",
    "type":"image",
    "url":"s1-3.jpg"
  },
  {
    "name":"s2-1_jpg",
    "type":"image",
    "url":"s2-1.jpg"
  },
  {
    "name":"s2-2_jpg",
    "type":"image",
    "url":"s2-2.jpg"
  },
  {
    "name":"s2-text_png",
    "type":"image",
    "url":"s2-text.png"
  },
  {
    "name":"s3-1_jpg",
    "type":"image",
    "url":"s3-1.jpg"
  },
  {
    "name":"s3-2_jpg",
    "type":"image",
    "url":"s3-2.jpg"
  },
  {
    "name":"s3-text_png",
    "type":"image",
    "url":"s3-text.png"
  }];