var resData = [
    {
        "name":"icon-phone_png",
        "type":"image",
        "url":"icon-phone.png"
    },
    {
        "name":"quan-bao-gif_png",
        "type":"image",
        "url":"quan-bao-gif.png"
    },
    {
        "name":"quan-bao-shou_png",
        "type":"image",
        "url":"quan-bao-shou.png"
    },
    {
        "name":"yhq-icon_png",
        "type":"image",
        "url":"yhq-icon.png"
    },
    {
        "name":"youhui_png",
        "type":"image",
        "url":"youhui.png"
    },
    {
        "name":"b-btn-1_png",
        "type":"image",
        "url":"b-btn-1.png"
    },
    {
        "name":"b-cake-1_png",
        "type":"image",
        "url":"b-cake-1.png"
    },
    {
        "name":"b-cake-2_png",
        "type":"image",
        "url":"b-cake-2.png"
    },
    {
        "name":"b-des-1_png",
        "type":"image",
        "url":"b-des-1.png"
    },
    {
        "name":"b-des-2_png",
        "type":"image",
        "url":"b-des-2.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"b-words-1_png",
        "type":"image",
        "url":"b-words-1.png"
    },
    {
        "name":"b-words-2_png",
        "type":"image",
        "url":"b-words-2.png"
    }
];