var resData = [
    {
        "name":"xinfeng-1_png",
        "type":"image",
        "url":"xinfeng-1.png"
    },
    {
        "name":"xinfeng-2_png",
        "type":"image",
        "url":"xinfeng-2.png"
    },
    {
        "name":"xinfeng-3_png",
        "type":"image",
        "url":"xinfeng-3.png"
    },
    {
        "name":"border_png",
        "type":"image",
        "url":"border.png"
    },
    {
        "name":"btn-go_png",
        "type":"image",
        "url":"btn-go.png"
    },
    {
        "name":"btn-yong_png",
        "type":"image",
        "url":"btn-yong.png"
    },
    {
        "name":"i-yuan_png",
        "type":"image",
        "url":"i-yuan.png"
    },
    {
        "name":"logo_png",
        "type":"image",
        "url":"logo.png"
    },
    {
        "name":"pic_png",
        "type":"image",
        "url":"pic.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    }
];