var resData = [
    {
        "name":"sec1-bg_png",
        "type":"image",
        "url":"sec1-bg.png"
    },
    {
        "name":"word-1_png",
        "type":"image",
        "url":"word-1.png"
    },
    {
        "name":"word-2_png",
        "type":"image",
        "url":"word-2.png"
    },
    {
        "name":"1893_png",
        "type":"image",
        "url":"1893.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"buy-btn_png",
        "type":"image",
        "url":"buy-btn.png"
    },
    {
        "name":"cake-bg_png",
        "type":"image",
        "url":"cake-bg.png"
    },
    {
        "name":"cake-nino_png",
        "type":"image",
        "url":"cake-nino.png"
    },
    {
        "name":"cake-xm_png",
        "type":"image",
        "url":"cake-xm.png"
    },
    {
        "name":"img-1_03_jpg",
        "type":"image",
        "url":"img-1_03.jpg"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"light_png",
        "type":"image",
        "url":"light.png"
    },
    {
        "name":"light-1_png",
        "type":"image",
        "url":"light-1.png"
    },
    {
        "name":"line-1_png",
        "type":"image",
        "url":"line-1.png"
    },
    {
        "name":"line-2_png",
        "type":"image",
        "url":"line-2.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"party_png",
        "type":"image",
        "url":"party.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    }
];