var resData = [
    {
        "name":"price_png",
        "type":"image",
        "url":"price.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"word_png",
        "type":"image",
        "url":"word.png"
    },
    {
        "name":"zuhe-1_png",
        "type":"image",
        "url":"zuhe-1.png"
    },
    {
        "name":"zuhe-2_png",
        "type":"image",
        "url":"zuhe-2.png"
    },
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    },
    {
        "name":"logo_png",
        "type":"image",
        "url":"logo.png"
    },
    {
        "name":"mingsheng-1_png",
        "type":"image",
        "url":"mingsheng-1.png"
    },
    {
        "name":"mingsheng-2_png",
        "type":"image",
        "url":"mingsheng-2.png"
    }
];