var resData = [
    {
        "name":"reduce-6_png",
        "type":"image",
        "url":"reduce-6.png"
    },
    {
        "name":"sele-li_png",
        "type":"image",
        "url":"sele-li.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"t-5_png",
        "type":"image",
        "url":"t-5.png"
    },
    {
        "name":"t-6_png",
        "type":"image",
        "url":"t-6.png"
    },
    {
        "name":"tips_png",
        "type":"image",
        "url":"tips.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"wap-banner_jpg",
        "type":"image",
        "url":"wap-banner.jpg"
    },
    {
        "name":"xst-1_png",
        "type":"image",
        "url":"xst-1.png"
    },
    {
        "name":"xst-2_png",
        "type":"image",
        "url":"xst-2.png"
    },
    {
        "name":"xst-3_png",
        "type":"image",
        "url":"xst-3.png"
    },
    {
        "name":"xst-4_png",
        "type":"image",
        "url":"xst-4.png"
    },
    {
        "name":"xst-5_png",
        "type":"image",
        "url":"xst-5.png"
    },
    {
        "name":"xst-6_png",
        "type":"image",
        "url":"xst-6.png"
    },
    {
        "name":"xst-7_png",
        "type":"image",
        "url":"xst-7.png"
    },
    {
        "name":"xst-8_png",
        "type":"image",
        "url":"xst-8.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"add-1_png",
        "type":"image",
        "url":"add-1.png"
    },
    {
        "name":"add-2_png",
        "type":"image",
        "url":"add-2.png"
    },
    {
        "name":"add-3_png",
        "type":"image",
        "url":"add-3.png"
    },
    {
        "name":"add-4_png",
        "type":"image",
        "url":"add-4.png"
    },
    {
        "name":"add-5_png",
        "type":"image",
        "url":"add-5.png"
    },
    {
        "name":"add-6_png",
        "type":"image",
        "url":"add-6.png"
    },
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"banner-title_png",
        "type":"image",
        "url":"banner-title.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"bj-banner_jpg",
        "type":"image",
        "url":"bj-banner.jpg"
    },
    {
        "name":"bj-cake-6_png",
        "type":"image",
        "url":"bj-cake-6.png"
    },
    {
        "name":"bj-quanyi_png",
        "type":"image",
        "url":"bj-quanyi.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"cake-5_png",
        "type":"image",
        "url":"cake-5.png"
    },
    {
        "name":"cake-6_png",
        "type":"image",
        "url":"cake-6.png"
    },
    {
        "name":"disc-1_png",
        "type":"image",
        "url":"disc-1.png"
    },
    {
        "name":"go-buy_png",
        "type":"image",
        "url":"go-buy.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"hy-title-3_png",
        "type":"image",
        "url":"hy-title-3.png"
    },
    {
        "name":"icon_png",
        "type":"image",
        "url":"icon.png"
    },
    {
        "name":"icon-1_png",
        "type":"image",
        "url":"icon-1.png"
    },
    {
        "name":"icon-1-h_png",
        "type":"image",
        "url":"icon-1-h.png"
    },
    {
        "name":"icon-2_png",
        "type":"image",
        "url":"icon-2.png"
    },
    {
        "name":"icon-2-h_png",
        "type":"image",
        "url":"icon-2-h.png"
    },
    {
        "name":"icon-3_png",
        "type":"image",
        "url":"icon-3.png"
    },
    {
        "name":"icon-3-h_png",
        "type":"image",
        "url":"icon-3-h.png"
    },
    {
        "name":"icon-4_png",
        "type":"image",
        "url":"icon-4.png"
    },
    {
        "name":"icon-4-h_png",
        "type":"image",
        "url":"icon-4-h.png"
    },
    {
        "name":"icon-5_png",
        "type":"image",
        "url":"icon-5.png"
    },
    {
        "name":"icon-5-h_png",
        "type":"image",
        "url":"icon-5-h.png"
    },
    {
        "name":"icon-6_png",
        "type":"image",
        "url":"icon-6.png"
    },
    {
        "name":"icon-6-h_png",
        "type":"image",
        "url":"icon-6-h.png"
    },
    {
        "name":"in-l_png",
        "type":"image",
        "url":"in-l.png"
    },
    {
        "name":"in-r_png",
        "type":"image",
        "url":"in-r.png"
    },
    {
        "name":"kouhong_png",
        "type":"image",
        "url":"kouhong.png"
    },
    {
        "name":"kouhong-over_png",
        "type":"image",
        "url":"kouhong-over.png"
    },
    {
        "name":"main-bg-2_png",
        "type":"image",
        "url":"main-bg-2.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"quanyi_png",
        "type":"image",
        "url":"quanyi.png"
    },
    {
        "name":"quanyi-title_png",
        "type":"image",
        "url":"quanyi-title.png"
    },
    {
        "name":"reduce-1_png",
        "type":"image",
        "url":"reduce-1.png"
    },
    {
        "name":"reduce-2_png",
        "type":"image",
        "url":"reduce-2.png"
    },
    {
        "name":"reduce-3_png",
        "type":"image",
        "url":"reduce-3.png"
    },
    {
        "name":"reduce-4_png",
        "type":"image",
        "url":"reduce-4.png"
    },
    {
        "name":"reduce-5_png",
        "type":"image",
        "url":"reduce-5.png"
    }
];