var resData = [
  {
    "name":"sec2-bg_png",
    "type":"image",
    "url":"sec2-bg.png"
  },
  {
    "name":"banner_png",
    "type":"image",
    "url":"sec1/banner.png"
  },
  {
    "name":"price-266_png",
    "type":"image",
    "url":"sec1/price-266.png"
  },
  {
    "name":"price-366_png",
    "type":"image",
    "url":"sec1/price-366.png"
  },
  {
    "name":"price-506_png",
    "type":"image",
    "url":"sec1/price-506.png"
  },
  {
    "name":"price-798_png",
    "type":"image",
    "url":"sec1/price-798.png"
  },
  {
    "name":"sec2-p1-text_png",
    "type":"image",
    "url":"sec1/sec2-p1-text.png"
  },
  {
    "name":"sec2-p1_png",
    "type":"image",
    "url":"sec1/sec2-p1.png"
  },
  {
    "name":"sec2-p2-text_png",
    "type":"image",
    "url":"sec1/sec2-p2-text.png"
  },
  {
    "name":"sec2-p2_png",
    "type":"image",
    "url":"sec1/sec2-p2.png"
  },
  {
    "name":"sec2-p3-text_png",
    "type":"image",
    "url":"sec1/sec2-p3-text.png"
  },
  {
    "name":"sec2-p3_png",
    "type":"image",
    "url":"sec1/sec2-p3.png"
  },
  {
    "name":"sec2-price_png",
    "type":"image",
    "url":"sec1/sec2-price.png"
  },
  {
    "name":"select-text_png",
    "type":"image",
    "url":"sec1/select-text.png"
  },
  {
    "name":"border-img_png",
    "type":"image",
    "url":"border-img.png"
  },
  {
    "name":"border-img2_png",
    "type":"image",
    "url":"border-img2.png"
  },
  {
    "name":"buy-btn_png",
    "type":"image",
    "url":"buy-btn.png"
  },
  {
    "name":"sec1-bg_jpg",
    "type":"image",
    "url":"sec1-bg.jpg"
  },
  {
    "name":"float_icon_png",
    "type":"image",
    "url":"sec1/float_icon.png"
  }];