var resData = [
    {
        "name":"quan-2_png",
        "type":"image",
        "url":"quan-2.png"
    },
    {
        "name":"quan-3_png",
        "type":"image",
        "url":"quan-3.png"
    },
    {
        "name":"time-bar_png",
        "type":"image",
        "url":"time-bar.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"wx-code_png",
        "type":"image",
        "url":"wx-code.png"
    },
    {
        "name":"xp_png",
        "type":"image",
        "url":"xp.png"
    },
    {
        "name":"xp-img_png",
        "type":"image",
        "url":"xp-img.png"
    },
    {
        "name":"zn-title-1_png",
        "type":"image",
        "url":"zn-title-1.png"
    },
    {
        "name":"zn-title-2_png",
        "type":"image",
        "url":"zn-title-2.png"
    },
    {
        "name":"zn-title-3_png",
        "type":"image",
        "url":"zn-title-3.png"
    },
    {
        "name":"zn-title-4_png",
        "type":"image",
        "url":"zn-title-4.png"
    },
    {
        "name":"zn-title-5_png",
        "type":"image",
        "url":"zn-title-5.png"
    },
    {
        "name":"zn-title-6_png",
        "type":"image",
        "url":"zn-title-6.png"
    },
    {
        "name":"zn-title-7_png",
        "type":"image",
        "url":"zn-title-7.png"
    },
    {
        "name":"zn-title-8_png",
        "type":"image",
        "url":"zn-title-8.png"
    },
    {
        "name":"zp-1_png",
        "type":"image",
        "url":"zp-1.png"
    },
    {
        "name":"zp-2_png",
        "type":"image",
        "url":"zp-2.png"
    },
    {
        "name":"zp-3_png",
        "type":"image",
        "url":"zp-3.png"
    },
    {
        "name":"zp-4_png",
        "type":"image",
        "url":"zp-4.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"buy-card_png",
        "type":"image",
        "url":"buy-card.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"car_png",
        "type":"image",
        "url":"car.png"
    },
    {
        "name":"car-on_png",
        "type":"image",
        "url":"car-on.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"dot_png",
        "type":"image",
        "url":"dot.png"
    },
    {
        "name":"go-buy-1_png",
        "type":"image",
        "url":"go-buy-1.png"
    },
    {
        "name":"go-buy-2_png",
        "type":"image",
        "url":"go-buy-2.png"
    },
    {
        "name":"go-buy-3_png",
        "type":"image",
        "url":"go-buy-3.png"
    },
    {
        "name":"gou-1-1_png",
        "type":"image",
        "url":"gou-1-1.png"
    },
    {
        "name":"gou-1-2_png",
        "type":"image",
        "url":"gou-1-2.png"
    },
    {
        "name":"gou-2_png",
        "type":"image",
        "url":"gou-2.png"
    },
    {
        "name":"gou-2-1_png",
        "type":"image",
        "url":"gou-2-1.png"
    },
    {
        "name":"gou-2-2_png",
        "type":"image",
        "url":"gou-2-2.png"
    },
    {
        "name":"gou-3-1_png",
        "type":"image",
        "url":"gou-3-1.png"
    },
    {
        "name":"gou-3-2_png",
        "type":"image",
        "url":"gou-3-2.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"img-4_png",
        "type":"image",
        "url":"img-4.png"
    },
    {
        "name":"img-5_png",
        "type":"image",
        "url":"img-5.png"
    },
    {
        "name":"img-6_png",
        "type":"image",
        "url":"img-6.png"
    },
    {
        "name":"img-7_png",
        "type":"image",
        "url":"img-7.png"
    },
    {
        "name":"img-8_png",
        "type":"image",
        "url":"img-8.png"
    },
    {
        "name":"kanjia_png",
        "type":"image",
        "url":"kanjia.png"
    },
    {
        "name":"manzeng_png",
        "type":"image",
        "url":"manzeng.png"
    },
    {
        "name":"manzeng-1_png",
        "type":"image",
        "url":"manzeng-1.png"
    },
    {
        "name":"mcard_png",
        "type":"image",
        "url":"mcard.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"part-b-1_png",
        "type":"image",
        "url":"part-b-1.png"
    },
    {
        "name":"part-b-2_png",
        "type":"image",
        "url":"part-b-2.png"
    },
    {
        "name":"part-b-3_png",
        "type":"image",
        "url":"part-b-3.png"
    },
    {
        "name":"part-b-4_png",
        "type":"image",
        "url":"part-b-4.png"
    },
    {
        "name":"part-c-1_png",
        "type":"image",
        "url":"part-c-1.png"
    },
    {
        "name":"part-c-2_png",
        "type":"image",
        "url":"part-c-2.png"
    },
    {
        "name":"part-c-3_png",
        "type":"image",
        "url":"part-c-3.png"
    },
    {
        "name":"part-t-1_png",
        "type":"image",
        "url":"part-t-1.png"
    },
    {
        "name":"part-t-2_png",
        "type":"image",
        "url":"part-t-2.png"
    },
    {
        "name":"part-t-3_png",
        "type":"image",
        "url":"part-t-3.png"
    },
    {
        "name":"part-t-4_png",
        "type":"image",
        "url":"part-t-4.png"
    },
    {
        "name":"part-t-5_png",
        "type":"image",
        "url":"part-t-5.png"
    },
    {
        "name":"price-1_png",
        "type":"image",
        "url":"price-1.png"
    },
    {
        "name":"price-2_png",
        "type":"image",
        "url":"price-2.png"
    },
    {
        "name":"price-3_png",
        "type":"image",
        "url":"price-3.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"quan-1_png",
        "type":"image",
        "url":"quan-1.png"
    }
];