var resData = [
    {
        "name":"w-buy_png",
        "type":"image",
        "url":"w-buy.png"
    },
    {
        "name":"w-cake_png",
        "type":"image",
        "url":"w-cake.png"
    },
    {
        "name":"w-cake1_png",
        "type":"image",
        "url":"w-cake1.png"
    },
    {
        "name":"w-dhua_png",
        "type":"image",
        "url":"w-dhua.png"
    },
    {
        "name":"w-m-baner_jpg",
        "type":"image",
        "url":"w-m-baner.jpg"
    },
    {
        "name":"w-title_png",
        "type":"image",
        "url":"w-title.png"
    },
    {
        "name":"w-zh_png",
        "type":"image",
        "url":"w-zh.png"
    },
    {
        "name":"w-zs_png",
        "type":"image",
        "url":"w-zs.png"
    },
    {
        "name":"w-zsong_png",
        "type":"image",
        "url":"w-zsong.png"
    },
    {
        "name":"bj_jpg",
        "type":"image",
        "url":"bj.jpg"
    },
    {
        "name":"buy-btn_png",
        "type":"image",
        "url":"buy-btn.png"
    },
    {
        "name":"buy-btn2_png",
        "type":"image",
        "url":"buy-btn2.png"
    }
];