var resData = [
    {
        "name":"words-1_png",
        "type":"image",
        "url":"words-1.png"
    },
    {
        "name":"words-2_png",
        "type":"image",
        "url":"words-2.png"
    },
    {
        "name":"words-3_png",
        "type":"image",
        "url":"words-3.png"
    },
    {
        "name":"words-4_png",
        "type":"image",
        "url":"words-4.png"
    },
    {
        "name":"yueyuan_png",
        "type":"image",
        "url":"yueyuan.png"
    },
    {
        "name":"banner-815_png",
        "type":"image",
        "url":"banner-815.png"
    },
    {
        "name":"banner-box_png",
        "type":"image",
        "url":"banner-box.png"
    },
    {
        "name":"banner-c-2_png",
        "type":"image",
        "url":"banner-c-2.png"
    },
    {
        "name":"banner-c-3_png",
        "type":"image",
        "url":"banner-c-3.png"
    },
    {
        "name":"banner-c-5_png",
        "type":"image",
        "url":"banner-c-5.png"
    },
    {
        "name":"banner-moon_png",
        "type":"image",
        "url":"banner-moon.png"
    },
    {
        "name":"banner-s1_png",
        "type":"image",
        "url":"banner-s1.png"
    },
    {
        "name":"banner-title_png",
        "type":"image",
        "url":"banner-title.png"
    },
    {
        "name":"box-bg_png",
        "type":"image",
        "url":"box-bg.png"
    },
    {
        "name":"box-in_png",
        "type":"image",
        "url":"box-in.png"
    },
    {
        "name":"box-out_png",
        "type":"image",
        "url":"box-out.png"
    },
    {
        "name":"cake-pic-1_png",
        "type":"image",
        "url":"cake-pic-1.png"
    },
    {
        "name":"cake-pic-2_png",
        "type":"image",
        "url":"cake-pic-2.png"
    },
    {
        "name":"cake-pic-3_png",
        "type":"image",
        "url":"cake-pic-3.png"
    },
    {
        "name":"cake-pic-4_png",
        "type":"image",
        "url":"cake-pic-4.png"
    },
    {
        "name":"dis-1_png",
        "type":"image",
        "url":"dis-1.png"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    }
];