var resData = [
    {
        "name":"s-sction-2-bg_jpg",
        "type":"image",
        "url":"s-sction-2-bg.jpg"
    },
    {
        "name":"s-sction-4_png",
        "type":"image",
        "url":"s-sction-4.png"
    },
    {
        "name":"s-sction-5_png",
        "type":"image",
        "url":"s-sction-5.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"by-btn_png",
        "type":"image",
        "url":"by-btn.png"
    },
    {
        "name":"more-bg_png",
        "type":"image",
        "url":"more-bg.png"
    },
    {
        "name":"section-3-title_png",
        "type":"image",
        "url":"section-3-title.png"
    },
    {
        "name":"s-sction-1_png",
        "type":"image",
        "url":"s-sction-1.png"
    },
    {
        "name":"s-sction-2_png",
        "type":"image",
        "url":"s-sction-2.png"
    }

];