var resData = [
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"icon-xs_png",
        "type":"image",
        "url":"icon-xs.png"
    },
    {
        "name":"in-l_png",
        "type":"image",
        "url":"in-l.png"
    },
    {
        "name":"in-r_png",
        "type":"image",
        "url":"in-r.png"
    },
    {
        "name":"qkl-1_png",
        "type":"image",
        "url":"qkl-1.png"
    },
    {
        "name":"qkl-2_png",
        "type":"image",
        "url":"qkl-2.png"
    },
    {
        "name":"rose_png",
        "type":"image",
        "url":"rose.png"
    },
    {
        "name":"sw1-next_png",
        "type":"image",
        "url":"sw1-next.png"
    },
    {
        "name":"sw1-prev_png",
        "type":"image",
        "url":"sw1-prev.png"
    },
    {
        "name":"sw2-next_png",
        "type":"image",
        "url":"sw2-next.png"
    },
    {
        "name":"sw2-prev_png",
        "type":"image",
        "url":"sw2-prev.png"
    },
    {
        "name":"ad-1_png",
        "type":"image",
        "url":"ad-1.png"
    },
    {
        "name":"banner_jpg",
        "type":"image",
        "url":"banner.jpg"
    },
    {
        "name":"bar_png",
        "type":"image",
        "url":"bar.png"
    }
];