var resData = [
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"foot-bg_jpg",
        "type":"image",
        "url":"foot-bg.jpg"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"banner-t_png",
        "type":"image",
        "url":"banner-t.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    }
];