var resData = [
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-2_png",
        "type":"image",
        "url":"sec-2.png"
    },
    {
        "name":"sec-3_png",
        "type":"image",
        "url":"sec-3.png"
    },
    {
        "name":"sec-4_png",
        "type":"image",
        "url":"sec-4.png"
    },
    {
        "name":"award-1_png",
        "type":"image",
        "url":"award-1.png"
    },
    {
        "name":"award-2_png",
        "type":"image",
        "url":"award-2.png"
    },
    {
        "name":"award-3_png",
        "type":"image",
        "url":"award-3.png"
    },
    {
        "name":"award-4_png",
        "type":"image",
        "url":"award-4.png"
    },
    {
        "name":"award-5_png",
        "type":"image",
        "url":"award-5.png"
    },
    {
        "name":"award-6_png",
        "type":"image",
        "url":"award-6.png"
    },
    {
        "name":"award-7_png",
        "type":"image",
        "url":"award-7.png"
    },
    {
        "name":"award-8_png",
        "type":"image",
        "url":"award-8.png"
    },
    {
        "name":"award-bg_png",
        "type":"image",
        "url":"award-bg.png"
    },
    {
        "name":"award-btn_png",
        "type":"image",
        "url":"award-btn.png"
    },
    {
        "name":"award-li_png",
        "type":"image",
        "url":"award-li.png"
    },
    {
        "name":"award-li-on_png",
        "type":"image",
        "url":"award-li-on.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"hy-title-3_png",
        "type":"image",
        "url":"hy-title-3.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"jia_png",
        "type":"image",
        "url":"jia.png"
    },
    {
        "name":"jian_png",
        "type":"image",
        "url":"jian.png"
    },
    {
        "name":"quan-1_png",
        "type":"image",
        "url":"quan-1.png"
    },
    {
        "name":"quan-2_png",
        "type":"image",
        "url":"quan-2.png"
    },
    {
        "name":"quan-3_png",
        "type":"image",
        "url":"quan-3.png"
    },
    {
        "name":"quan-4_png",
        "type":"image",
        "url":"quan-4.png"
    },
    {
        "name":"quan-6_png",
        "type":"image",
        "url":"quan-6.png"
    },
    {
        "name":"quan-7_png",
        "type":"image",
        "url":"quan-7.png"
    },
    {
        "name":"quan-8_png",
        "type":"image",
        "url":"quan-8.png"
    }
];