var resData = [
    {
        "name":"icon-zh_png",
        "type":"image",
        "url":"icon-zh.png"
    },
    {
        "name":"s-title_png",
        "type":"image",
        "url":"s-title.png"
    },
    {
        "name":"banner-1_png",
        "type":"image",
        "url":"banner-1.png"
    },
    {
        "name":"banner-2_png",
        "type":"image",
        "url":"banner-2.png"
    },
    {
        "name":"banner-3_png",
        "type":"image",
        "url":"banner-3.png"
    },
    {
        "name":"banner-4_png",
        "type":"image",
        "url":"banner-4.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"cake-bg_png",
        "type":"image",
        "url":"cake-bg.png"
    },
    {
        "name":"haoli_png",
        "type":"image",
        "url":"haoli.png"
    },
    {
        "name":"icon-77_png",
        "type":"image",
        "url":"icon-77.png"
    }
];