var resData = [
    {
        "name":"qy-3_png",
        "type":"image",
        "url":"qy-3.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"btn_png",
        "type":"image",
        "url":"btn.png"
    },
    {
        "name":"qy-1_png",
        "type":"image",
        "url":"qy-1.png"
    },
    {
        "name":"qy-2_png",
        "type":"image",
        "url":"qy-2.png"
    }
];