var resData = [
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"t-3_png",
        "type":"image",
        "url":"t-3.png"
    },
    {
        "name":"t-4_png",
        "type":"image",
        "url":"t-4.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"banner-t_png",
        "type":"image",
        "url":"banner-t.png"
    },
    {
        "name":"banner-wap_jpg",
        "type":"image",
        "url":"banner-wap.jpg"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"foot-bg_jpg",
        "type":"image",
        "url":"foot-bg.jpg"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"icon-1_png",
        "type":"image",
        "url":"icon-1.png"
    },
    {
        "name":"icon-1-h_png",
        "type":"image",
        "url":"icon-1-h.png"
    },
    {
        "name":"icon-2_png",
        "type":"image",
        "url":"icon-2.png"
    },
    {
        "name":"icon-2-h_png",
        "type":"image",
        "url":"icon-2-h.png"
    },
    {
        "name":"icon-3_png",
        "type":"image",
        "url":"icon-3.png"
    },
    {
        "name":"icon-3-h_png",
        "type":"image",
        "url":"icon-3-h.png"
    },
    {
        "name":"icon-4_png",
        "type":"image",
        "url":"icon-4.png"
    },
    {
        "name":"icon-4-h_png",
        "type":"image",
        "url":"icon-4-h.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"in-1_png",
        "type":"image",
        "url":"in-1.png"
    },
    {
        "name":"in-2_png",
        "type":"image",
        "url":"in-2.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"in-b-1_png",
        "type":"image",
        "url":"in-b-1.png"
    },
    {
        "name":"in-b-2_png",
        "type":"image",
        "url":"in-b-2.png"
    },
    {
        "name":"in-c-1_png",
        "type":"image",
        "url":"in-c-1.png"
    },
    {
        "name":"in-c-2_png",
        "type":"image",
        "url":"in-c-2.png"
    },
    {
        "name":"in-d-1_png",
        "type":"image",
        "url":"in-d-1.png"
    },
    {
        "name":"in-d-2_png",
        "type":"image",
        "url":"in-d-2.png"
    },
    {
        "name":"input_png",
        "type":"image",
        "url":"input.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    },
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    }
];