var resData = [
    {
        "name":"icon_30_png",
        "type":"image",
        "url":"icon_30.png"
    },
    {
        "name":"in-a-1_png",
        "type":"image",
        "url":"in-a-1.png"
    },
    {
        "name":"in-a-2_png",
        "type":"image",
        "url":"in-a-2.png"
    },
    {
        "name":"quan-60_png",
        "type":"image",
        "url":"quan-60.png"
    },
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-2_png",
        "type":"image",
        "url":"sec-2.png"
    },
    {
        "name":"sec-3_png",
        "type":"image",
        "url":"sec-3.png"
    },
    {
        "name":"sec-4_png",
        "type":"image",
        "url":"sec-4.png"
    },
    {
        "name":"snak-1_png",
        "type":"image",
        "url":"snak-1.png"
    },
    {
        "name":"snak-2_png",
        "type":"image",
        "url":"snak-2.png"
    },
    {
        "name":"snak-3_png",
        "type":"image",
        "url":"snak-3.png"
    },
    {
        "name":"snake_png",
        "type":"image",
        "url":"snake.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"hy-title-2_png",
        "type":"image",
        "url":"hy-title-2.png"
    },
    {
        "name":"icon_15_png",
        "type":"image",
        "url":"icon_15.png"
    }
];