var resData = [
    {
        "name":"word-1_png",
        "type":"image",
        "url":"word-1.png"
    },
    {
        "name":"word-2_png",
        "type":"image",
        "url":"word-2.png"
    },
    {
        "name":"word-3_png",
        "type":"image",
        "url":"word-3.png"
    },
    {
        "name":"baner_png",
        "type":"image",
        "url":"baner.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"pic-1_png",
        "type":"image",
        "url":"pic-1.png"
    },
    {
        "name":"pic-2_png",
        "type":"image",
        "url":"pic-2.png"
    },
    {
        "name":"pic-3_png",
        "type":"image",
        "url":"pic-3.png"
    },
    {
        "name":"pic-4_png",
        "type":"image",
        "url":"pic-4.png"
    }
];