var resData = [
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"title-5_png",
        "type":"image",
        "url":"title-5.png"
    },
    {
        "name":"title-6_png",
        "type":"image",
        "url":"title-6.png"
    },
    {
        "name":"title-7_png",
        "type":"image",
        "url":"title-7.png"
    },
    {
        "name":"title-8_png",
        "type":"image",
        "url":"title-8.png"
    },
    {
        "name":"title-9_png",
        "type":"image",
        "url":"title-9.png"
    },
    {
        "name":"top-img-1_png",
        "type":"image",
        "url":"top-img-1.png"
    },
    {
        "name":"top-img-2_png",
        "type":"image",
        "url":"top-img-2.png"
    },
    {
        "name":"top-img-3_png",
        "type":"image",
        "url":"top-img-3.png"
    },
    {
        "name":"top-img-4_png",
        "type":"image",
        "url":"top-img-4.png"
    },
    {
        "name":"top-txt-1_png",
        "type":"image",
        "url":"top-txt-1.png"
    },
    {
        "name":"top-txt-2_png",
        "type":"image",
        "url":"top-txt-2.png"
    },
    {
        "name":"top-txt-3_png",
        "type":"image",
        "url":"top-txt-3.png"
    },
    {
        "name":"top-txt-4_png",
        "type":"image",
        "url":"top-txt-4.png"
    },
    {
        "name":"whd_png",
        "type":"image",
        "url":"whd.png"
    },
    {
        "name":"xp-img_png",
        "type":"image",
        "url":"xp-img.png"
    },
    {
        "name":"zuhe-1_png",
        "type":"image",
        "url":"zuhe-1.png"
    },
    {
        "name":"zuhe-2_png",
        "type":"image",
        "url":"zuhe-2.png"
    },
    {
        "name":"zuhe-3_png",
        "type":"image",
        "url":"zuhe-3.png"
    },
    {
        "name":"zuhe-4_png",
        "type":"image",
        "url":"zuhe-4.png"
    },
    {
        "name":"zuhe-5_png",
        "type":"image",
        "url":"zuhe-5.png"
    },
    {
        "name":"1yuan_png",
        "type":"image",
        "url":"1yuan.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"banner-logo_png",
        "type":"image",
        "url":"banner-logo.png"
    },
    {
        "name":"banner-word_png",
        "type":"image",
        "url":"banner-word.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"car_png",
        "type":"image",
        "url":"car.png"
    },
    {
        "name":"car-on_png",
        "type":"image",
        "url":"car-on.png"
    },
    {
        "name":"close_png",
        "type":"image",
        "url":"close.png"
    },
    {
        "name":"dot_png",
        "type":"image",
        "url":"dot.png"
    },
    {
        "name":"ewm_png",
        "type":"image",
        "url":"ewm.png"
    },
    {
        "name":"hd-img-1_png",
        "type":"image",
        "url":"hd-img-1.png"
    },
    {
        "name":"hd-img-2_png",
        "type":"image",
        "url":"hd-img-2.png"
    },
    {
        "name":"hd-img-3_png",
        "type":"image",
        "url":"hd-img-3.png"
    },
    {
        "name":"hd-img-4_png",
        "type":"image",
        "url":"hd-img-4.png"
    },
    {
        "name":"hd-img-5_png",
        "type":"image",
        "url":"hd-img-5.png"
    },
    {
        "name":"hd-img-6_png",
        "type":"image",
        "url":"hd-img-6.png"
    },
    {
        "name":"hd-img-7_png",
        "type":"image",
        "url":"hd-img-7.png"
    },
    {
        "name":"hd-img-8_png",
        "type":"image",
        "url":"hd-img-8.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"img-4_png",
        "type":"image",
        "url":"img-4.png"
    },
    {
        "name":"img-5_png",
        "type":"image",
        "url":"img-5.png"
    },
    {
        "name":"img-6_png",
        "type":"image",
        "url":"img-6.png"
    },
    {
        "name":"jiang-1_png",
        "type":"image",
        "url":"jiang-1.png"
    },
    {
        "name":"jiang-2_png",
        "type":"image",
        "url":"jiang-2.png"
    },
    {
        "name":"jiang-3_png",
        "type":"image",
        "url":"jiang-3.png"
    },
    {
        "name":"jiang-4_png",
        "type":"image",
        "url":"jiang-4.png"
    },
    {
        "name":"jiang-5_png",
        "type":"image",
        "url":"jiang-5.png"
    },
    {
        "name":"jiang-6_png",
        "type":"image",
        "url":"jiang-6.png"
    },
    {
        "name":"jiang-7_png",
        "type":"image",
        "url":"jiang-7.png"
    },
    {
        "name":"manzeng_png",
        "type":"image",
        "url":"manzeng.png"
    }
];