var resData = [
  {
    "name":"t1-arrow_png",
    "type":"image",
    "url":"t1-arrow.png"
  },
  {
    "name":"t2-arrow_png",
    "type":"image",
    "url":"t2-arrow.png"
  },
  {
    "name":"title_png",
    "type":"image",
    "url":"title.png"
  },
  {
    "name":"top-bg_png",
    "type":"image",
    "url":"top-bg.png"
  },
  {
    "name":"bg-spliter_jpg",
    "type":"image",
    "url":"bg-spliter.jpg"
  },
  {
    "name":"footer-banner_jpg",
    "type":"image",
    "url":"footer-banner.jpg"
  },
  {
    "name":"main-text_png",
    "type":"image",
    "url":"main-text.png"
  },
  {
    "name":"p1-1_png",
    "type":"image",
    "url":"p1-1.png"
  },
  {
    "name":"p1-2_png",
    "type":"image",
    "url":"p1-2.png"
  },
  {
    "name":"p2-1_png",
    "type":"image",
    "url":"p2-1.png"
  },
  {
    "name":"p2-2_png",
    "type":"image",
    "url":"p2-2.png"
  },
  {
    "name":"p3_png",
    "type":"image",
    "url":"p3.png"
  },
  {
    "name":"p3-3_png",
    "type":"image",
    "url":"p3-3.png"
  },
  {
    "name":"price1_png",
    "type":"image",
    "url":"price1.png"
  },
  {
    "name":"price2_png",
    "type":"image",
    "url":"price2.png"
  },
  {
    "name":"t1_png",
    "type":"image",
    "url":"t1.png"
  }];