var resData = [
    {
        "name":"banner-bg_png",
        "type":"image",
        "url":"banner-bg.png"
    },
    {
        "name":"banner-cake_png",
        "type":"image",
        "url":"banner-cake.png"
    },
    {
        "name":"banner-cake-bj_png",
        "type":"image",
        "url":"banner-cake-bj.png"
    },
    {
        "name":"banner-title_png",
        "type":"image",
        "url":"banner-title.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-1-1_png",
        "type":"image",
        "url":"cake-1-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-btn_png",
        "type":"image",
        "url":"cake-btn.png"
    },
    {
        "name":"cake-kuang_png",
        "type":"image",
        "url":"cake-kuang.png"
    },
    {
        "name":"cake-price_png",
        "type":"image",
        "url":"cake-price.png"
    },
    {
        "name":"img-1_png",
        "type":"image",
        "url":"img-1.png"
    },
    {
        "name":"img-2_png",
        "type":"image",
        "url":"img-2.png"
    },
    {
        "name":"img-3_png",
        "type":"image",
        "url":"img-3.png"
    },
    {
        "name":"img-4_png",
        "type":"image",
        "url":"img-4.png"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    },
    {
        "name":"line-2_png",
        "type":"image",
        "url":"line-2.png"
    },
    {
        "name":"line-3_jpg",
        "type":"image",
        "url":"line-3.jpg"
    },
    {
        "name":"mengbao_png",
        "type":"image",
        "url":"mengbao.png"
    },
    {
        "name":"mengbao-bj_png",
        "type":"image",
        "url":"mengbao-bj.png"
    },
    {
        "name":"play-btn_png",
        "type":"image",
        "url":"play-btn.png"
    },
    {
        "name":"reduce-1_png",
        "type":"image",
        "url":"reduce-1.png"
    },
    {
        "name":"reduce-2_png",
        "type":"image",
        "url":"reduce-2.png"
    },
    {
        "name":"reduce-3_png",
        "type":"image",
        "url":"reduce-3.png"
    },
    {
        "name":"reduce-4_png",
        "type":"image",
        "url":"reduce-4.png"
    },
    {
        "name":"reduce-5_png",
        "type":"image",
        "url":"reduce-5.png"
    },
    {
        "name":"reduce-6_png",
        "type":"image",
        "url":"reduce-6.png"
    },
    {
        "name":"satang_gif",
        "type":"image",
        "url":"satang.gif"
    },
    {
        "name":"step-1_png",
        "type":"image",
        "url":"step-1.png"
    },
    {
        "name":"step-2_png",
        "type":"image",
        "url":"step-2.png"
    },
    {
        "name":"step-3_png",
        "type":"image",
        "url":"step-3.png"
    },
    {
        "name":"step-txt_png",
        "type":"image",
        "url":"step-txt.png"
    },
    {
        "name":"s-title_png",
        "type":"image",
        "url":"s-title.png"
    },
    {
        "name":"t-1_png",
        "type":"image",
        "url":"t-1.png"
    },
    {
        "name":"t-2_png",
        "type":"image",
        "url":"t-2.png"
    },
    {
        "name":"v-bj_png",
        "type":"image",
        "url":"v-bj.png"
    },
    {
        "name":"video-img_png",
        "type":"image",
        "url":"video-img.png"
    },
    {
        "name":"v-img_png",
        "type":"image",
        "url":"v-img.png"
    },
    {
        "name":"vode-kuang_png",
        "type":"image",
        "url":"vode-kuang.png"
    },
    {
        "name":"wanfa_png",
        "type":"image",
        "url":"wanfa.png"
    },
    {
        "name":"zp_png",
        "type":"image",
        "url":"zp.png"
    },
    {
        "name":"add-1_png",
        "type":"image",
        "url":"add-1.png"
    },
    {
        "name":"add-2_png",
        "type":"image",
        "url":"add-2.png"
    },
    {
        "name":"add-3_png",
        "type":"image",
        "url":"add-3.png"
    },
    {
        "name":"add-4_png",
        "type":"image",
        "url":"add-4.png"
    },
    {
        "name":"add-5_png",
        "type":"image",
        "url":"add-5.png"
    },
    {
        "name":"add-6_png",
        "type":"image",
        "url":"add-6.png"
    }
];