var resData = [
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"bg2_png",
        "type":"image",
        "url":"bg2.png"
    },
    {
        "name":"buybtn_png",
        "type":"image",
        "url":"buybtn.png"
    },
    {
        "name":"cake1_png",
        "type":"image",
        "url":"cake1.png"
    },
    {
        "name":"cake2_png",
        "type":"image",
        "url":"cake2-beijing.png"
    },
    {
        "name":"cake3_png",
        "type":"image",
        "url":"cake3-beijing.png"
    },
    {
        "name":"fruit1_png",
        "type":"image",
        "url":"fruit1.png"
    },
    {
        "name":"fruit2_png",
        "type":"image",
        "url":"fruit2.png"
    },
    {
        "name":"i1_png",
        "type":"image",
        "url":"i1.png"
    },
    {
        "name":"i2_png",
        "type":"image",
        "url":"i2.png"
    },
    {
        "name":"i4_png",
        "type":"image",
        "url":"i4-beijing.png"
    },
    {
        "name":"i5_png",
        "type":"image",
        "url":"i5-beijing.png"
    },
    {
        "name":"i6_png",
        "type":"image",
        "url":"i6.png"
    },
    {
        "name":"i7_png",
        "type":"image",
        "url":"i7.png"
    },
    {
        "name":"ronghua_png",
        "type":"image",
        "url":"ronghua.png"
    },
    {
        "name":"text1_png",
        "type":"image",
        "url":"text1.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"word1_png",
        "type":"image",
        "url":"word1.png"
    },
    {
        "name":"word2_png",
        "type":"image",
        "url":"word2-beijing.png"
    },
    {
        "name":"word3_png",
        "type":"image",
        "url":"word3-beijing.png"
    },
    {
        "name":"candle_png",
        "type":"image",
        "url":"candle.png"
    },
    {
        "name":"cris2_png",
        "type":"image",
        "url":"cris2.png"
    }
];