var resData = [
    {
        "name":"price-2_png",
        "type":"image",
        "url":"price-2.png"
    },
    {
        "name":"sec-1_png",
        "type":"image",
        "url":"sec-1.png"
    },
    {
        "name":"sec-2_png",
        "type":"image",
        "url":"sec-2.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"tree_png",
        "type":"image",
        "url":"tree.png"
    },
    {
        "name":"tree-txt_png",
        "type":"image",
        "url":"tree-txt.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"code_png",
        "type":"image",
        "url":"code.png"
    },
    {
        "name":"price-1_png",
        "type":"image",
        "url":"price-1.png"
    }
];