var resData = [
    {
        "name":"prev_png",
        "type":"image",
        "url":"prev.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"bg_png",
        "type":"image",
        "url":"bg.png"
    },
    {
        "name":"btn-1_png",
        "type":"image",
        "url":"btn-1.png"
    },
    {
        "name":"btn-2_png",
        "type":"image",
        "url":"btn-2.png"
    },
    {
        "name":"code_png",
        "type":"image",
        "url":"code.png"
    },
    {
        "name":"French_png",
        "type":"image",
        "url":"French.png"
    },
    {
        "name":"lipin_png",
        "type":"image",
        "url":"lipin.png"
    },
    {
        "name":"next_png",
        "type":"image",
        "url":"next.png"
    }
];