var resData = [
    {
        "name":"qx-cake_png",
        "type":"image",
        "url":"qx-cake.png"
    },
    {
        "name":"s-bg-1_png",
        "type":"image",
        "url":"s-bg-1.png"
    },
    {
        "name":"s-bg-2_png",
        "type":"image",
        "url":"s-bg-2.png"
    },
    {
        "name":"tip_png",
        "type":"image",
        "url":"tip.png"
    },
    {
        "name":"wx_png",
        "type":"image",
        "url":"wx.png"
    },
    {
        "name":"wx-bg_png",
        "type":"image",
        "url":"wx-bg.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"box_png",
        "type":"image",
        "url":"box.png"
    },
    {
        "name":"buy-btn_png",
        "type":"image",
        "url":"buy-btn.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"close2_png",
        "type":"image",
        "url":"close2.png"
    },
    {
        "name":"foot-bg_png",
        "type":"image",
        "url":"foot-bg.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    }
];