var resData = [
    {
        "name":"part2_title_4_png",
        "type":"image",
        "url":"part2_title_4.png"
    },
    {
        "name":"s-title-1_png",
        "type":"image",
        "url":"s-title-1.png"
    },
    {
        "name":"s-title-2_png",
        "type":"image",
        "url":"s-title-2.png"
    },
    {
        "name":"banner_png",
        "type":"image",
        "url":"banner.png"
    },
    {
        "name":"foot_bg_png",
        "type":"image",
        "url":"foot_bg.png"
    },
    {
        "name":"part1_cake_1_png",
        "type":"image",
        "url":"part1_cake_1.png"
    },
    {
        "name":"part1_cake_2_png",
        "type":"image",
        "url":"part1_cake_2.png"
    },
    {
        "name":"part1_cake_3_png",
        "type":"image",
        "url":"part1_cake_3.png"
    },
    {
        "name":"part1_cake_4_png",
        "type":"image",
        "url":"part1_cake_4.png"
    },
    {
        "name":"part1_title_1_png",
        "type":"image",
        "url":"part1_title_1.png"
    },
    {
        "name":"part1_title_2_png",
        "type":"image",
        "url":"part1_title_2.png"
    },
    {
        "name":"part1_title_3_png",
        "type":"image",
        "url":"part1_title_3.png"
    },
    {
        "name":"part1_title_4_png",
        "type":"image",
        "url":"part1_title_4.png"
    },
    {
        "name":"part2_cake_1_png",
        "type":"image",
        "url":"part2_cake_1.png"
    },
    {
        "name":"part2_cake_2_png",
        "type":"image",
        "url":"part2_cake_2.png"
    },
    {
        "name":"part2_cake_3_png",
        "type":"image",
        "url":"part2_cake_3.png"
    },
    {
        "name":"part2_cake_4_png",
        "type":"image",
        "url":"part2_cake_4.png"
    },
    {
        "name":"part2_title_1_png",
        "type":"image",
        "url":"part2_title_1.png"
    },
    {
        "name":"part2_title_2_png",
        "type":"image",
        "url":"part2_title_2.png"
    },
    {
        "name":"part2_title_3_png",
        "type":"image",
        "url":"part2_title_3.png"
    }
];