var resData = [
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"bg2_png",
        "type":"image",
        "url":"bg2.png"
    },
    {
        "name":"buybtn_png",
        "type":"image",
        "url":"buybtn.png"
    },
    {
        "name":"buybtn-out_png",
        "type":"image",
        "url":"buybtn-out.png"
    },
    {
        "name":"cake1_png",
        "type":"image",
        "url":"cake1.png"
    },
    {
        "name":"cake2_png",
        "type":"image",
        "url":"cake2.png"
    },
    {
        "name":"cake3_png",
        "type":"image",
        "url":"cake3.png"
    },
    {
        "name":"cake4_png",
        "type":"image",
        "url":"cake4.png"
    },
    {
        "name":"cake5_png",
        "type":"image",
        "url":"cake5.png"
    },
    {
        "name":"fruit1_png",
        "type":"image",
        "url":"fruit1.png"
    },
    {
        "name":"fruit2_png",
        "type":"image",
        "url":"fruit2.png"
    },
    {
        "name":"fruit3_png",
        "type":"image",
        "url":"fruit3.png"
    },
    {
        "name":"fruit4_png",
        "type":"image",
        "url":"fruit4.png"
    },
    {
        "name":"i1_png",
        "type":"image",
        "url":"i1.png"
    },
    {
        "name":"i2_png",
        "type":"image",
        "url":"i2.png"
    },
    {
        "name":"i3_png",
        "type":"image",
        "url":"i3.png"
    },
    {
        "name":"i4_png",
        "type":"image",
        "url":"i4.png"
    },
    {
        "name":"i5_png",
        "type":"image",
        "url":"i5.png"
    },
    {
        "name":"i6_png",
        "type":"image",
        "url":"i6.png"
    },
    {
        "name":"i7_png",
        "type":"image",
        "url":"i7.png"
    },
    {
        "name":"i8_png",
        "type":"image",
        "url":"i8.png"
    },
    {
        "name":"i9_png",
        "type":"image",
        "url":"i9.png"
    },
    {
        "name":"i10_png",
        "type":"image",
        "url":"i10.png"
    },
    {
        "name":"minus_png",
        "type":"image",
        "url":"minus.png"
    },
    {
        "name":"photo1_png",
        "type":"image",
        "url":"photo1.png"
    },
    {
        "name":"photo2_png",
        "type":"image",
        "url":"photo2.png"
    },
    {
        "name":"plus_png",
        "type":"image",
        "url":"plus.png"
    },
    {
        "name":"ronghua_png",
        "type":"image",
        "url":"ronghua.png"
    },
    {
        "name":"text1_png",
        "type":"image",
        "url":"text1.png"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"word1_png",
        "type":"image",
        "url":"word1.png"
    },
    {
        "name":"word2_png",
        "type":"image",
        "url":"word2.png"
    },
    {
        "name":"word3_png",
        "type":"image",
        "url":"word3.png"
    },
    {
        "name":"word4_png",
        "type":"image",
        "url":"word4.png"
    },
    {
        "name":"word5_png",
        "type":"image",
        "url":"word5.png"
    },
    {
        "name":"candle_png",
        "type":"image",
        "url":"candle.png"
    },
    {
        "name":"cris_png",
        "type":"image",
        "url":"cris.png"
    },
    {
        "name":"cris2_png",
        "type":"image",
        "url":"cris2.png"
    }
];