var resData = [
    {
        "name":"words-1_png",
        "type":"image",
        "url":"words-1.png"
    },
    {
        "name":"words-2_png",
        "type":"image",
        "url":"words-2.png"
    },
    {
        "name":"words-2-bg_png",
        "type":"image",
        "url":"words-2-bg.png"
    },
    {
        "name":"words-3_png",
        "type":"image",
        "url":"words-3.png"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"flower_png",
        "type":"image",
        "url":"flower.png"
    },
    {
        "name":"more_png",
        "type":"image",
        "url":"more.png"
    },
    {
        "name":"q-cake_png",
        "type":"image",
        "url":"q-cake.png"
    },
    {
        "name":"qiqiu-box_png",
        "type":"image",
        "url":"qiqiu-box.png"
    },
    {
        "name":"quqi-1_png",
        "type":"image",
        "url":"quqi-1.png"
    },
    {
        "name":"quqi-2_png",
        "type":"image",
        "url":"quqi-2.png"
    },
    {
        "name":"quqi-3_png",
        "type":"image",
        "url":"quqi-3.png"
    },
    {
        "name":"ren-box_png",
        "type":"image",
        "url":"ren-box.png"
    },
    {
        "name":"ren-hs_png",
        "type":"image",
        "url":"ren-hs.png"
    },
    {
        "name":"ren-pao_png",
        "type":"image",
        "url":"ren-pao.png"
    },
    {
        "name":"ren-quqi_png",
        "type":"image",
        "url":"ren-quqi.png"
    },
    {
        "name":"ren-ti_png",
        "type":"image",
        "url":"ren-ti.png"
    },
    {
        "name":"ren-yao_png",
        "type":"image",
        "url":"ren-yao.png"
    },
    {
        "name":"ren-you_png",
        "type":"image",
        "url":"ren-you.png"
    }
];