var resData = [
    {
        "name":"quanyi-4_png",
        "type":"image",
        "url":"quanyi-4.png"
    },
    {
        "name":"banner-wap_png",
        "type":"image",
        "url":"banner-wap.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"hy-title-1_png",
        "type":"image",
        "url":"hy-title-1.png"
    },
    {
        "name":"in-1_png",
        "type":"image",
        "url":"in-1.png"
    },
    {
        "name":"in-2_png",
        "type":"image",
        "url":"in-2.png"
    },
    {
        "name":"quan_png",
        "type":"image",
        "url":"quan.png"
    },
    {
        "name":"quanyi-3_png",
        "type":"image",
        "url":"quanyi-3.png"
    }
];