var resData = [
    {
        "name":"load_gif",
        "type":"image",
        "url":"load.gif"
    },
    {
        "name":"menpiao_png",
        "type":"image",
        "url":"menpiao.png"
    },
    {
        "name":"mins_png",
        "type":"image",
        "url":"mins.png"
    },
    {
        "name":"price-title_png",
        "type":"image",
        "url":"price-title.png"
    },
    {
        "name":"s_png",
        "type":"image",
        "url":"s.png"
    },
    {
        "name":"add_png",
        "type":"image",
        "url":"add.png"
    },
    {
        "name":"bg_jpg",
        "type":"image",
        "url":"bg.jpg"
    },
    {
        "name":"b-title_png",
        "type":"image",
        "url":"b-title.png"
    },
    {
        "name":"cake_png",
        "type":"image",
        "url":"cake.png"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"duihua_png",
        "type":"image",
        "url":"duihua.png"
    },
    {
        "name":"footer-bg_png",
        "type":"image",
        "url":"footer-bg.png"
    },
    {
        "name":"go_png",
        "type":"image",
        "url":"go.png"
    },
    {
        "name":"go-btn_png",
        "type":"image",
        "url":"go-btn.png"
    },
    {
        "name":"gou_png",
        "type":"image",
        "url":"gou.png"
    },
    {
        "name":"gui-1_png",
        "type":"image",
        "url":"gui-1.png"
    },
    {
        "name":"guigou_png",
        "type":"image",
        "url":"guigou.png"
    },
    {
        "name":"guitou_png",
        "type":"image",
        "url":"guitou.png"
    },
    {
        "name":"huaA_png",
        "type":"image",
        "url":"huaA.png"
    },
    {
        "name":"huaB_png",
        "type":"image",
        "url":"huaB.png"
    },
    {
        "name":"hun_png",
        "type":"image",
        "url":"hun.png"
    },
    {
        "name":"line_png",
        "type":"image",
        "url":"line.png"
    }
];