var resData = [
    {
        "name":"ren_png",
        "type":"image",
        "url":"ren.png"
    },
    {
        "name":"s1-bg_jpg",
        "type":"image",
        "url":"s1-bg.jpg"
    },
    {
        "name":"s3-bg_jpg",
        "type":"image",
        "url":"s3-bg.jpg"
    },
    {
        "name":"s6-bg_jpg",
        "type":"image",
        "url":"s6-bg.jpg"
    },
    {
        "name":"title_png",
        "type":"image",
        "url":"title.png"
    },
    {
        "name":"title-1_png",
        "type":"image",
        "url":"title-1.png"
    },
    {
        "name":"title-2_png",
        "type":"image",
        "url":"title-2.png"
    },
    {
        "name":"title-3_png",
        "type":"image",
        "url":"title-3.png"
    },
    {
        "name":"title-4_png",
        "type":"image",
        "url":"title-4.png"
    },
    {
        "name":"banner-1_png",
        "type":"image",
        "url":"banner-1.png"
    },
    {
        "name":"banner-2_png",
        "type":"image",
        "url":"banner-2.png"
    },
    {
        "name":"banner-3_png",
        "type":"image",
        "url":"banner-3.png"
    },
    {
        "name":"banner-bg_jpg",
        "type":"image",
        "url":"banner-bg.jpg"
    },
    {
        "name":"cake-1_png",
        "type":"image",
        "url":"cake-1.png"
    },
    {
        "name":"cake-2_png",
        "type":"image",
        "url":"cake-2.png"
    },
    {
        "name":"cake-3_png",
        "type":"image",
        "url":"cake-3.png"
    },
    {
        "name":"cake-4_png",
        "type":"image",
        "url":"cake-4.png"
    },
    {
        "name":"in-l_png",
        "type":"image",
        "url":"in-l.png"
    },
    {
        "name":"in-r_png",
        "type":"image",
        "url":"in-r.png"
    },
    {
        "name":"pic_png",
        "type":"image",
        "url":"pic.png"
    }
];